### ISSUE TITLE
changing from bash to zsh

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1003]
Before I mess too much up, in updating my OS on my Mac I went to zsh. `jupyter` does not appear to do anything. Any advice

```
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Stevens-MacBook-Pro:Volumes sr320$ ls
GoogleDrive	Macintosh HD
Stevens-MacBook-Pro:Volumes sr320$ jupyter notebook
-bash: jupyter: command not found
Stevens-MacBook-Pro:Volumes sr320$ conda update conda
-bash: conda: command not found
Stevens-MacBook-Pro:Volumes sr320$ chsh -s /bin/zsh
Changing shell for sr320.
Password for sr320: 
Stevens-MacBook-Pro:Volumes sr320$ jupyter notebook
-bash: jupyter: command not found
```

**Comment by sr320** [comment]
progress - 
I was able to reinstall Anaconda and launch Jupyter Lab and Notebook, but cannot seem to open from command-line

https://d.pr/i/togbsv

**Comment by kubu4** [comment]
This is a `$PATH` issue, combined with a change in the way Anaconda install goes now.

For example, when I run the following:

`which conda`

I get:

`/home/samb/programs/miniconda3/condabin/conda`

However, all of the Anaconda packages are actually located here:

`/home/samb/programs/miniconda3/bin`

Knowing this, you can launch a Jupyter notebook by using the following command:

`/home/samb/programs/miniconda3/bin/jupyter-lab`

or

`/home/samb/programs/miniconda3/bin/jupyter-notebook`

If you don't want to do that every time, I think you can edit your `zsh` equivalent to a `.bashrc` file so that `/home/samb/programs/miniconda3/bin` is pre-pended to your `$PATH`. 

Of course, another solution is to look up how to start an Anconda package using the new installation configuration. My guess is they probably want people to use environments to manage things these days.
