### ISSUE TITLE
Oyster gene merging issue

### ISSUE THREAD

**Issue by meganewing** [RobertsLab/resources#1027]
Okay so I am trying to merge these two files by loci#, but in one of the files there is repeated loci# and it seems to be deleting all the duplicates. The two files are locusUniprotMerge.csv and top25markers_allcells_072720(1).txt 

How do I merge them without deleting the duplicates? I've attached the files, a description of all the files that may be mentioned in my code, and the working R code I have for this. 
[oystergenemergingissue.zip](https://github.com/RobertsLab/resources/files/5544166/oystergenemergingissue.zip)

**Comment by kubu4** [comment]
A couple of things.

1. I'm not seeing a column labelled as `loci#` (or something similar) in `locusUniprotMerge.csv` or in `top25markers_allcells_072720(1).txt` (as they are in the zip file provided). Here's what I see when looking at `top25markers_allcells_072720(1).txt`:


```shell
head top25markers_allcells_072720\ \(1\).txt | column -t
gene_id       gene_short_name  cell_group  marker_score        mean_expression    fraction_expressing  specificity         pseudo_R2            marker_test_p_value    marker_test_q_value    V2
LOC105340423  LOC105340423     11          0.140614816815872   0.86873326399805   0.652618135376756    0.215462625375398   0.162046165755659    4.54986718036635e-81   2.45528122547854e-75   zinc             finger            protein       235
LOC105340423  LOC105340423     9           0.152707557104033   0.85312153122531   0.718525179856115    0.212529165831896   0.20363463616303     1.01436024412999e-119  5.47387333421821e-114  zinc             finger            protein       235
LOC105325769  LOC105325769     12          0.182398047688628   5.93822484614347   0.998260869565217    0.182715814322231   0.483798567808459    9.60285694237628e-206  5.18206651467005e-200  disks            large-associated  protein       5
```

Which column do you want to work with? I'm guessing the very last column (one of the unlabelled ones)?

2. Your code doesn't seem to reference `locusUniprotMerge.csv` anywhere.

3. Your R code references the following files/objects/data frames, but they weren't in the zip file:

- `oysterblast`

- `geneAndSampleID.csv`

- `oysterblast_uniprot.csv`

Without those files, we can't fully execute your R script.

**Comment by sr320** [comment]
I suggest making this a GH repo / R project..

**Comment by sr320** [comment]
Where does this stand?

**Comment by meganewing** [comment]
https://github.com/meganewing/OysterGeneAssist

Been looking into how the merging function works, can't seem to find anything about _keeping_ duplicates, only removing them :/ Is there another function/command that would be good to try to keep the duplicates?

**Comment by kubu4** [comment]
A join command/function would keep duplicates. Did you happen to address my points from my previous comment?

**Comment by sr320** [comment]
also organize repo (code, data, analyses)..
Recall `join` from our reading in class. and see example @ https://github.com/fish546-2021/steven-duck/blob/main/code/02-Adding-annotations.ipynb

**Comment by meganewing** [comment]
Yeah I added all the code to the repo and realized I mistakenly referred to locusMerge as locusUniprotMerge. Also was using "loci#" colloquially. The actual column names are "V2" for locusMerge and "gene_id" for top25markers_allcells_072720(1)

I'll try `join` !

**Comment by meganewing** [comment]
Having an issue with sorting the file locusMerge.csv by column 14. 

 'combineLocusInfoAndMarkerInfo_0125.ipynb' is the jupyter notebook for joining the files 'locusMerge.csv' and 'top25marker.csv' -- found in the repo below in the code file

Line 111 is where I'm running into the issue, but I'm not sure if it will show up as the same line when you open up because I am still learning how jupyter notebook works. 

Repo I have going for this which has all the data files I'm referencing and working code: 
https://github.com/meganewing/OysterGeneAssist

**Comment by kubu4** [comment]
I believe the problem is that `locusMerge.csv` has an inconsistent number of fields throughout the file.

To count the number of fields, you can use the following `awk` command:

`awk -F","  '{print NF}' locusMerge.csv`

This will spit out the number of fields in each line, so it will spit out 549 lines of numbers. To see the results in a more informative fashion, modify the above command like so:

`awk -F","  '{print NF}' locusMerge.csv | sort`

Since you're sorting your file on field 14, I'm assuming you're expecting that each record (i.e. line) has only 14 fields. The output of the above command with the sort reveals that you have many lines with more than 14 fields.

With this being the case, `sort` gets kinda screwed up (at least with what you're wanting it to do) when you only specify a single value as the sort field (i.e. key). If a second field is not supplied, `sort` will utilize any subsequent fields on a line to continue sorting.

With that out of the way, you probably should limit the sorting to _just_ the 14th field. You can do that like so:

`sort -k14,14 locusMerge.csv > locusMerge_sorted.csv`

Then, checking that the output file is properly sorted:

`sort -c -k14,14 locusMerge_sorted.csv`

That should do it!

Also, notice that I did _not_ specify numeric sort (`-n` argument) like you did in your Jupyter notebook. Numeric sort won't work on non-numeric fields. Field 14 is a string (i.e. words, text) and is not numeric (i.e. just a number).

Finally, I can tell that these files were written out from R because each field is quoted. I'm not sure what impact (if any) this has on trying to sort data using bash. It would be best if you changed the `write.csv` command to include this argument `quote=FALSE`. Dropping the quotes also makes it much easier to read.

Anyway, let me know how it goes!

**Comment by kubu4** [comment]
Sorry, I just realized I didn't explain the `awk` command! Here's how it works:

`awk -F"," '{print NF}'`

`awk`: Tells bash to use the program `awk`

`-F","`: Tells `awk` that the field separator is a comma. The default field separator is a tab.

`'{print NF}'`: Tells `awk` to print the number of fields on each line of the input file. `NF` is a built-in `awk` variable which (as you may be able to guess) stands for Number of Fields.

**Comment by kubu4** [comment]
Also, bigger picture... I'd address the differing number of fields in your file before continuing any work on the sorting.

**Comment by kubu4** [comment]
Finally, I neglected to consider this until now (and it's important):

How does `sort` determine what the field separator is? This should've been the first thing I started troubleshooting; sorry!

From the `sort` manual:

```
-t	char, --field-separator=char
	     Use char as a field separator character.  The initial char	is not
	     considered	to be part of a	field when determining key offsets.
	     Each occurrence of	char is	significant (for example, "charchar"
	     delimits an empty field).	If -t is not specified,	the default
	     field separator is	a sequence of blank space characters, and con-
	     secutive blank spaces do not delimit an empty field, however, the
	     initial blank space is considered part of a field when determin-
	     ing key offsets.  To use NUL as field separator, use -t '\0'.
```

I don't have time any more today to work on this, but this is one very obvious issue (in hindsight, of course) with the `sort` commands that both of us used.
