### ISSUE TITLE
RNAseq - lanes vs. runs clarification question

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1032]
RNAseq data: 
We get 4 files per library. 2 lanes and 2 runs.

What are the differences between the lanes and runs?

**Comment by kubu4** [comment]
Can you provide an example of files that fall into each of the terms you're using? I'm not sure I totally follow what you're asking.

**Comment by grace-ac** [comment]
In this google sheets tab called "LIBRARIES": https://docs.google.com/spreadsheets/d/1d17yg5F5gKKC66O8QkTIlPxljJeuX7ZsG46pkBr1lNQ/edit#gid=0 

There's 2 rows per library. Each row is a different Lane. if you just look at the first row, there are two "trims" per lane, R1 and R2.

I think I was assuming the "R" stands for "run", but maybe it stands for something else?

**Comment by kubu4** [comment]
"R" stands for "read". We did paired end sequencing, so each library gets sequenced in two directions (I. E . Read 1 and Read 2). Does that help?

**Comment by kubu4** [comment]
Lanes are generally are indicated by the "*_001*" in the filenames. If a library was sequenced on multiple lanes, that number is incremented by one for each additional lane of sequencing.

**Comment by grace-ac** [comment]
that helps!! Thanks!

**Comment by afcoyle** [comment]
Hey, quick question on this! My interpretation is that each library is split up into 2 reads (Read 1 and Read 2). Due to sequencing limitations, most reads were split between 2+ lanes, but I can put those back together.

Basically, let's say I have 4 files in a library, and am trying to compare gene expression. Can I combine the different lanes for each read (say, can Library1_Read1_Lane1 be combined with Library1_Read1_Lane2)?

**Comment by kubu4** [comment]
Yes.
