### ISSUE TITLE
Issue accessing Cutadapt on Mox 

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#1053]
Trying to use TrimGalore on Mox, which uses Cutadapt. I see Cutadapt listed on the Mox wiki as an installed software, but I don't see it in the Mox /gscratch/srlab/programs/ directory, or in the anaconda3/bin subdirectory. Anyone know if it is still on Mox in the lab's shared resources, and if so where?

**Comment by kubu4** [comment]
Firstly, thanks for pointing out the out-dated software listing on the Mox wiki! I will update that next week. Sorry about that!

Secondly, are you encountering an error? If yes, can you please post you command and the resulting error message?

Finally, there's an existing installation of TrimGalore (`/gscratch/srlab/programs/TrimGalore-0.4.5/trim_galore`) that seems to run without issue. Do you need the newer version that you tried installing yesterday?

**Comment by kubu4** [comment]
> Finally, there's an existing installation of TrimGalore (/gscratch/srlab/programs/TrimGalore-0.4.5/trim_galore) that seems to run without issue.

This is _wrong_! Please ignore.

I knew there was something wonky with `cutadapt`. It's part of an Anaconda package, so you'll need to install `cutadapt` yourself, via Anaconda. This means you'll have your own, separate installation of `cutadapt` that isn't available to anyone else. This is why I'm able to run it, as well as Shelly - we've both installed it independently. 

A "shared" installation of `cutdapt` is/was a pain to setup because it's required to be in a the user's system `$PATH`. It appears that `fastqc` and `TrimGalore` do not offer an option to point to the `cutadapt` install location, which would get around the need to use the system `$PATH`.

With all that being said, I might work on a "shared" install next week. The drawback is that it's not obvious to new users (although, I guess this situation as a whole isn't obvious to new users, either) on where to find it and how to use it...

**Comment by kubu4** [comment]
Please follow the `cutadapt` Conda installation instructions here:

https://cutadapt.readthedocs.io/en/stable/installation.html#installation-with-conda

**Comment by kubu4** [comment]
>  I might work on a "shared" install next week. 

Looking into this a bit, I'm remember why it hasn't been done. I will _not_ be doing this. This is due to the fact that `pip` is not available (which is required for the "shared" installation) and is extremely difficult to install on the cluster (due to the fact that standard installation methods required access to system directories that are locked down by Mox admins; rightfully so). This has always been an issue with Python-based software and it's extremely annoying.

If you have any problems with the Anaconda install, feel free to open a new issue.

**Comment by kubu4** [comment]
Another thing that I'll add about `cutadapt` is that I'm pretty sure it's single-threaded. As such, it's very slow. That's the main reason I switched to using `fastp`. It's multi-threaded (runs up to 16 threads). Plus, `fastp` also generates it's own before/after reports (similar to `FastQC`) and the output is compatible with `MultiQC`.

**Comment by laurahspencer** [comment]
Thanks for all the insight and investigation, Sam.  I was able to run TrimGalore after doing a few additional things. FYI my use of Mox thus far has been _very_ limited, so I had to install/update a few other things that most of you already have.  Listing the steps here in case other Mox novices need them. 

  1) Installed the latest version of Miniconda for Lenox. Downloaded the package "Python 3.8 | Miniconda3 Linux 64-bit" from [here](https://docs.conda.io/en/latest/miniconda.html#installing) using `wget` into my personal programs directory (/gscratch/srlab/lhs3/programs/). Installed Miniconda using directions listed [here](https://conda.io/projects/conda/en/latest/user-guide/install/linux.html). 
  2) Set up new channels using instructions listed [here](https://bioconda.github.io/user/install.html)
```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```
3) Installed `cutadapt` using the conda install directions listed [here](https://cutadapt.readthedocs.io/en/stable/installation.html)
4) While the cutadaptenv was activated, identified the path to the `cutadapt` program on Mox using `whereis cutadapt` so I could specify location in my job script (although not sure if that was necessary).  
5) Added the most current version of FastQC on Mox to my $PATH using 
`export PATH=$PATH:/gscratch/srlab/programs/fastqc_v0.11.9`. This was definitely necessary, since TrimGalore does not have an option to specify FastQC's path.

**Comment by kubu4** [comment]
Thanks for adding your setup guide. That's definitely helpful.

For posterity, I'd also like to add:

> Installed the latest version of Miniconda for Lenox. Downloaded the package "Python 3.8 | Miniconda3 Linux 64-bit" from here using wget into my personal programs directory (/gscratch/srlab/lhs3/programs/).

This works and will work, however, it's not the best for a "long-term" approach to installing/running software on Mox. The primary reason is that login nodes (i.e. the location when you login to Mox) is relatively small, space-wise (it's only 10GB). Programs (especially Anaconda/Miniconda) can/will quickly consume this space and force you to make decisions on which stuff to keep later on down the line. And, to exacerbate things, since Anaconda/Miniconda are actually package managers, it becomes difficult to figure out which packages are the ones consuming the most disk space and which packages require which other packages as dependencies to run properly... So, attempting to remove just a single package to recover some disk space has the potential to break all the others.

I'll give you a guess how I know this. Ugh.

Since we already have both Anaconda and Miniconda installed (`ls /gscratch/srlab/programs/`), you can save a fair amount of space on your login node by using these existing installations to install `conda` packages/environments instead of installing Anaconda/Miniconda and packages on your login node. And, in turn, you wont have to worry (too much) about disk space running out on your login node.

Anyway, as user-friendly as Anaconda/Miniconda are for installing new packages, they are kind of annoying in a shared environment like Mox. As an example of this, did you know we have `MultiQC` installed on Mox? Probably not because it's not listed as a program in `/gscratch/srlab/programs/`. Why not? Because it was installed using Anaconda (but why not Miniconda?? Who knows!). Knowing that, do you now know where `MultiQC` is installed? Again, probably not (it's here: `/gscratch/srlab/programs/anaconda3/bin`). Trying to document this stuff is kinda of a nightmare.

Anyway, this is definitely TMI, but just figured I'd toss it in here in case someone finds this issue in the future....
