### ISSUE TITLE
Suggestions wanted: Improve finding stuff in nightingales

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1058]
Should we add a "tags" column that would have "lab colloquialisms" or something? E.g @yaaminiv was looking for some "Hawaii" samples earlier today. She probably only knew of them as "Hawaii samples", but that info isn't in [nigthingales](https://b.link/nightingales).

If we had a "tags" column, "Hawaii" would be in that column. Also, probably other stuff, like OA, pH, ocean acidification, pCO<sub>2</sub>, etc.

All suggestions welcome!

**Comment by yaaminiv** [comment]
Tags would be really helpful! Since there's a lot of information on the main sheet, I wonder if there could be different tabs for each species or year the samples were sequenced. Took me a while to scroll through and find what I needed (and I didn't actually find the information I needed until my second pass through the spreadsheet)

**Comment by kubu4** [comment]
To address your points, one of the reasons we have these in a Google Sheet is to take advantage of Filters. You can quickly filter by things like species and/or sequencing dates; greatly reduces scrolling.

**Comment by kubu4** [comment]
No additional suggestions.
