### ISSUE TITLE
Get 546 students accounts on owl/gannet

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1069]
Let get folks set up accounts on one of our birds so they can practice remote  next week, and in prep for mox.

**Comment by kubu4** [comment]
Individual accounts or single login with individual directories?

**Comment by sr320** [comment]
What ever you think is best... if they can all use single login at same time, that seems like easiest.

**Comment by kubu4** [comment]
Sorry, just looked at the title of issue and noticed desired server(s);  I was setting this up on Emu.

I'm assuming you're wanting them to be able to use SSH, in order to mimic logging into Mox?

If yes, to set them up with SSH on Owl/Gannet, we have to elevate their user group to "admin". This means they would have _write_ access to almost all of the server. This seems a bit risky to me.

Would Emu be an acceptable alternative?

**Comment by sr320** [comment]
I was thinking more to store large files. and rysync content off mox - to
mox etc.

Not necessarily to run analysis. So whatever you think is best for that is
fine.

**Comment by kubu4** [comment]
Gotcha. Thanks.

**Comment by kubu4** [comment]
Ok, they all have accounts on Gannet (UW Net ID is their username) and personal folders at:

`/volume2/web/fish546_2021/<uw_net_id>`

I've configured permissions so that they have limited access to other parts of the server, so things should be relatively safe. I've done some light testing using a new user account and things seem to work... 

Things will _definitely_ be safe if we only teach them how to use `rsync` and don't explain `ssh` to them.

I'll send you the password via Slack - they all have the same password.
