### ISSUE TITLE
Conversion success! Unsure what Step2 entails

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#107]
Looks like it's working...?
![capture](https://user-images.githubusercontent.com/14934314/32127394-5d15149a-bb2b-11e7-87bd-8747c04a7d38.PNG)

**Comment by grace-ac** [comment]
The .mzML are in Downloads! 
![capture1](https://user-images.githubusercontent.com/14934314/32127421-9a442298-bb2b-11e7-8abe-e21e727e3611.PNG)

**Comment by grace-ac** [comment]
I don't get what [Step 2](https://github.com/RobertsLab/resources/blob/master/protocols/DIA-data-Analyses.md#step-2-prepare-peptide-database) is saying to do. What fasta files? 

I'm experiencing general confusion. 

![capture](https://user-images.githubusercontent.com/14934314/32127791-239a2324-bb2e-11e7-8de0-7aa8be3af8fd.PNG)

**Comment by grace-ac** [comment]
May be easier to wait until we can speak with Jose.?

**Comment by sr320** [comment]
I will also edit protocol such that it makes more sense...

**Comment by sr320** [comment]
use this file (rename from .txt to .fa)
[Cg_Giga_cont_prtc_AA.txt](https://github.com/RobertsLab/resources/files/1451100/Cg_Giga_cont_prtc_AA.txt)

**Comment by grace-ac** [comment]
I am on [Step 2c](https://github.com/RobertsLab/resources/blob/master/protocols/DIA-data-Analyses.md#step-2c-modify-tabular-digested-proteome) and I am having some trouble with the awk thing. 

This is what I have in a jupyter notebook so far:
![capture](https://user-images.githubusercontent.com/14934314/32514643-86790212-c3b2-11e7-8d72-c951f3a9787b.PNG)

I'm wanting to see what the file looks like that was created by the Protein Digestion Simulator is [Step 2b](https://github.com/RobertsLab/resources/blob/master/protocols/DIA-data-Analyses.md#step-2b-run-in-silico-tryptic-digestion-of-reference-proteome-with-quality-standards). Am I using the wrong thing?

The file is in the folder named "grace" on the desktop, so I am pretty positive I'm in the correct directory.

**Comment by sr320** [comment]
Head is not installed on that computer? This is a windows machine...
Just open using windows explorer to look at the file..

**Comment by grace-ac** [comment]
Ah ok, and no, I just installed anaconda - didn't know there were more things to install! I'm guessing that means "awk" won't work until things get installed, either.

**Comment by sr320** [comment]
Lets see what Sam says - seems like if bash is installed this should
work....
Note I was reading about a Linux install available for Windows that might
be new SOP for windows
https://msdn.microsoft.com/en-us/commandline/wsl/install-win10

**Comment by kubu4** [comment]
Use Docker. ;)

I'll formulate real response shortly... (although, Docker is actually an easy solution).

**Comment by kubu4** [comment]
Yes, the problem is because Bash is not installed on that computer (awk, head, tail, etc. are programs included with Bash).

Try following the instructions under the "Setup" section for Windows at this link: https://uwescience.github.io/2017-10-02-uw/

After installing, I'd recommend restarting the computer.

Then, fire up a Jupyter notebook and type the following in a cell and run the cell:

```!which head```

If things are working correctly, the output should be something like (i.e. a path to somewhere):

```/usr/local/bin```

Otherwise, you'll get the same error you got above. Please let me know how this plays out.

**Comment by grace-ac** [comment]
I followed the instructions and also went along with the video tutorial, but the same error came up:
![capture](https://user-images.githubusercontent.com/14934314/32517966-07dde23c-c3bd-11e7-9647-fec731b8da0b.PNG)

**Comment by kubu4** [comment]
I think the actual issue here is the instructions in [2c](https://github.com/RobertsLab/resources/blob/master/protocols/DIA-data-Analyses.md#step-2c-modify-tabular-digested-proteome) are incomplete, right?

Step [2c](https://github.com/RobertsLab/resources/blob/master/protocols/DIA-data-Analyses.md#step-2c-modify-tabular-digested-proteome) needs explicit instructions on how to extract just the two columns needed.

**Comment by sr320** [comment]
Added instructions
