### ISSUE TITLE
Join two files based on "LOC" Number

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1081]
Two files
https://raw.githubusercontent.com/meganewing/OysterGeneAssist/main/data/locusMerge.csv
and
https://raw.githubusercontent.com/meganewing/OysterGeneAssist/main/data/top25marker.csv

example LOC number = `LOC105340423`

(I tried and have doubts there are any matches based on some greps; but of course, I could have fouled it up)

**Comment by kubu4** [comment]
> I tried and have doubts there are any matches

I'm in agreement.

**Comment by laurahspencer** [comment]
Is this a trick question? I joined the tables in R and found one LOC number in common, LOC105340423, which happens to be your example number.  R script attached. 

[join.zip](https://github.com/RobertsLab/resources/files/5885008/join.zip)

**Comment by kubu4** [comment]
Thanks for checking that, @laurahspencer! I didn't bother using R. The bigger issue here is that `locusMerge.csv` is not uniformly formatted, which is going to screw up any programmatic manipulation outside of R. I think that should be fixed:

![image](https://user-images.githubusercontent.com/4514104/106141398-dd08f200-6124-11eb-93f0-fbee36050efa.png)


![image](https://user-images.githubusercontent.com/4514104/106143970-5f46e580-6128-11eb-9ba8-1fe075370c93.png)





And, although it's close, `top25marker.csv` seems to need some fixing as well (but maybe those non-"LOC" gene ids are expected to be there?):

![image](https://user-images.githubusercontent.com/4514104/106141651-4557d380-6125-11eb-86d1-3e314c46a3c1.png)

R is able to properly parse the file, likely because it was produced in R (based on the column headers and field quoting):

![image](https://user-images.githubusercontent.com/4514104/106144635-54408500-6129-11eb-9954-f20750f2cb5f.png)


Notice, R shows only a total of 14 columns, unlike shell tools.

Finally, I don't know what the expectations were (if any) in regards to what the join would produce, but @laurahspencer's results show only a single match between the two files.

**Comment by sr320** [comment]
Thanks! - all should join, so there is some issue will have to go back and revisit.
