### ISSUE TITLE
how do posts in github connect to lab notebook website? 

### ISSUE THREAD

**Issue by ocattau** [RobertsLab/resources#1212]
in my lab notebook(https://ocattau.github.io/), I have a folder called posts and inside the posts I have individual files that are labeled by date 'year_month_day'. How do I connect this folder to upload on my website?

**Comment by kubu4** [comment]
You need to append the filenames with `.md`.

**Comment by kubu4** [comment]
Also, it looks you need to add a header section. Here's an example:

```
---
layout: post
title: CoGe on Fidalgo Sibs
date: '2016-05-05'
categories: Sample-Processing
tags: test
tags: shellfish

---
```

At a minimum, you need the dashes and the layout, title, and date lines. Change title and date to match your own post content. Leave the layout line as is.

**Comment by ocattau** [comment]
okay I have my headers and all files are in .md but nothing is appearing on my website. Here is what my code looks like. 


 ---
layout: post
title: blast locally 
date: '2021-05-12'
categories: blast
tags: test
tags: hemat_transciptome
---

#2021 May 12th 
#today I finished blasting localy using NCIB blast and Jupyter notebooks
!{bldir}blastx \
-query ../oliviacattau/blasts/hemat_transcriptome_v1.5.fasta \
-db ../oliviacattau/blasts/uniprot_sprot_2021_02  \
-out ../oliviacattau/blasts/analysis/hemat_transcriptome-uniprot_blastx.tab \
-evalue 1E-20 \
-num_threads 4 \
-max_target_seqs 1 \
-outfmt 6

**Comment by kubu4** [comment]
I can't too into this ATM, but I see you also have this repo: https://github.com/ocattau/notebook

Should stuff actually be there instead?

**Comment by kubu4** [comment]
I think the setup process got a little out of whack. In your desired repo, it shows this:

![image](https://user-images.githubusercontent.com/4514104/118054792-c1c09c00-b33b-11eb-86e4-c243caecddd8.png)


However, it should show something like this:

![image](https://user-images.githubusercontent.com/4514104/118054823-d866f300-b33b-11eb-9e22-746277f9bafc.png)


Which is what your `notebook` repo shows:

![image](https://user-images.githubusercontent.com/4514104/118054878-f2a0d100-b33b-11eb-9791-c92a1098145d.png)

I guess I'd recommend trying the setup process again to see if you can get things going. Otherwise, try to swing by the beginning of Science Hour and we can help you along in real-time.

**Comment by kubu4** [comment]
This was resolved with correct yaml headers and, per @sr320 , hyphenating filenames (apparently, underscores are not permitted).
