### ISSUE TITLE
Cannot install methyKit on R Server (raven)

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1237]
tried 

```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.12")
```

```{r}
BiocManager::install(c("methylKit"))
```

tail of output

```

ERROR: dependencies ‘GenomicRanges’, ‘GenomeInfoDb’, ‘Rsamtools’, ‘fastseg’, ‘rtracklayer’, ‘Rhtslib’ are not available for package ‘methylKit’
* removing ‘/home/sr320/R/x86_64-pc-linux-gnu-library/4.0/methylKit’
Warning in install.packages(...) :
  installation of package ‘methylKit’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmphEYKTn/downloaded_packages’
Installation path not writeable, unable to update packages: checkpoint, curl, doParallel, iterators,
  jsonlite, MASS, R6, Rcpp, RUnit
```

then started over with 

```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.12")
```

and got

```
Bioconductor version 3.12 (BiocManager 1.30.15), R 4.0.2 (2020-06-22)
Installation path not writeable, unable to update packages: checkpoint, curl, doParallel, iterators,
  jsonlite, MASS, R6, Rcpp, RUnit
```

**Comment by kubu4** [comment]
Dang, it seems like you're unable to install packages, which is annoying. However, those dependencies for methylkit always pop up during an initial install.

I'm out ATM, so can't deal with until later, but one thing to look into is setting a personal R library path. This should allow you to install packages without hassle.

**Comment by sr320** [comment]
set up `/home/sr320/R_libs/` to install libraries locally.  Worked in that installed tidyverse.
However still getting methKit error 

```
ERROR: dependencies ‘Rsamtools’, ‘rtracklayer’, ‘Rhtslib’ are not available for package ‘methylKit’
* removing ‘/home/sr320/R_libs/methylKit’
Warning in install.packages(...) :
  installation of package ‘methylKit’ had non-zero exit status
```

tried to install Rsamtools ...

```
Warning in install.packages :
  package ‘Rsamtools’ is not available (for R version 4.0.2)
```

**Comment by kubu4** [comment]
What command(s) are you using to install those packages? Most of those packages are Bioconductor packages, so you'll need that Bioconductor installation command.

**Comment by kubu4** [comment]
Also, you'll need to install `Rhtslib` before `Rsamtools`.

And, installing `Rsamtools` has been where things keep going wrong. 

I haven't had a chance to install base R (instead of Microsoft Open R) yet, so haven't tested to see if that will fix the issue.

**Comment by sr320** [comment]
latest error


```{r}
BiocManager::install(c("Rhtslib"))
```



```
Error: package or namespace load failed for ‘Rhtslib’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/sr320/R_libs/Rhtslib/libs/Rhtslib.so':
  /home/sr320/R_libs/Rhtslib/libs/Rhtslib.so: undefined symbol: lzma_easy_buffer_encode
Error: loading failed
Execution halted
```

**Comment by kubu4** [comment]
> If you get a chance to just to give me sudo

Sorry! I had added you to the default `adm` group, thinking that meant `administrator` (and, thus, would make you a sudoer). However, it turns out, that `adm` group is solely for viewing log files or something. I've now added you to the `sudo` group, so you should be able to use `sudo` now!

In regards to this:

> /home/sr320/R_libs/Rhtslib/libs/Rhtslib.so: undefined symbol: lzma_easy_buffer_encode

This can be remedied by creating a file in `~/.R/Makevars` with the following info:

`PKG_LIBS+=-llzma`

However, no need to bother, as I'd already done this and was still get stuck on installing `Rsamtools` downstream (I've posted an issue on the Microsoft Open R GitHub repo about the problem).

---

FINALLY, this is all a bit moot (besides the `sudo` part), as I've installed base R, and set raven to use the base R installation instead of the Microsoft Open R install.

I've installed the following with base R in the system library so everyone should have access the next time they start a new session using RStudio Server on raven:

- `tidyverse`
- `methylkit`
- `DESeq2`
- `WGCNA` (this one's for you, @afcoyle )
- `pheatmap`

**Comment by sr320** [comment]
Back at the place where I cannot install methylKit on raven.... based on last comment should it not be present?

**Comment by sr320** [comment]
nevermind - 
this seemed to work

```
```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("methylKit")
```
