### ISSUE TITLE
Mac Mini in FTR 230 dead

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#1239]
At long last the Mac Mini (genefish) is dead (tried turning it on today, was not successful). Not sure if there's interest in replacing it. My workflow involved running things on genefish since I could easily ScreenShare into it, but I may have been the only one using it.

**Comment by kubu4** [comment]
I don't think the computer's dead.

There was a power outage earlier this week and I think that may have tripped something. I say this because I can't access Owl either.

It's possible they were both plugged into the battery backup power unit.

Can you please verify that the battery backup unit is powered on (it's the big black box to the right of the TV)?

**Comment by kubu4** [comment]
Also, it might be easier to do this via Zoom, so I can see things and help direct you more efficiently.

**Comment by kubu4** [comment]
Off-topic, but

> genefish since I could easily ScreenShare

You should be able to easily do this with Ostrich (which is a much more powerful computer), as it is also Mac OS.

**Comment by yaaminiv** [comment]
Mac Mini + (hopefully) Owl should be back online. Turned the power box back on.
