### ISSUE TITLE
qubit RNA HS standards and samples question

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1257]
Lindsay A. has been using the qubit with the RNA HS kit (Jackie's lab will reimburse/replace reagents and tubes used!!!) 

**Weird stuff with standards**
The standard 1 for RNA HS has been reading at ~30 for the last two rounds of qubit-ing she's done. When I have run qubit for RNA HS, standard 1 is typically in the high 70s, mid to high 80s. 

**Weird stuff with samples**
The sample readings have been pretty different as well - she re-ran the same samples twice and the RNA concentrations for some of them were way off -- one sample was ~40 ng/ul the first time she ran it, and now it's ~8ng/ul. 

She vortexes the samples, standards,  and working solutions. 

I read through parts of the qubit manual and it looks like the qubit uses the standards to determine the RNA concentration in the samples...

She says she's had the standards at room temp when she runs them. 

**What could be happening? What should she do?**

**Comment by kubu4** [comment]
There are too many variables involved in order to troubleshoot this. E.g.:

- What's the expiration date(s) on reagents?
- Why did she decide to re-run samples?
- How were samples stored/treated between re-running?
- How is she making the dye solution?
- What sample volume is she measuring (low volumes are more subject to pipetting errors)?
- Is she making sure to change the settings on the Qubit for the sample volume being measured?

At the end of the day, the best approach is probably to have someone in lab to assist/observe...
