### ISSUE TITLE
Determine MDB-Seq protocol to use with Cv samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#126]

**Comment by yaaminiv** [comment]
[Lab Notebook](https://yaaminiv.github.io/Sequencing-Protocol-Thoughts/)

I did some reading (because I really don't know much about the different sequencing methods), and I think Mac's protocol should be fine? The only thing I couldn't find information on were the kits she used, and whether or not there are better alternatives for them. 

@kubu4 do you have any thoughts?
