### ISSUE TITLE
GIS ?

### ISSUE THREAD

**Issue by ChrisMantegna** [RobertsLab/resources#1329]
Hey all!
I'm looking for 'required' skill recommendations for our research neck of the woods and I'm thinking that GIS may be a useful one.  In my mind that is 2nd tier to things like statistics, data science, molecular bio kind of skills when building a course schedule. 

Any suggestions?
Thanks!

**Comment by sr320** [comment]
Would not consider required, the other area missing in the list of prominent areas is physiology.

**Comment by ChrisMantegna** [comment]
For sure - that is a true oversight on my part. I'll def. take another pass at the BIOL course list. 
@afcoyle @ocattau @mattgeorgephd @kubu4 @AHuffmyer -- what courses were most beneficial to you in your early grad school days? Thanks!

**Comment by AHuffmyer** [comment]
Agreed on physiology! Courses that help you learn data skills are particularly useful - R courses, bioinformatics, etc. Courses that cover oceanography/ocean chemistry, energetics, and thermodynamics are great context for climate change work. I wish I could have had the opportunity to take courses that covered respiration/respirometry and performance curves for physiology work! Now that I am in the metabolomics/metabolism world, I wish I also had more biochemistry experience. I also learned a lot from science writing, grant writing, and science policy/scicomm courses. All great areas to consider for courses!

**Comment by afcoyle** [comment]
Definitely agree with Ariana on the importance of data science courses! I've taken a bunch so far, and it's really really helped me have a good grasp on how to structure my research, both on a day-to-day and big-picture level.

Here's a list of all the classes I've taken so far that've been most useful in my research:
- Intro to R (FISH 552/553). Taught by Kristin Privitera-Johnson. I knew a mishmash of R stuff going in, but this was _really_ helpful at building those theoretical foundations. Especially since you need R for basically everything
- Bioinformatics (FISH 546). Taught by @sr320, so really really helpful for getting knowledge needed for research. Not seeing it on the calendar for this winter, but [here's a link to the course wiki](https://github.com/sr320/course-fish546-2021/wiki). And here's a link to the [textbook](https://drive.google.com/file/d/0BwVK83sm6XQGWGNZUmlLckdZU1E/view?resourcekey=0-4XzW5WNx5s_GDgQ97RvqsA), which really is a must-read for bioinformatics stuff.
- Introduction to Environmental Data Science (FISH 497 at the time, but it's getting a new number). Taught by Mark Scheuerell. Not a deep dive into any one topic, but a broad overview of everything - R Markdown, Git/GitHub, tidy data, SQL, and a bunch more. Again, not seeing it offered this winter, but [here's the wiki](https://fish497.github.io/website/index.html).

I also haven't taken any classes with them, but I remember @yaaminiv recommending taking some genome science courses, and I'm thinking about taking GENOME 561 (Molecular Population Genetics And Evolution) this winter!

**Comment by ChrisMantegna** [comment]
@zbengt -sorry I left you out on the first round, but join in the fun :)

Thank you @AHuffmyer and @afcoyle! Super helpful suggestions. 
@afcoyle - take 561, I had my eye on it as well.

**Comment by mattgeorgephd** [comment]
A few courses in the Biology department worth keeping an eye out for:

BIOL 421 Ecological and Evolutionary Physiology of Animals
BIOL 423 Marine Ecological Processes
BIOL 560 Seminar in Ecology - Friday morning at 9:30. Don't have to sign up for credit to attend.

**Comment by zbengt** [comment]
Thank you all for these suggestions!

@ChrisMantegna If you're interested in GIS, I've heard a couple grad students recommend marine GIS in oceanography or the equivalent (non-marine focused) class in geography. But I think the best way to engage with GIS is to learn what the tools look like and then tinker around with them yourself from there. A lot of more computationally focused GIS happens using R, Python, and JavaScript, so you probably wouldn't have too much trouble applying any data science skills you learn to GIS. I can suggest some free training resources if you're interested!

**Comment by ChrisMantegna** [comment]
Thank you @mattgeorgephd -awesome suggestions. @zbengt - I will take you up on the training/ resource stuff. It's the perfect way to check it out.

**Comment by yaaminiv** [comment]
popping in for a timely course recommendation: the ENGAGE class! over the course of winter quarter you practice science communication skills, culminating in a public talk at town hall seattle in the spring. definitely one of my favorite classes i took!

applications are out and due by 11/19: https://catalyst.uw.edu/catalyst/chooser/cf14fdf812d4d6c35527442826e5d7d3

**Comment by ChrisMantegna** [comment]
Thank you, thank you all! Tons of valuable info in here :)
