### ISSUE TITLE
Clean up code repo

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1358]
as many things have been incorporated into handbook, it would be good to clean up
https://github.com/RobertsLab/code

That is, delete stale pages that are captured in handbook.

**Comment by kubu4** [comment]
Do you have any examples, or something that caught your eye? Off-hand, I don't feel like there's any real overlap in The Handbook and the `code` repo.  The Handbook is fairly limited in the amount/type of code examples/guides.

**Comment by sr320** [comment]
this caught my eye https://github.com/RobertsLab/code/blob/master/blast.md

**Comment by kubu4** [comment]
Ah! Well, definitely agree on getting rid of that, since it's empty. Definitely no need. Of course, there is no BLAST tutorial in The Handbook. This, then, gets into where should some of this end up? Does it make more sense to copy most of the code examples/.ipynbs to some location in The Handbook? Or, do we expect people to also remember that we have a dedicated `code` repo for that kind of stuff?

**Comment by sr320** [comment]
Bigger thing is folks should be going to handbook to look for code. Where it lives is not as much of issue as there will be links in handbook.

**Comment by kubu4** [comment]
Yeah, that's part of what I was getting at. There's nothing currently in The Handbook that directs people to the `code` repo.

**Comment by sr320** [comment]
except pages like https://robertslab.github.io/resources/bio-Annotation/
:)

**Comment by kubu4** [comment]
True, but it's not obvious that we have an _entire repo_ which contains helpful code.
