### ISSUE TITLE
Add tagseq data to nightingales

### ISSUE THREAD

**Issue by mattgeorgephd** [RobertsLab/resources#1405]
Tagseq data from the NOPP-gigas-ploidy-temp project

Here is the link to the files on gannet:

https://gannet.fish.washington.edu/panopea/NOPP-gigas-ploidy-temp/022022-tagseq/

Here is the github repo:

https://github.com/mattgeorgephd/NOPP-gigas-ploidy-temp

**Comment by kubu4** [comment]
Thanks! 

Alrighty, I've `rsync'd` data to https://owl.fish.washington.edu/nightingales/C_gigas. When you have a chance, please add all pertinent info to [nightingales spreadsheet](https://docs.google.com/spreadsheets/d/1_XqIOPVHSBVGscnjzDSWUeRL7HUHXfaHxVzec-I-8Xk/edit?usp=sharing) (I recently sent you edit access).

Since this is single-end sequencing data, please create a single row for each FastQ file.

If you have any questions, please feel free to hit me up (Slack or new GitHub issue).
