### ISSUE TITLE
Extract RNA from Salmon samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1410]

**Comment by sr320** [comment]
It would be good to get these extracted in April. 
@kubu4 can you tackle the brains, and 
@mattgeorgephd can you take the other 3 tissues?

We can have Delaney provide support (tube labelling etc)

**Comment by sr320** [comment]
https://github.com/RobertsLab/resources/issues/1307

**Comment by kubu4** [comment]
Brain samples are done. Here's summary table:

They're stored in [Sam's RNA Box #3](https://docs.google.com/spreadsheets/d/1j9jm3b91IkVfG0EsSjQpR--t2R97YXEQPaOFqsOqjhc/edit?usp=sharing).

| Sample | Concentration (ng/uL) | Elution Volume (uL) | Yield (ng) |
|--------|-----------------------|---------------------|------------|
| 6A     | 116                   | 15                  | 1740       |
| 7A     | 132                   | 15                  | 1980       |
| 8A     | 120                   | 15                  | 1800       |
| 9A     | 130                   | 15                  | 1950       |
| 10A    | 94                    | 15                  | 1410       |
| 11A    | 114                   | 15                  | 1710       |
| 12A    | 80                    | 15                  | 1200       |
| 13A    | 80.8                  | 15                  | 1212       |
| 14A    | 74.6                  | 15                  | 1119       |
| 15A    | 108                   | 15                  | 1620       |
| 17A    | 138                   | 15                  | 2070       |
| 18A    | 89                    | 15                  | 1335       |
| 19A    | 67.6                  | 15                  | 1014       |
| 21A    | 61.6                  | 15                  | 924        |
| 22A    | 108                   | 15                  | 1620       |
| 24A    | 83.8                  | 15                  | 1257       |
| 26A    | 98.8                  | 15                  | 1482       |
| 27A    | 110                   | 15                  | 1650       |
| 28A    | 118                   | 15                  | 1770       |
| 29A    | 124                   | 15                  | 1860       |
| 30A    | 102                   | 15                  | 1530       |

**Comment by mattgeorgephd** [comment]
> @mattgeorgephd can you take the other 3 tissues?

I'll work on these next week.

**Comment by kubu4** [comment]
- RNAzol RT
- Direct-zol RNA Microprep Kit (ZymoResearch), with DNase step

**Comment by mattgeorgephd** [comment]
>

**Comment by mattgeorgephd** [comment]
> 

c

**Comment by kubu4** [comment]
I think that's correct.

**Comment by mattgeorgephd** [comment]
@sr320 

Received word from the UT Austin sequencing facility regarding the salmon samples. They ran a random selection of samples through their bioanalyzer for a quick QC and forwarded me the [results](https://www.dropbox.com/s/kabh8zfsyz442om/QB22201_Eukaryote_Total_RNA_Nano_DE34903795_2022-05-25_13-16-53.pdf?dl=0).

Looking at the RIN and curves:
1. 3/5 brain didn't pass QC.
2. 1/4 liver didn't pass QC
3. 0/2 gonad didn't pass QC

Options going forward:
1. Stick with the original plan and sequence all samples at $75 a pop (omitting ones that failed as mentioned above)
2. Run bioanalyzer on the remaining samples at $20 a sample, then sequence the ones that pass at $75 a pop

Let me know what you'd like to do

**Comment by sr320** [comment]
@mattgeorgephd @kubu4 did y'all run bioanalyzer? 

@mattgeorgephd what did your QC look like for your tag-see?

**Comment by kubu4** [comment]
> did y'all run bioanalyzer

No

**Comment by kubu4** [comment]
@mattgeorgephd - Out of curiosity, how do you know which samples are which on those electropherograms?

And, what are their criteria to identify samples that "fail" QC?

**Comment by mattgeorgephd** [comment]
@sr320 I ran the bioanalyzer on 3-5 samples from each extraction date for the liver and gonad samples to look for consistency. All had two peaks with an RIN above 7.

@kubu4 The GSAF recommends RINs above ~6 for Tag-seq. They said they can compensate for/clean up alcohol contamination (extended tails on the second peak). The well positions are listed above the graphs. Here is a key:

Brain: A1, E1, B2, D2, C3
Liver: D4, E5, F6, G7
Gonad: H8, D11

A third option is to run the bioanalyzer on all of the extra RNA we have in the freezer (most, but not all had extra) and let them know which to run.

**Comment by sr320** [comment]
Is it possible samples degraded in transit?

**Comment by kubu4** [comment]
@mattgeorgephd - It looks like there are two sets of graphs that are both labelled `A1`, with drastically different scores. I'm I lookin at those correctly?

This gets back to the issue of the impact of whether or not RNA degradation (and, what degree of degradation) has any actual impact on sequencing data. Even if RNA is degraded, if (for example), one was only going to sequence 50bp, then I feel like RNA would have to be _severely_ degraded in order to prevent one from getting usable sequence data.

So, with that in mind, does RNA degradation even matter for sequencing like this? I mean, there's always going to be some level of degradation, even in samples with a RIN of 10. So, we have to decide what level is acceptable/unacceptable...

**Comment by mattgeorgephd** [comment]
@sr320 There are samples with an RIN of around 10, so degradation due to shipping seems unlikely. The box I sent was oversized for the application just in case it got caught up, which it didn't.

@kubu4 Good catch, it looks like they ran A1 twice. One graph looks flat, so maybe they didn't load enough in one well of the bioanalyzer chip?

re: quality required for Tag-seq - there isn't much in the literature to go off of, and it looks like most references are copy/pasting the quality recommendations for RNA-seq. The argument about Tag-seq being less sensitive to degradation makes sense to me. I just wanted to get your guys feedback before I gave the go ahead, especially given that Sam had mentioned that he had encountered difficulties with the brain extractions.
