### ISSUE TITLE
Issue with notebook backups

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1420]
https://gannet.fish.washington.edu/github_backups/notebooks/

**Comment by kubu4** [comment]
What's the concern here?

All files are present (e.g. Aidan's notebook):

![image](https://user-images.githubusercontent.com/4514104/156669347-36c16e40-883a-4522-8521-8daa330f6992.png)

If you want to peruse files via that URL (e.g. https://gannet.fish.washington.edu/github_backups/notebooks/afcoyle.github.io/), you won't be able to because each notebook contains an `index.html` file which web browsers automatically try to load. So, browsing the notebook backups via URL results in a weird render of the notebooks, using the `index.html` file instead of displaying an index of all the files in the actual directory.

I can look into disabling this, if you'd like. Not sure how it can be done, but I'm fairly confident a solution exists somewhere.

**Comment by sr320** [comment]
Yep related to link in handbook that does not really provide anything  eg https://d.pr/i/ORWl9O

Probably best to provide path on gannet instead of url

**Comment by kubu4** [comment]
I've made the notebook directories browsable via URL. You may have to refresh the page if you still see the attempted rendered version.

I did this by adding a `.htaccess` file to `github_backups/notebooks/` with the following content:

```
# Ignore index.html to avoid attempt to render
# Ensures displaying index of directory when visited via URL
DirectoryIndex index-of.html
```

This tells the server that it should look for a directory index file called `index-of.html`. If this file is _not_ found, then the index of the directory contents is displayed instead. So, this effectively ignores the `index.html` and won't try to render the web page described in `index.html`.
