### ISSUE TITLE
Can't run multiqc on Raven

### ISSUE THREAD

**Issue by mattgeorgephd** [RobertsLab/resources#1491]
Fastqc works just fine by calling: 

```/home/shared/FastQC/fastqc```

I fond the multiqc folder:

```/home/shared/MultiQC.v1.12.dev0/multiqc```

Reviewed the [handbook](https://multiqc.info/docs/#running-multiqc), but don't have the permissions to attempt install

**Comment by kubu4** [comment]
Yeah, MultiQC is tricky. I still haven't ever figured out how to get an install set for all users on a single computer.

You'll need to activate Anaconda and then follow the install instructions for Conda install:

https://github.com/ewels/MultiQC#installation

Let me know if you need help with the Anaconda portion of things.

**Comment by mattgeorgephd** [comment]
Solution:

```
eval "$(/opt/anaconda/anaconda3/bin/conda shell.bash hook)"
conda activate
which multiqc
multiqc --help
```

**Comment by kubu4** [comment]
Turns out, I've managed to get MultiQC installed for anyone needing it on Raven.

Installation was challenging, but ended up requiring to be installed via `pip` instead of the `conda install -c bioconda multiqc` command.

So, all users should now be able to utilize MultiQC using the instructions @mattgeorgephd posted [above](https://github.com/RobertsLab/resources/issues/1491#issuecomment-1199762604).
