### ISSUE TITLE
Should I have a GitHub Repo/Notebook?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#152]
Would it be best if I transitioned to GitHub for my notebook ?

While doing this, I could maybe help with the [issue in Onboarding](https://github.com/RobertsLab/onboarding/issues/1) of creating a guide for setting up a GitHub Notebook...

**Comment by kubu4** [comment]
I'll chime in here.

I think it's personal preference, however, I do think it would be better to switch to a notebook that's dedicated solely to your work. My reasoning is that it makes it much easier to search through older content. 

And, on that note, searching through the GitHub notebooks is nearly impossible (if it's possible, could someone please provide some info - I'd like to be able to do this). The WordPress-based notebooks that @jldimond and I use (onsnetwork.org) allows for this. 

However, @jldimond isn't the biggest fan of the notebooks and has legitimate complaints about using onsnetwork.org (e.g. loading times!). Another strike against using onsnetwork.org notebooks is that backups aren't terribly easy to initiate and require access to the WordPress database (which we don't have) for a full, proper backup of the site.

Both formats recognize markdown. This allows for easier composition of posts in a markdown editor/viewer so you can see real-time previews of what your post formatting will end up looking like. Write your post in a markdown editor/viewer and then copy/paste into your notebook entry.

**Comment by grace-ac** [comment]
Thanks for those thoughts, @kubu4 ! I think I will likely use GitHub as it is more familiar to me than onsnetwork is, and it sounds like it'll be a more reliable backup option. 

According to Yaamini, at first glance, GitHub doesn't appear to have a searchable option. There are some potential searchable options with tags and categories, but she currently doesn't have the time to delve into it.

**Comment by sr320** [comment]
I will help you set it up..
I need to write a step by step guide.
Search is actually easy- just search the repo...

**Comment by kubu4** [comment]
> Search is actually easy- just search the repo...

Hmmm, this doesn't work for me. For example, searching [Yaamini's notebook repo](https://github.com/yaaminiv/yaaminiv.github.io) for "dnr" only produces [a single search result](https://github.com/yaaminiv/yaaminiv.github.io/search?q=dnr&type=Issues&utf8=%E2%9C%93).

But, she has posts that use "dnr" in the [body of the post](https://github.com/yaaminiv/yaaminiv.github.io/blob/master/_posts/2016-12-02-December-Goals.md) and she even has [markdown files with "dnr" in the filename](https://github.com/yaaminiv/yaaminiv.github.io/blob/master/_posts/2016-10-05-DNR-Project-Introduction.md). Neither of those instances show up when I search for "dnr" or "DNR".

Additionally, it's not easy to figure out how to get to the repo in order to initiate a search if you're not a GitHub user.

**Comment by jldimond** [comment]
Yes, not always crazy about onsnetwork mainly because it seems slow to refresh and publish. But otherwise I think it's a good option. You can easily backup by periodically downloading an .xml file.

**Comment by grace-ac** [comment]
Link to the how-to screen recording of setting up a GitHub notebook: http://owl.fish.washington.edu/scaphapoda/grace/Github-noteboook.mov

**Comment by kubu4** [comment]
Good vid! I highly recommend installing a clipboard manager on your Mac. It will greatly improve your copying and pasting life!
