### ISSUE TITLE
issues merging data with technical replicates 

### ISSUE THREAD

**Issue by ocattau** [RobertsLab/resources#1556]
If I want to combine two datasets A and B where A is my CS data and B is my protein data, I would merge by Oyster Label (ex. R51). But merge doesn't like it when you have multiple data points with the same name as it multiples the data frame by 3 (instead of 3 technical replicates I have 9). I could rename everything as R51a and R51b ex.... but I would prefer not to. Is there another filter or merge command that can do this type of thing?

```{r}
new_df <- merge(A, B, by=Label, all=FALSE) #produces data frame x3 the size 
```

**Comment by sr320** [comment]
there is _join_, but I would need to see the data to best offer solution.

**Comment by ocattau** [comment]
Okay it looks like semi_join() will work but the order of the datasets matter 
```{r}
new_df<-semi_join(A, B, by='Label') # data frame of size A
new_df<-semi_join(B, A, by='Label') # data frame of size B
```

**Comment by ocattau** [comment]
Looks like semi-join() doesn't work after all. Here is my code
```{r}
P<-read.csv("https://github.com/ocattau/CS-manuscript/blob/main/raw-data/Protein_all.csv") #198 obs
CS<-read.csv("https://github.com/ocattau/CS-manuscript/blob/main/raw-data/Absorbance_all.csv") #204 obs
new_df <- merge(CS, P, by='Label', all=FALSE) #produces data frame x3 the size 
new_df<-semi-join(CS, P, by='Label') #does not list any data from P 
```

**Comment by sr320** [comment]
Url

**Comment by kubu4** [comment]
Is that a private repo, by chance?

**Comment by ocattau** [comment]
I just made it public

**Comment by kubu4** [comment]
Those file URLs link to GitHub page with the CSV. They do not link directly to each of the CSVs...

**Comment by ocattau** [comment]
Sorry about that, should be fixed now
```{r}
P<-read.csv("https://raw.githubusercontent.com/ocattau/CS-manuscript/main/raw-data/Protein_all.csv") #198 obs
CS<-read.csv("https://raw.githubusercontent.com/ocattau/CS-manuscript/main/raw-data/Absorbance_all.csv") #204 obs
new_df <- merge(CS, P, by='Label', all=FALSE) #produces data frame x3 the size 
new_df<-semi_join(CS, P, by='Label') #does not list any data from P 
```

**Comment by kubu4** [comment]
Okay, I found the correct URLs and looked at the data.

>  Is there another filter or merge command that can do this type of thing?

The answer, unfortunately, is no. 

The reason is that the computer can't (i.e. will not) make the decision of which row should be joined with which row, when there are duplicates of the join value.

For example, how does the computer know which of the three `R46` in `Protein_all.csv` match the appropriate `R46` in `Absorbance_all.csv`? There's nothing telling the computer how to make that decision, so it won't make the decision for the user.

With that said, what's the end goal here? Why do you want to merge these?

**Comment by ocattau** [comment]
I need to join the protein data with the CS data so that I can calculate the final CS and protein values, it is from two assays so they have separate CSVs

**Comment by kubu4** [comment]
Would you be able to provide an example of what you want the final table to look like?

**Comment by sr320** [comment]
Honestly its probably worth going over step by step -as many early steps concern me.. (eg the way samples are labelled).

**Comment by ocattau** [comment]
Like this [https://raw.githubusercontent.com/ocattau/CS-manuscript/main/raw-data/Absorbance_ideal_table.csv](https://github.com/ocattau/CS-manuscript/blob/main/raw-data/Absorbance_ideal_table.csv)

But without the repeating values (you see the first value is repeated 9 times instead of 3) 

This is my entire code but it is a bit of a mess https://github.com/ocattau/CS-manuscript/blob/main/code/CS%20script%20samples%201-72.Rmd

**Comment by ocattau** [comment]
Okay I think I know what's happening, I have three technical replicates for the CS data, I have three technical replicates for the BSA protein data so therefore I actually have nine technical replicates ie three times three equals nine.

**Comment by sr320** [comment]
> Honestly its probably worth going over step by step -as many early steps concern me.. (eg the way samples are labelled).

again at some point soon we need to go over code step by step (and/or better commenting) before you spend too much more time on

**Comment by kubu4** [comment]
>  we need to go over code step by step

Science Hour tomorrow would be the perfect time to do this! See you there?

**Comment by AHuffmyer** [comment]
I'm joining this thread a little late - but my general thought is that you cannot join a data frame with technical replicates from two different processes. This is because your row needs to be the level of one observation. And it is not possible for a technical replicate from the CS assay to be from the same "observation" as a replicate from the protein assay. It would only be appropriate to merge these data frames if you summarize replicates to the level of the true biological replicate/oyster ID. If you want to plot these on the same plot you would need to have them in two separate data frames and overlay or facet the plots to visualize. Happy to try to help!
