### ISSUE TITLE
Making Google team drive pics public

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#157]
Is there a way we can make the photos at 
https://drive.google.com/drive/u/0/folders/0ALfztRtnsFHXUk9PVA

public? I am trying to share with SeaGrant,

Maybe @grace-ac has to do it because she set it up.

**Comment by grace-ac** [comment]
This is what it looks like when I try to share:
![screen shot 2018-01-17 at 10 42 01 am](https://user-images.githubusercontent.com/14934314/35060381-2dd9756c-fb73-11e7-8334-c8cabe80e268.png)

You might be able to share since you were the one in the team that put the images in the folder?

https://gsuite.google.com/learning-center/products/drive/get-started-team-drive/ 
Section 4 talks about sharing capabilities in Team Drive.

**Comment by kubu4** [comment]
Alternative is to put this on UW Google Drive account. Not as convenient, but would allow folder sharing.

**Comment by sr320** [comment]
Yep thanks..
