### ISSUE TITLE
Install CPC2 and CPAT on raven

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1630]
CPC2 http://cpc2.gao-lab.org/download.php

CPAT https://cpat.readthedocs.io/en/latest/#installation

**Comment by Sdssourcing** [comment]
#

**Comment by kubu4** [comment]
Both programs are installed.

CPC2 is here: `/home/shared/CPC2_standalone-1.0.1/bin/CPC2.py`

CPAT is accessible by calling `cpat.py` from anywhere.

NOTE: In order to run either or these programs, the user will need to use the system-wide Anaconda install!

Here are the steps to check which Anaconda is currently being used and how to switch to the system-wide install:

1. Figure out which Anaconda installation is being used:

    `which conda`

    If the output does _NOT_ return the following, you'll need to switch:

    `/opt/anaconda/anaconda3/bin/conda`

2. Switch to system-wide Anaconda:

- Deactivate current Anaconda environment:

   -  `conda deactivate`

- Load system-wide Anaconda environment:

  - `eval "$(/opt/anaconda/anaconda3/bin/conda shell.bash hook)"`

3. Confirm system-wide Anaconda environment is loaded:

    `which conda`

    should return:

    `/opt/anaconda/anaconda3/bin/conda`

Let me know if this does/not work!
