### ISSUE TITLE
Get PDF data into Excel

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1631]
Take this PDF of excel file and get into excel - https://d.pr/f/fz4vkI

there should be some conversion tools or ability to take photo and convert to excel

**Comment by sr320** [comment]
then..

Column 1 - Species
Column 2 - Site #
Column 3 - Algae or Invertebrate
Column 4,5,6 - High Med low (with value letters)
Column 7 notes.

**Comment by DoroLar** [comment]
Hey Professor. I apologize for taking so long! I have reorganized the data from the PDF into this excel sheet. 

[Re-organized data (PDF into Excel).xlsx](https://github.com/RobertsLab/resources/files/11435855/Re-organized.data.PDF.into.Excel.xlsx)

**Comment by sr320** [comment]
@ChrisMantegna seems correct?

**Comment by ChrisMantegna** [comment]
That looks lovely! Thank you @DoroLar  and @sr320 . I would add a readme sheet in front of that one that lists the key to the abundance categories _and_ then if there is time/ nothing else pressing going on, I would separate the species names into Family, Species, and Genus since not all names have all three it would help with ID and comparison down the road.
