### ISSUE TITLE
Difference between read.table() and read.csv()

### ISSUE THREAD

**Issue by ocattau** [RobertsLab/resources#1633]
How come this code below produces 7,737 rows
```{r}
goslims<-read.table(file="https://raw.githubusercontent.com/RobertsLab/code/master/r_projects/sam/20230328-pgen-gene_annotation-update/outputs/02-goslim-mapping/20230329-pgen-annotations-SwissProt-GO-BP_GOslim.tab", header=TRUE, sep = '\t', fill=TRUE)
```
while this code below produces 14,672 rows 
```{r}
goslims<-read.csv(file="https://raw.githubusercontent.com/RobertsLab/code/master/r_projects/sam/20230328-pgen-gene_annotation-update/outputs/02-goslim-mapping/20230329-pgen-annotations-SwissProt-GO-BP_GOslim.tab", header=TRUE, sep = '\t', fill=TRUE)
```
What is the correct way to read in tab files?

**Comment by mattgeorgephd** [comment]
I have had more luck with read.delim for tab data using the sep="\t" argument

**Comment by kubu4** [comment]
Matt's suggestion is probably best.

But, if you're choosing between `read.csv()` and `read.table()`, you definitely want to use `read.csv()`.

The reason for this is that `read.table()` uses the first five lines of a file to try to quickly determine the file's layout/organization (specifically, determine the maximum number of columns in the file). Once it scans the first five lines and makes a guess at the file layout, it uses that info to decide if it should keep rows (rows which have the "expected" number of columns) or discard the rows which deviate from the "expected" file layout.

Looking at that file, there are many fields which are empty. Those fields are likely not counted as columns (despite the fact that there is a header for each column...), which means that those rows are discarded because they do not have the "expected" number of columns. And, looking at the help option for `read.table()`, it seems like the use of `fill = TRUE` somehow confounds/contributes to this?

And, to add to the confusion, supposedly `read.csv()` behaves the same as `read.table()`, but simply has a different set of default options. However, I'd argue that's not the case based on this issue.

**Comment by kubu4** [comment]
Also, this is a _great_ example of why you should never blindly trust the computer!

How/why did you discover the difference between the two functions?

**Comment by ocattau** [comment]
Steven was skeptical that I only had 7,000 GOslims and he ran the code on his computer and got 14,000 so that's how we figured it out. It ended up producing mostly the same results except it had put ~10 GOslims in the GOterm category. Thanks for the help!
