### ISSUE TITLE
borrow dewar for liquid N for summer at marrowstone?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1667]
Hi all!

Hoping to borrow a dewar for liquid nitrogen for the summer at marrowstone for sea star work. 

Is there an extra we can use? 

Also, if yes, where would I get liquid N?

**Comment by kubu4** [comment]
Unfortunately, I can't speak to the other questions. But, for this one
 
 > Also, if yes, where would I get liquid N?

Liquid nitrogen is available in the Chemistry Stores in Bagley Hall (basement). You'll need to register a budget number via online form:

https://chem.washington.edu/research-stockroom

Also, as a heads up, there's usually no available parking (but, since it's summer you could get lucky...), so you'll definitely want a cart to transport the dewar.

Two more things:

1. If you haven't taken (and passed!) the LN2 training, you need to do so:

https://www.ehs.washington.edu/training/liquid-nitrogen-safety

2. Transporting LN2 inside an enclosed personal vehicle is not allowed, per Washington Dept. of Transportation law(s).

**Comment by sr320** [comment]
We have a dewar that you could use but the LN would eventually evaporate (~several of weeks??) and might not be practical to fill back up at UW - but you could use. 

The other option if you have a -80 onsite is alcohol bath with dry ice - which might be easier to access at your location.

What is the time frame where you will need capacity to snap freeze samples?

**Comment by grace-ac** [comment]
Ah, ok... that might not be super feasible for us out here, then.

The alcohol bath and dry ice seems like a good option! Though, it sounds like there isn't a source of dry ice out here. Would that be something I could get from UW and drive to Marrowstone? Or does it also require a non-personal vehicle.

**Comment by grace-ac** [comment]
we are hoping to flash freeze our inoculum that we use for experiments... with our first experiment hopefully starting between tomorrow and next Mon/Tues... can't start until we have an active sick star as our source of disease

**Comment by sr320** [comment]
for freezing inoculum.... I would simply place directly in -80 freezer. Can hold / transport on wet ice. 

end goal for inoculum is? ie what do you plan to do with it

**Comment by grace-ac** [comment]
ok!

the post-doc is the one who will be working with the inoculum - her part of the project is to look for pathogen. she was thinking flash freezing before going into -80 was ideal, but since we do have -80, we can just put it straight into that
