### ISSUE TITLE
Install Iso-seq on mox

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1671]
for dealing with Mussel PacBio data

https://github.com/PacificBiosciences/IsoSeq/blob/master/isoseq-clustering.md

**Comment by kubu4** [comment]
Alrighty, it's installed. It's an Anaconda package, so the environment will have to be activated in order to use it:

`conda activate isoseq_env`

Not sure if anyone else has access. Please let me know if you can access or not.

To use in a SLURM script, you'll need the following lines to activate a conda environment:

```bash
# Load Anaconda
# Unknown why this is needed, but Anaconda will not run if this line is not included.
. "/gscratch/srlab/programs/anaconda3/etc/profile.d/conda.sh"

# Activate the IsoSeq Anaconda environment
conda activate conda activate isoseq_env
```
