### ISSUE TITLE
Does someone know how to fix this code?

### ISSUE THREAD

**Issue by Noahk22** [RobertsLab/resources#1722]
I'm trying to create a multiline graph where each individual (Microchip_ID) is plotted along the three SL data points recorded while the individuals were growing in their temperature treatments. I also wanted to color code the lines by their treatment. 

Here is my code: date_levels <- c("SL_12212022", "SL_12272022", "SL_mm")
temp.dataa2$Date <- factor(temp.dataa2$Date, levels = date_levels)

ggplot(temp.dataa2, aes(x = Date, y = Value, color = Temperature, group = Microchip_ID)) +
  geom_line() +
  geom_point() +
  labs(x = "Date", y = "Value", color = "Temperature") +
  theme_minimal() +
  theme(legend.position = "top") +
  scale_color_manual(values = c("Low" = "blue", "Medium" = "green", "High" = "red"))

Here is the dataset: 
[temp-experiment-size-3.csv](https://github.com/RobertsLab/resources/files/12834364/temp-experiment-size-3.csv)

**Comment by mattgeorgephd** [comment]
It looks like the issue is how you structured your data in the csv file prior to import. You need a column called Date in your dataset that has a corresponding Microchip_ID and Temperature. You can then factor the 'Date' column. Here is a link to the csv file formatted correctly: 
[temp-experiment-size-3-reformat.csv](https://github.com/RobertsLab/resources/files/12834796/temp-experiment-size-3-reformat.csv)



Once that is taken care of, you can plot them all together like this:

```
temp.dataa2 <- read.csv("R datasets/temp-experiment-size-3-reformat.csv")

date_levels <- c("SL_11212022", "SL_12272022", "SL_mm")
temp.dataa2$Date <- factor(temp.dataa2$Date, levels = date_levels, ordered=TRUE)
temp.dataa2$Temperature <- factor(temp.dataa2$Temperature, levels = c("0","5","9","16"))

# overlayed figure
p1 <- ggplot(temp.dataa2, aes(x = Date, y = value, color = Temperature, group = Microchip_ID)) +
             geom_line() +
             geom_point() +
             labs(x = "Date", y = "Value", color = "Temperature") +
             theme_minimal() +
             theme(legend.position = "top") + 
             scale_color_manual(values = c("darkblue","royalblue1","orangered1","darkred"))

p1
```

The resulting figure looks like this:

![image](https://github.com/RobertsLab/resources/assets/70529576/79c52762-b2c6-4698-be14-d4fa11120d35)

This looks a bit messy, so if you'd like to look at each temperature individually, try something like this:

```
# facet wrapped figure
p2 <- ggplot(temp.dataa2, aes(x = Date, y = value, color = Temperature, group = Microchip_ID)) +
             geom_line() +
             geom_point() +
             labs(x = "Date", y = "Value", color = "Temperature") +
             # theme_minimal() +
             theme(legend.position = "top") + 
             scale_color_manual(values = c("darkblue","royalblue1","orangered1","darkred")) + facet_wrap(~ Temperature)

p2
```
![image](https://github.com/RobertsLab/resources/assets/70529576/910f76cf-33de-4c7d-b53b-fa773c69918c)

Given the variability in these data, I you might want to summarize your results with boxplots instead of lines, but it is up to you:

```
# overlayed figure; boxplot
p3 <- ggplot(temp.dataa2, aes(x = Date, y = value, color = Temperature)) +
             geom_boxplot() +
             labs(x = "Date", y = "Value", color = "Temperature") +
             theme_minimal() +
             theme(legend.position = "top") + 
             scale_color_manual(values = c("darkblue","royalblue1","orangered1","darkred"))

p3

# facet wrapped figure; boxplot
p4 <- ggplot(temp.dataa2, aes(x = Date, y = value, color = Temperature)) +
             geom_boxplot() +
             labs(x = "Date", y = "Value", color = "Temperature") +
             # theme_minimal() +
             theme(legend.position = "top") + 
             scale_color_manual(values = c("darkblue","royalblue1","orangered1","darkred")) + facet_wrap(~ Temperature)

p4
```
![image](https://github.com/RobertsLab/resources/assets/70529576/e8f5ded5-1c0c-4958-a7fa-d38ad87220ca)

![image](https://github.com/RobertsLab/resources/assets/70529576/56d27eb4-74c8-4543-953a-b7b31ad22518)

**Comment by Noahk22** [comment]
Thank you so much Matt! This was super helpful!!!
