### ISSUE TITLE
gitignore by file size

### ISSUE THREAD

**Issue by meganewing** [RobertsLab/resources#1750]
Is there a way to add a line to a .gitignore file to automatically ignore any files over a certain size? ? / if not, how do you specify which files to ignore? I've just been manually unselecting them during the commit process, but surely that's not the best way.

**Comment by kubu4** [comment]
From the command line:

`find ./* -size +100M | cat >> .gitignore`

Run that command from the top directory of your repo. 

It will search for all files >100MB and add them to the top-level `.gitignore` file. You'll have to re-run it periodically to pick up on new files, though. Also, it's likely to create a lot of duplicated lines in the `.gitignore` file, since every time it runs, it'll still find the same big files and add them...

**Comment by meganewing** [comment]
thank you!
