### ISSUE TITLE
 Rebudget: BIVALVE REPRO CONTROL

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1777]
see email for details

**Comment by kubu4** [comment]
Having looked through this and attempting to access things via Workday, here's what I've surmised:

- Supplies/Materials have exceeded budget amount by ~$19,000

It seems like this might be relatively straightforward to figure out (i.e. review individual transactions), but I don't have access to the transaction history for the budget.

In your email you mentioned remember some transactions being categorized as "unallocated." Reviewing the emails, this was resolved and was due to an error in the transfer process from Ariba to Workday (a known issue).

So, I think the easiest thing to do is just review the transactions for the budget, confirm their accuracy, and then go from there.

**Comment by kubu4** [comment]
Also, from looking through the purchasing log, ~78% of the Supplies/Materials budget was used to purchase the 10X Genomics kits for single cell sequencing at the very beginning of the grant. So, it's definitely over budget, but the purchasing log doesn't reflect it being over budget by ~$19,000...

**Comment by sr320** [comment]
What category is severely underspent?

**Comment by kubu4** [comment]
Salary and Wages has a remaining budget of ~$24,000 (only $8000 has been spent).
