### ISSUE TITLE
Identify samples for Cod methylation sequencing

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1785]
Per @sr320 - please identify possible samples for cod methylation sequencing.

**Comment by shedurkin** [comment]
I already have a subset of the RNAseq samples selected for methylation work, compiled in the same sheets document, [here](https://docs.google.com/spreadsheets/d/19CqqS3wOhmG7drw163v7evUylRWwOjBOdvuR-y0RqF0/edit#gid=155247170). Blood samples are included though, since we hadn't been told at the time that blood samples are harder to process -- is it safe to assume that blood also can't be processed for methylation work?

**Comment by sr320** [comment]
@shedurkin revisit / revise the list to make sure we have no samples with corresponding poor RIN or no RNA for RNAseq job to increase chance of getting matches.

**Comment by shedurkin** [comment]
Revised the same sheets document to include only samples with sufficient RNA quantity and RIN >6. Will we be able to extract blood samples, or should those also be replaced?

**Comment by sr320** [comment]
lets leave in blood

**Comment by shedurkin** [comment]
I ensured the methylation sample list does not include the missing sample 92 or the two samples exluced from DEG work due to wonky RNASeq fastqc profiles (129, 149). The finalized list of samples to send for methylation is [here](https://docs.google.com/spreadsheets/d/19CqqS3wOhmG7drw163v7evUylRWwOjBOdvuR-y0RqF0/edit#gid=155247170)

**Comment by laurahspencer** [comment]
@shedurkin one pertinent note- we ran genetic analyses on all samples last year and samples 1, 2, and 121 were discarded from analysis as they were outliers in the PCA.  If you have the option, I would stay away from samples 1 and 2 at least, since I suspect that there _could_ have been some contamination during sampling. Here are some slides with more info. on those genetic analyses: https://docs.google.com/presentation/d/12mD339i0r6ZE3wHYpKmfN3aaSBnRGi_JyS1IyMG6bO4/edit?usp=sharing

**Comment by laurahspencer** [comment]
Also- to capture the most variation in growth and genetic composition I recommend selecting samples that are spread out along both axes of this figure, which shows the genetic PC1 along the x-axis, and residuals from a growth~temperature linear model along the y-axis. 

![image](https://github.com/RobertsLab/resources/assets/17264765/577b146a-995f-448b-acb6-a6c9e0a4a1d9)

Here is a link to an interactive version of this figure; download the file to your local computer, then double click to open in a browser and you will be able to zoom in, select temperatures to show, etc. https://github.com/laurahspencer/pcod-juveniles-2023/blob/main/lcWGS/analysis-20230922/pca/pca_growth-resids.html

**Comment by shedurkin** [comment]
Just wanted to double check that we're including blood samples for methylation, now that we've decided not to do the extractions in-house? 
(per #1764, Azenta handles blood and tissue differently for RNA extraction, possibly same issue with DNA extraction?)

**Comment by kubu4** [comment]
Sequencing not happening at Azenta.

Regardless, the issue before was that we had not indicated that there would be blood samples when we got the initial quote. They'll handle blood, but it just costs a different amount to process. Since we already had a quote and a PO, it would've been a major annoyance to try to update all of that.

**Comment by sr320** [comment]
No blood

**Comment by sr320** [comment]
Sorry - misunderstood- will do what’s on quote

**Comment by kubu4** [comment]
Are these samples ready to go? 

I finally received a PO number on Tuesday, but the quote expires on Sunday... 

I've already requested an extension on the quote, but have not heard back yet. If they'll accommodate the extension request, we'll need to send these out on Monday or Tuesday next week.

**Comment by sr320** [comment]
@laurahspencer and @shedurkin are we satisfied with the current set?

**Comment by kubu4** [comment]
Alrighty, they've extended the quote! 

Currently awaiting sample submission instructions.

**Comment by kubu4** [comment]
Sample submission sheet is here:

[(Form) Psomagen_NGS_Order_Sheet_2024.xlsx](https://github.com/RobertsLab/resources/files/15044310/Form.Psomagen_NGS_Order_Sheet_2024.xlsx)


Please fill out and upload completed form in this issue.

**Comment by shedurkin** [comment]
I believe Laura is running one last analysis before finalizing the methylation sample list. She wants to see whether our RNAseq'd samples contain multiple haplotypes of ZP3 (a gene of interest that may play a role in cold adaptation)

**Comment by shedurkin** [comment]
@kubu4 did we ever get the four unextracted blood samples (57 B, 58 B, 19 B, 20 B) back from Azenta? These are the blood samples that we originally sent for RNA extraction and sequencing, but which we ended up replacing (#1764).

**Comment by kubu4** [comment]
No. Samples aren't generally returned...

**Comment by laurahspencer** [comment]
Not getting this done today. Going to chat with Ingrid on Monday to see what she thinks about including just one haplotype (the most common, "T.A.T"), or including two. I'm leaning towards two, since there seems to be some growth differences in the cold treatments. Here is a violin plot showing the residuals from a growth~temperature model (growth=change in fish length), plotted by temperature and haplotype (2 most common haplotypes only). The left haplotype (T.A.T) is likely fish from the eastern Bering Sea / Aleutian Islands / western Gulf of Alaska. The right haplotype, which is heterozygous at all three loci that we have data for (T/G, A/G, T/A), could be one of several designations that spawn further south. So, the two haplotypes could represent fish that are adapted to different environments. One issue, though, is that these haplotypes were pulled from RNASeq data! So, our confidence and ability to pick up rarer alleles depends on depth, AND depth is way higher in the cold treatment. I think that's why we don't have many heterozygotes (right haplotype) showing up in the 16degC treatment. We do have lcWGS data for these fish, so I'll check with Ingrid to see if we can leverage that data, too. 

What's the new deadline? :bowtie:

![image](https://github.com/RobertsLab/resources/assets/17264765/86b421d6-cbae-4835-917b-f4934e0a4ae2)

**Comment by kubu4** [comment]
Looks like they updated it to June 21!

**Comment by laurahspencer** [comment]
False alarm- error in plotting :(  What I thought was growth differences are in fact just different scales. DARN!

**Comment by sr320** [comment]
@laurahspencer so does this mean we can submit this week?

**Comment by laurahspencer** [comment]
Okay! I updated the list of methylation samples. In addition to Kathleen's requirements (RNA quality, exclude outliers, equal representation across tank, growth distribution, and genetic PC1 axis), I made sure we had representation across the distribution of a rough estimate of hepato-somatic index (liver weight/final weight), and predominantly selected the "T.A.T" haplotype at exonic variants in the ZP3 gene, but did include 2 or 3 rarer haplotypes per treatment. FYI, to identify haplotype, I pulled them from both the lcWGS data and RNASeq data. Here are plots showing the samples that are selected (circles) for methylation analysis compared to all RNA samples (sample numbers), with the x-axes being genetic PC1 scores, and the top figure showing the hepato-somatic index on the y-axis, and the bottom figure showing growth~temperature residuals on the y-axis.

![image](https://github.com/RobertsLab/resources/assets/17264765/44aaa702-46a3-4ed5-a8f8-90c27504bcda)

![image](https://github.com/RobertsLab/resources/assets/17264765/f73ec5a0-01ef-489e-9704-2762f16bee74)

**Comment by sr320** [comment]
@kubu4 can you tentatively get these shipped out next week?  
Maybe aligning with day you can connect with Eric on qpcr analysis?

**Comment by kubu4** [comment]
I'll plan on shipping them out on Tuesday.

@shedurkin - Please complete the sample sheet (linked in a comment above) and compile samples into a dedicated box.

**Comment by shedurkin** [comment]
> I'll plan on shipping them out on Tuesday.
> 
> @shedurkin - Please complete the sample sheet (linked in a comment above) and compile samples into a dedicated box.

How much tissue is required? Since we've already subsampled all of these samples for RNAseq, will DNA extraction require all remaining tissue?

**Comment by kubu4** [comment]
Good question. Does the sample submission sheet provide any info?

**Comment by shedurkin** [comment]
I see instructions for frozen tissue suggesting 10-30mg for DNA extraction. I'll weigh some of the samples to get a sense of how much tissue we have left. I'm guessing we want to reserve some if possible?

**Comment by sr320** [comment]
@kubu4 

Sorry I might have missed the quote

Are they spiking with lambda phage?

**Comment by sr320** [comment]
@shedurkin for blood

Pick matches with liver samples, 2 from each treatment

**Comment by sr320** [comment]
@laurahspencer feel free to weigh in on gill and blood picks - just getting basic idea if patterns vary from liver.

**Comment by sr320** [comment]
> Offhand, don't know. I'll check and report back. 
> 
> 
> 
> Do we want spike-in? 

I think that is necessary to measure conversion efficiency - unless they say otherwise

**Comment by sr320** [comment]
> I've always assumed (possibly a bad idea...) 

Lets not assume
We have a few sets without spikes so we do not know effeciency

**Comment by kubu4** [comment]
Yep, I've already sent an email for more info.

**Comment by shedurkin** [comment]
> Edited the list so that blood and gill samples are also liver samples selected for methylation sequencing

Unfortunately two of these are still blood samples that we basically lost to Azenta (current blood selection is **57B**, 59B, 18B, **20B**, samples lost to Azenta are **57B**, 58B, 19B, **20B**). 57B and 20B are also the two blood samples which you have marked as being rare haplotypes, so I'm guessing we want to replace them with other similar samples. It looks like the best options would be **replacing 57B with 40B** (only other methylation sample with a rare haplotype from treatment 0C) and **replacing 20B with 3B** (only other methylation sample with a rare haplotype from treatment 16C). 
Since I'm guessing we also want to be able to perform cross-tissue comprisons between the blood and gill tissues, that would also mean switching the gill samples to come from the same individuals. Would those changes make sense with the haplotype data @laurahspencer ?

**Comment by shedurkin** [comment]
> @shedurkin for blood
> 
> Pick matches with liver samples, 2 from each treatment

Our quote is for 4 blood samples, so the current selection is two samples from the 0C treatment and two samples from the 16C treatment (the extremes)

**Comment by laurahspencer** [comment]
>Since I'm guessing we also want to be able to perform cross-tissue comprisons between the blood and gill tissues, that would also mean switching the gill samples to come from the same individuals. Would those changes make sense with the haplotype data @laurahspencer ?

@shedurkin Yes, I agree it makes sense to select gill/blood samples to match liver samples. 

In terms of haplotype, if we're hoping to do any type of cross-tissue analysis, let's just choose all samples from fish with the same common ZP3 haplotype (GTATATGCT). **So, replace gill/blood sample 20 with either 4 or 12, and replace gill/blood sample 57 with either 50 or 70.**

**Comment by kubu4** [comment]
Just a reminder that I'm planning on being in lab tomorrow to ship these.

Please post the completed sample sheet in a reply in this Issue..

Also, please let me know where I can find the box of samples to ship.

I need to have the shipment to the front desk by 11AM.

**Comment by shedurkin** [comment]
Replaced 57B/57G with 50B/50G, and replaced 20B/20G with 12B/12G. Compiled all samples in box labelled "P.cod samples for methylation” with the date (04/25/2024) and my initials (KMD) in the middle -80 freezer in FTR. I filled the "Sample ID", "Species", and "Sample Status" columns of the order sheet (linked below), but I'm not sure which other sections need to be filled
[Pcod_methylation_Psomagen_NGS_Order_Sheet_2024.xlsx](https://github.com/RobertsLab/resources/files/15154803/Pcod_methylation_Psomagen_NGS_Order_Sheet_2024.xlsx)

Relevant lab notebook posts:
[Liver subsampling](https://shedurkin.github.io/Roberts-LabNotebook/posts/projects/pacific_cod/2024_04_25_methylation_subsampling.html)
[Blood and gill subsampling](https://shedurkin.github.io/Roberts-LabNotebook/posts/projects/pacific_cod/2024_04_29_methylation_subsampling.html)

**Comment by kubu4** [comment]
Samples shipped today.
