### ISSUE TITLE
pOverA settings for mRNA WGCNA

### ISSUE THREAD

**Issue by zbengt** [RobertsLab/resources#1796]
I am doing mRNA WGCNA runs for CEABiGR oyster RNA-seq data. I have the pipeline all set from my [lncRNA runs](https://github.com/zbengt/oyster-lnc/blob/main/code/12-WGCNA-lncRNA.Rmd), but I'm not sure what settings to use for pOverA for filtering data. [Ariana's previous WGCNA code](https://github.com/zbengt/oyster-lnc/blob/main/code/12-WGCNA-lncRNA.Rmd) did this:
"Specifying the minimum count for a proportion of samples for each gene. Here, we are using a pOverA of 0.07. This is because we have 38 samples with a minimum of n=3 samples per lifestage. Therefore, we will accept genes that are present in 3/38 = 0.07 of the samples because we expect different expression by life stage. We are further setting the minimum count of genes to 10, such that 7% of the samples must have a gene count of >10 in order for the gene to remain in the data set."

We are just looking at treatment with this data. Different WGCNA runs will be done for each sex. Since I have 10 males and 16 females, with treatment and control groups, it seems the only experimentally relevant option is making the proportion of samples for each gene based on the number of individuals in each group:
Males 4 Control and 6 Treatment (going with the smaller proportion for Control) --> 4/10 --> 0.4
Females 8 Control and 8 Treatment --> 8/16 --> 0.5

And making the minimum count 10.

But wouldn't that filter out too many genes? Don't we want to cast a much wider net to compare with lncRNA modules? Since the sample size is so small, I think it would make sense to make the proportion 1 out of each sex group (Males - 1/10 - 0.1; Females - 1/16 - 0.062).

**Comment by AHuffmyer** [comment]
I recommend running with the lower threshold because you are going to be interested in individual variation in this analysis. You can set it to counts of 10 and proportion of 0.05 (such that 5% of samples need to have a lncRNA count of >10 for that lncRNA to remain in the analysis). 

I also recommend running mini experiments on this data. Try running it at thresholds that are of interest to you. How many genes made it through each threshold? Is there a big difference between them? How does it change the results? This will help you understand how the pOverA affects your data. If you only want to look at lncRNA's that are present in all samples, that is when you would increase your threshold.

**Comment by zbengt** [comment]
For lncRNAs I've made the settings pretty loose so that they are at least one individual and a minimum of 5 counts. I was wondering if there is a standard way to do this filtering for mRNA runs with coding sequences. But this makes sense! We'll discuss further when we meet at 3. Thank you!

**Comment by zbengt** [comment]
Determined working settings that are experimentally relevant. View lab notebook post here:
https://zbengt.github.io/2024-02-14-05-CEABiGR_WGCNA_settings_lncRNA_male/
