### ISSUE TITLE
Plot oyster growth data

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1805]
If it helps I have uploaded at https://github.com/RobertsLab/project-gigas-carryover/blob/main/lifestage_carryover/data/size/gigas-lengths.csv

**Comment by Eric-Ess** [comment]
Do you think you could upload a more current version? [https://docs.google.com/spreadsheets/d/1FzmBKACmgf4Mt0i75l_yDv3RfTQeKKnRuQ78ClAINCE/edit#gid=0](https://docs.google.com/spreadsheets/d/1FzmBKACmgf4Mt0i75l_yDv3RfTQeKKnRuQ78ClAINCE/edit#gid=0)

**Comment by sr320** [comment]
@AHuffmyer there really needs to be some reformatting before similar to what I did... (or at least it would be easier)

**Comment by AHuffmyer** [comment]
Looks good - I'll do that and upload later today

**Comment by Eric-Ess** [comment]
Actually scratch that, I don't think it matters. Should be fine. Thanks

**Comment by AHuffmyer** [comment]
Looks like all data is in the gigas-lengths.csv now on GitHub. I'll write a script now to do some plotting.

**Comment by Eric-Ess** [comment]
No need, already working on that. Though feel free to suggest edits once I make the notebook post

**Comment by AHuffmyer** [comment]
Great! Looking forward to seeing it!

**Comment by AHuffmyer** [comment]
It would also be great to visualize mortality. You could count the number of columns with "dead" in the notes column and divide that by the total number of animals to get percent mortality. I remember the juvenile class had high mortality in the treatment condition.

**Comment by Eric-Ess** [comment]
notebook post: https://eric-ess.github.io/plotting-growth/  just did a quick fraction for mortality since only juveniles died and only from the jan 31 date (as far as i know). Let me know if i should make any edits, I'm still very new to R

**Comment by sr320** [comment]
plot life stages separtately

**Comment by sr320** [comment]
and plot replicates separately (or denote with color etc)

**Comment by AHuffmyer** [comment]
I also played around with plots using [this script](https://github.com/RobertsLab/project-gigas-carryover/blob/main/lifestage_carryover/scripts/growth_AH.Rmd). 

Significant effects of lifestage and month, no effect of treatment. 

```
model<-aov(length~lifestage*month*treatment, data=growth)
summary(model)

                            Df Sum Sq Mean Sq  F value Pr(>F)    
lifestage                    3 383973  127991 1377.056 <2e-16 ***
month                        2   9529    4765   51.264 <2e-16 ***
treatment                    1    157     157    1.686  0.194    
lifestage:month              3  15429    5143   55.335 <2e-16 ***
lifestage:treatment          3    510     170    1.830  0.140    
month:treatment              2     15       8    0.081  0.922    
lifestage:month:treatment    3     26       9    0.094  0.963    
Residuals                 1006  93503      93                    

```

![mean_lengths](https://github.com/RobertsLab/resources/assets/32178010/a563f50b-d139-452f-b22c-697bef94fb28)

![mean_lengths_box](https://github.com/RobertsLab/resources/assets/32178010/8c58964a-976f-4853-9dfa-086e9b3d31f7)

**Comment by sr320** [comment]
very cool... though I imagine we have some replicate / family bias likely sampling the two biggest adult families in November

**Comment by AHuffmyer** [comment]
Yes definitely! We should next summarise by replicate and calculate the percent change for each and plot those values. Some of the response to treatment (if any) would likely be masked here by looking at all replicates together.

**Comment by AHuffmyer** [comment]
Here are the results by replicate. Note the huge change in scale of total growth between seed/spat and juvenile/adult! There are some very interesting family-specific responses to treatment where some families are strongly affected but others aren't. However, because we do not have individual replicates of each family and did not track individual oyster in each bag, we cannot perform statistics on family effects. 

![adults_Nov_percent_growth](https://github.com/RobertsLab/resources/assets/32178010/a744caa5-a2e5-487b-834f-bcf23ab81e37)

No significant effect of treatment on adults in November.  
```
model<-replicates%>%
  select(treatment, lifestage, tag, perc_growth_Nov)%>%
  drop_na()%>%
  droplevels()%>%
  
  aov(perc_growth_Nov~treatment, data=.)

summary(model)

            Df Sum Sq Mean Sq F value Pr(>F)  
treatment    1  8.358   8.358   4.132 0.0883 .
Residuals    6 12.137   2.023 
```

![adults_Jan_percent_growth](https://github.com/RobertsLab/resources/assets/32178010/e0bcbc2f-04a2-480b-952b-6df99343a8be)
![juvenile_Jan_percent_growth](https://github.com/RobertsLab/resources/assets/32178010/094bda8f-9cab-482d-ac88-3f519f57b237)
![seed_Jan_percent_growth](https://github.com/RobertsLab/resources/assets/32178010/44d2efcb-0397-4a6d-b43b-d15e4c2cafa6)
![spat_Jan_percent_growth](https://github.com/RobertsLab/resources/assets/32178010/2d8ba85d-2562-4d67-97f7-404ef050deeb)

No effect of treatment on growth to January, but significant effect of life stage. 

```
model<-replicates%>%
  select(treatment, lifestage, tag, perc_growth_Jan)%>%
  drop_na()%>%
  droplevels()%>%
  
  aov(perc_growth_Jan~treatment*lifestage, data=.)

summary(model)

                    Df Sum Sq Mean Sq F value   Pr(>F)    
treatment            1      1       1   0.015    0.904    
lifestage            3  96056   32019 325.275 3.54e-13 ***
treatment:lifestage  3    363     121   1.231    0.335    
Residuals           14   1378      98 

```

**Comment by AHuffmyer** [comment]
Notebook post with above analyses: https://ahuffmyer.github.io/ASH_Putnam_Lab_Notebook/Oyster-Lifestage-Carryover-Growth-Analysis/
