### ISSUE TITLE
Cod WGBS liver DNA quality/integrity is bad

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1894]
DNA isolations have been completed, but _all_ the liver samples appear to have extremely degraded gDNA - average ~100bp.

They've requested additional tissue to attempt additional isolations. Admittedly, I'm not sure this will make a difference.

Blood samples look decent. A couple of the gill samples look decent.

I've attached the QC report here. Scroll down in the report to view TapeStation histograms.

[Original_Sample_QC_AN00019129_ANW240502S006Q001.pdf](https://github.com/RobertsLab/resources/files/15266292/Original_Sample_QC_AN00019129_ANW240502S006Q001.pdf)

Ideas on how to proceed?

**Comment by sr320** [comment]
One option would be selecting different tissue.

**Comment by laurahspencer** [comment]
Bummer. 
If we can't look at methylation in liver tissue, we should probably reconsider the purpose/broader questions we can answer with methylation sequencing. 

One option: Ben is super interested in temperature biomarkers. Ultimately he wants to know what temperatures juveniles were exposed to during rearing. This [2022 paper](https://doi.org/10.1111/1755-0998.13725), for example, suggests that this might be possible using methylation analysis. The experimental design from this project isn't perfect for his question, since our fish were only exposed as juveniles, not larvae, and samples were collected directly out of the experimental temperatures rather than after returning to a common temperature. But, it could be a good start.

For methylation biomarker identification, we could do either blood or fin clips, both which could be collected non-invasively from future fish, and identify regions or genes with methylation patterns that respond to temperature. Fin clips would be better for collecting in the field, are often collected for genetics, and could have the added benefit of being leveraged by a future methylation aging project :eyes:  I'd need to check with Ingrid to see if we still have fin clip tissue or DNA from those, which we used for lcWGS.

Another option (if possible)- Ben now has reproductive mature Pacific cod in his hatchery (not the case last year), so he has more access to gametes/embryos. He is running experiments on them now, and he is seeing cool impacts of light on hatch timing and buoyancy. We could check with him and see whether he could pull samples from that study for sequencing.  I wouldn't have any issue redirecting the methylation funds, since we already have so much data from that juvenile study (fish metrics, HSI, liver lipids, liver gene expression, lcWGS from fins).

**Comment by sr320** [comment]
Let's move forward with @kubu4 extracting liver DNA to see if it's ok. (Subset) - then we re-assses path fwd.

Btw 

Integrated co-pilot response:

Based on the information you've provided, it appears you're dealing with issues of DNA isolation and degradation from liver samples. Here are a few suggestions on how to proceed:

1. **Re-isolation from additional tissue**: If additional tissue is available, it might be worth trying to isolate DNA again. However, you've mentioned uncertainty about this approach. It's important to ensure that the initial degradation wasn't due to the isolation process itself.

2. **Optimize DNA isolation protocol for liver samples**: It's possible that the DNA isolation protocol may need tweaking when it comes to liver samples. You may need to use a different method or adjust the current protocol to better preserve the DNA.

3. **Use other sample types**: Given that the DNA from blood and some gill samples appears to be in better condition, you might consider focusing on these sample types if they can provide the information you need.

4. **Consult with a subject matter expert**: You might want to consult with a molecular biologist or a genomics expert. They might be able to provide further insights or suggest alternative approaches.

5. **Discuss with your team or project stakeholders**: Understanding the implications of using degraded DNA or switching to a different sample type for your project is essential. You might need to discuss this with your team or project stakeholders.

Please note that these are general suggestions. The best course of action would depend on the specifics of your project and the resources available to you.

**Comment by kubu4** [comment]
If someone can set aside a subset of tissues and let me know where they are, I'll get some DNA isolated next week.

**Comment by laurahspencer** [comment]
After you get an idea of DNA quality in those liver samples it's probably worth it to meet and chat about the broader questions we'll want to address with the next round of sequencing.

**Comment by sr320** [comment]
@shedurkin can you please id 4 samples that have never been touched and 4 samples that we went out for DNA methylation.

**Comment by shedurkin** [comment]
> @shedurkin can you please id 4 samples that have never been touched and 4 samples that we went out for DNA methylation.

Untouched liver samples (never sent for RNA or DNA extraction), one from each treatment:
6, 42, 95, 122

Liver samples that were sent for DNA extraction for which we still have tissue, one from each treatment:
12, 39, 79, 118


It's worth noting that most of the liver tissue samples that had already been sent for RNAseq had little tissue remaining.  About half of the samples selected for methylation analysis had barely enough (~10mg), so there's no additional tissue to send to Azenta. (Details in [notebook post](https://shedurkin.github.io/Roberts-LabNotebook/posts/projects/pacific_cod/2024_04_25_methylation_subsampling.html))

**Comment by kubu4** [comment]
Could you also please let me know where I can find these eight samples? Thanks.

**Comment by shedurkin** [comment]
They're in the left -80 freezer in FTR, rack 13, and the individual boxes are labelled with sample numbers. They're probably all in different boxes though :(

**Comment by kubu4** [comment]
Thanks!

**Comment by kubu4** [comment]
Supplies have been ordered.

I'd expect to begin working on this early next week. I'll keep this issue updated as I progress.

**Comment by kubu4** [comment]
I'll get notebook post up soon, but here's gel. Confirms what Psomagen is seeing on their end (118 didn't have any tissue in the tube, btw):

![PXL_20240531_210357784~2](https://github.com/RobertsLab/resources/assets/4514104/52d64c58-031b-41b3-a3b9-9bcd193c7198)

**Comment by sr320** [comment]
So thawed ones are compromised and fresh ones are ok?

**Comment by kubu4** [comment]
Looks that way...
