### ISSUE TITLE
Extract DNA from cod blood samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1922]

**Comment by laurahspencer** [comment]
It looks like there is also some leftover gDNA from **fin clips** in the freezer at NOAA, which was used for lcWGS.

**Comment by sr320** [comment]
@laurahspencer can you select blood samples that make sense based on treatment / RNA-seq - 8 coldest 8 warmest?

**Comment by laurahspencer** [comment]
Yes, I'll do so tomorrow. I'll also be at SAFS tomorrow, bringing fin clip tissue and/or DNA over from NOAA.

**Comment by sr320** [comment]
@laurahspencer can you get a list of samples for extraction?

**Comment by laurahspencer** [comment]
Here I list 20 samples total - five each of blood and fin tissues from 0C and 16C. Blood samples are frozen, fin clips are in ethanol in the flammables hood. For fin clips, if there's sufficient tissue it'd be great to use only a portion of it for this sequencing effort.  

Steven, in terms of funding, how many total samples can we do? If are you intending this to be a preliminary sequencing run, then we'd go back and do more depending on what we see I can pare back the list to fewer samples. If I were to choose a tissue to focus on, it would be fin clips since they are much easier to collect from fish. There could be issues with blood samples since we simply flash froze them, whereas other folks typically add anticoagulants and/or centrifuge them. 

Also - we plan to throw a few jaw bone samples in there (currently in the process of getting them from folks at Newport), and a few sleeper shark fin and/or muscle samples will arrive in the mail in the next week or so, which we'll also need to process for methylation analysis similar to these samples. 

| Tube Label | Sample # | Tank | Temp Treatment | Tissue Type |
|:----------:|:--------:|:----:|:--------------:|:-----------:|
|    39 B    |    39    |  12  |        0       |    Blood    |
|    47 B    |    47    |  11  |        0       |    Blood    |
|    50 B    |    50    |  11  |        0       |    Blood    |
|    59 B    |    59    |  10  |        0       |    Blood    |
|    70 B    |    70    |   9  |        0       |    Blood    |
|     4 B    |     4    |   1  |       16       |    Blood    |
|    11 B    |    11    |   2  |       16       |    Blood    |
|    12 B    |    12    |   2  |       16       |    Blood    |
|    18 B    |    18    |   3  |       16       |    Blood    |
|    30 B    |    30    |   4  |       16       |    Blood    |
|    39 F    |    39    |  12  |        0       |  Caudal Fin |
|    47 F    |    47    |  11  |        0       |  Caudal Fin |
|    50 F    |    50    |  11  |        0       |  Caudal Fin |
|    59 F    |    59    |  10  |        0       |  Caudal Fin |
|    70 F    |    70    |   9  |        0       |  Caudal Fin |
|     4 F    |     4    |   1  |       16       |  Caudal Fin |
|    11 F    |    11    |   2  |       16       |  Caudal Fin |
|    12 F    |    12    |   2  |       16       |  Caudal Fin |
|    18 F    |    18    |   3  |       16       |  Caudal Fin |
|    30 F    |    30    |   4  |       16       |  Caudal Fin |

To document why we're doing this- the idea is to look for temperature biomarkers in the epigenome, i.e. informative CpG sites for which methylation predicts temperature treatment. Blood and fin clips are good candidate tissues for biomarker development for this since they are non-invasive. The future aim would be to see if methylation levels at biomarker sites persist after the fish return to common temperatures. Here are a couple related studies- [one in zebrafish](https://onlinelibrary.wiley.com/doi/full/10.1111/1755-0998.13725) that looked at this in gonad tissue (and also identified sex biomarkers), and one that used blood from [chickens](https://journals.biologists.com/jeb/article/220/19/3579/18782/DNA-methylation-profiles-in-red-blood-cells-of).

**Comment by sr320** [comment]
@kubu4 can you proceed with these extraction

**Comment by kubu4** [comment]
Are there any blood samples I can use for testing extractions? Need to get an idea of what volumes to use, if they're pellet-able, and whether or not I should try to pellet them before extraction.

Also, @laurahspencer, where can I find the blood samples? I feel like you told me, but, if you did, I don't remember.

**Comment by laurahspencer** [comment]
@shedurkin can you point Sam to where the frozen cod blood samples are stored? 

Here's 8 samples you can use for testing. I'm sure you'll find that samples have varying amounts of blood.  Can you let me know which ones you actually use?  Thank you!

- 5 B
- 123 B
- 76 B
- 85 B
- 14 B
- 133 B
- 65 B
- 95 B

**Comment by laurahspencer** [comment]
Quick follow-up, which kit/method do you plan to use for extractions? Will you use the same method for blood as you will for fin clips?  

I ask, because we'll also need to extract DNA from a few of these fish's jawbones preserved in ethanol, and need to identify the DNA extraction method for jawbones to coordinate with a collaborator.  @kubu4 and @sr320 any thoughts on the DNA extraction method for jawbone?

**Comment by kubu4** [comment]
I was planning on using Quick-DNA Miniprep Kit (ZymoResearch) for any/all DNA isolations, but need to test out with blood a bit before I plow through all the samples.

Is jawbone cartilage or actual bone?

If bone, I'd probably just pulverize under LN<sub>2</sub> and then proceed with kit.

**Comment by laurahspencer** [comment]
Jawbones will be actual ossified bone from juvenile fish that are ~100m long, so kinda small bones.  Jawbones will be preserved in ethanol at room temp to match the fin clip collection method. Since that's the case I wouldn't think I'd need to grind in liquid nitrogen, but correct me if I'm wrong! 

I see on the [Zymo website](https://www.zymoresearch.com/products/quick-dna-miniprep) that that kit is for "Whole blood (fresh or stored), buffy coat, buccal cells, cells from culture, saliva, and other biological liquid samples," but it sounds like you've gotten good quality yields from solid pieces of tissue? Have you ever used it on fin clips?

**Comment by kubu4** [comment]
Yes, you can use it for tissue, as well. I used it to isolate high quality DNA from cod liver tissues from this project.

No, I've never isolated DNA from fin clips, as we are a _shellfish_ lab. :wink: 

Regarding the jawbone, I figured it might be too tough to homogenize with plastic mortar/pestle tubes - that's why I figured it'd need to be pulverized under LN<sub>2</sub>.

**Comment by shedurkin** [comment]
> @shedurkin can you point Sam to where the frozen cod blood samples are stored?

They're stored in the same boxes as the cod liver/gill/spleen samples (left -80 freezer in FTR, rack 13, and the individual boxes are labelled with sample numbers)

**Comment by kubu4** [comment]
> Here's 8 samples you can use for testing. I'm sure you'll find that samples have varying amounts of blood. Can you let me know which ones you actually use?

- `5B`
- `14B`
- `65B`
- `76B`

https://robertslab.github.io/sams-notebook/posts/2024/2024-07-18-DNA-Isolation-Quantification-and-Integrity-Assessment---Pacific-Cod-Blood-Samples-Test/

**Comment by kubu4** [comment]
Alrighty, I isolated DNA from the blood samples.

https://robertslab.github.io/sams-notebook/posts/2024/2024-07-18-DNA-Isolation-and-Quantification---Pacific-Cod-Blood/

@laurahspencer  and @shedurkin - The following blood samples were _not_ located in the freezer boxes:

- `12B`
- `18B`
- `50B`
- `59B`

How would you like to deal with these missing samples (e.g. select four more samples to isolate)?

**Comment by sr320** [comment]
If this is just a test - 4 is fine to make decisions.

**Comment by sr320** [comment]
In other words if @kubu4 is happy let’s move forward with 20 @laura
selected.

**Comment by kubu4** [comment]
I did the test and that went well.

Moved forward using the list of 10 blood samples that @laurahspencer had [selected](https://github.com/RobertsLab/resources/issues/1922#issuecomment-2189879056).

However, of those 10, only there were only six found in the freezer.

**Comment by sr320** [comment]
Thanks for the clarification-

To circle back and refresh my memory - we are looking for 8 from coldest, 8
from warmest that align with our RNA-seq data
https://github.com/RobertsLab/resources/issues/1922#issuecomment-2174251880

**Comment by shedurkin** [comment]
> @laurahspencer and @shedurkin - The following blood samples were _not_ located in the freezer boxes:
> 
> * `12B`
> * `18B`
> * `50B`
> * `59B`

Sorry I didn't catch this in Laura's original list of 20 samples, but these are the four blood samples already sent to Azenta for WGBS (see [here ](https://github.com/RobertsLab/resources/issues/1785#issuecomment-2083710521) for linked order sheet and notebook posts detailing the full set of samples already sent)

**Comment by laurahspencer** [comment]
Awesome that you were able to get high quality DNA from those blood samples @kubu4!  But I can't believe I missed that @shedurkin had already used those blood samples.  

With the blood samples Sam processed, we have 3 from each temperature, although DNA concentrations look good for only 2 each (see below table).  I'll pick more blood samples for extraction. Seems like we're getting a ~65-75% success rate in terms of yield, so I'll pick several more.  I do think fin clips are preferable in terms of biomarker development,. We also just received a handful of sleeper shark tissues. So, lots more extractions we can do before sending things off for sequencing. @kubu4 are you planning another lab day soon? If so, I can come help you with these! Or I can certainly do them myself if you have other things on your plate.

| Tube Label | Sample # | Tank | Temp Treatment | Tissue Type | DNA concentration (pg/uL) |
|:----------:|:--------:|:----:|:--------------:|:-----------:|:-----------:|
|    39 B    |    39    |  12  |        0       |    Blood    |    506    |
|    47 B    |    47    |  11  |        0       |    Blood    |    3.3    |
|    70 B    |    70    |   9  |        0       |    Blood    |    830    |
|     4 B    |     4    |   1  |       16       |    Blood    |    9.36    |
|    11 B    |    11    |   2  |       16       |    Blood    |    212    |
|    30 B    |    30    |   4  |       16       |    Blood    |    1100    |

**Comment by laurahspencer** [comment]
Our new plan is to extract both dna & rna from cod blood, moving to new issue #1951
