### ISSUE TITLE
 Can I mkdir /gscratch/srlab/stanja to run some .sh jobs on Mox?

### ISSUE THREAD

**Issue by sarahtanja** [RobertsLab/resources#1979]
Is it ok for me to add a stanja directory to the /gscratch/srlab/ folder for running .sh scripts? 

Currently reviewing the [Mox Guides](https://robertslab.github.io/resources/mox_Adding-a-User/#:~:text=Bioinformatic%20Workflows-,New%20User,-The%20first%20step) in the handbook and I already have access to Mox and can login successfully.

**Comment by sarahtanja** [comment]
Just saw the [previous issue](https://github.com/RobertsLab/resources/issues/1977) about Klone... which (Mox vs. Klone) would you suggest for me to run RNA-seq analysis .sh scripts on at the moment?

**Comment by kubu4** [comment]
> Is it ok for me to add a stanja directory to the /gscratch/srlab/ folder for running .sh scripts?

Yes. Please be sure to run all jobs so that outputs from your jobs end up in `/gscratch/scrubbed/stanja` (you may need to create that directory.

> RNA-seq analysis .sh scripts on at the moment?

I'd say go with Mox for now, but feel free to try out Klone. You'll need to review the Klone guides in the Handbook, as Klone requires the use of containers. So, the learning curve is a bit steep for Klone ATM. But, Mox is dunzo as of 11/1/2024, so diving into Klone might be a worthwhile endeavor if you think you'll keep using the UW HPC stuff in the future.

Alternatively, just use Raven. That way, you can interact with Raven via the Rstudio interface, is easy to operate out of your git repo(s), and doesn't require the `sbatch script.sh` formatting and nosense...

**Comment by sarahtanja** [comment]
> So, the learning curve is a bit steep for Klone ATM. But, Mox is dunzo as of 11/1/2024

I am looking for shallow learning curve but need to use it through December... I'll review the guides and likely hop on Science Hour this Friday to check in on Klone/Mox user questions

> Alternatively, just use Raven. That way, you can interact with Raven via the Rstudio interface, is easy to operate out of your git repo(s), and doesn't require the sbatch script.sh formatting and nonsense...

I have been using Raven so far, but a `fastqc` command yesterday took 7+ hrs to run, and I'm working with 63 samples so I anticipate longer run times for a number of other steps too that I'd like to avoid... So I figure UW HPC is the way to go unless there's a secret way to make code run faster in Raven

**Comment by kubu4** [comment]
> a secret way to make code run faster in Raven

No secret. Raven's nearly as fast as Mox (actually has more threads/CPUs than Mox)...


> a fastqc command yesterday took 7+ hrs

Post new issue with FastQC code. Maybe we can see if there's something obvious slowing things down. Or, you may just have a boatload of data that will take than long no matter what. Or, maybe someone else happened to be using Raven at the same time, which would've slowed your job down significantly...
