### ISSUE TITLE
GitHub connection on raven in r is not working

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1999]
unable to push my commits in r from Raven to Github: 

![Screenshot 2024-10-29 at 2 51 49 PM](https://github.com/user-attachments/assets/4a446ec9-0d16-4e2b-90db-3d35e4c6c570)

**Comment by kubu4** [comment]
When you have a sec, can you please copy/paste the error in your original post? Makes it easier for searching. Thanks!

**Comment by shedurkin** [comment]
I've had similar errors when trying to push a file(s) that was too large, or trying to push a single commit with many largeish files, instead of breaking them up into multiple commits. I corrected this by undoing my last commit (`git reset --soft HEAD~1` will undo most recent commit but retain the changes) and either adding excessively large files to the .gitignore or spreading the changes over multiple commits.

I also found this [stack overflow exchange](https://stackoverflow.com/questions/44780221/git-push-failing-http-500-curl-22-the-requested-url-returned-error-500-internal) which suggested increasing the buffer size (among other things)

**Comment by shedurkin** [comment]
I've also experienced that! For me it happens when I've inadvertedly selected a huge number of files/changes in the git pane, or if a huge number are staged for a commit. For example, if I "check" the staging box for an output directory that contains dozens of files, it will take forever for all of the files to fully load and stage. I think I've just had to wait for them to load so I can unstage them.

**Comment by sr320** [comment]
you can also preemptively ignore before you create files.. I commonly doing this when generating bams and sams

**Comment by sr320** [comment]
Though this (indexing big files) likely does not correspond to error message at top.

**Comment by grace-ac** [comment]
yeah i didn't have any big sam or bam files... trying to check status in command line in that same GitHub repo and it's kind of frozen....
![Screenshot 2024-10-30 at 12 54 45 PM](https://github.com/user-attachments/assets/0910e2c4-ad74-4683-b2fd-19382e120ba4)

**Comment by sr320** [comment]
quick zoom?

**Comment by grace-ac** [comment]
yeah! your usual link?

**Comment by kubu4** [comment]
FYI - @sarahtanja was (still is?) experiencing lengthy wait times for `git status` yesterday as well...

We thought it was potentially tied to a possible errant `git add` command that may have added numerous hidden files of undetermined size.

She ran `git reset` and we could see the items that were accidentally staged for commit.

**Comment by sr320** [comment]
solution : deleted and started over pull from GH.
