### ISSUE TITLE
Install RepeatMasker on Raven

### ISSUE THREAD

**Issue by shedurkin** [RobertsLab/resources#2002]
I'm hoping to get [RepeatMasker](https://repeatmasker.org/RepeatMasker/), a transposable element identification tool, installed on Raven for E5 work. I'm pretty sure I don't have write permissions though in Raven's `home/shared` directory. @kubu4 or @sr320 would you be able to install it?

I double checked and this tool is not currently available in the /home/shared directory, and my attempt to install was blocked by a permissions issue.

**Comment by kubu4** [comment]
Whew! Finally finished!

Very glad we don't have to install RepeatMasker very often. Forgot how much of a pain it is.

It's here: `/home/shared/RepeatMasker-4.1.7-p1/RepeatMasker`

**Comment by kubu4** [comment]
I should add that this is configured with the `dfam38_full.0.h5` taxonomy partition/database.

Details are here: https://github.com/Dfam-consortium/FamDB

There are eight others. I did not install them due to file size/space concerns. The repeat family above should encompass what organisms we usually work with,.
