### ISSUE TITLE
Megan up unmapped reads

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#2009]
unmapped reads at 
https://gannet.fish.washington.edu/seashell/bu-github/project-pycno-multispecies-2023/output/04-pyc-hisat/

**Comment by kubu4** [comment]
Okay, this is up and running on _Mox_...

Took this approach since it was faster than trying to deal with installs/downloads/database configs on Klone.

Just a heads up, maintenance next Tuesday could be an issue. Last time I ran this on Laura's crab reads, the process took _41 days_! Of course, there are far fewer reads here, but the point is, this can be a long process...

**Comment by sr320** [comment]
Maybe just run one pair of reads - so we get something for proposal

**Comment by kubu4** [comment]
Mapping finished late last night. Currently importing into MEGAN to visualize/evaluate taxonomic assignments (import will take a couple of hours).
