### ISSUE TITLE
Rstudio project locks up upon opening in raven | is it due to an automated git status command and a large repo?

### ISSUE THREAD

**Issue by sarahtanja** [RobertsLab/resources#2029]
I'm experiencing the same 'lockup' issue #1998 working in raven in the `/media/4TB_JPG_ext/` drive as I was working in the `/home/8TB_HDD_02/` drive.

This issue arose only after I migrated the large fastq.gz files using `rsync` from gannet to raven. When I cloned the repo and made small edits on a code file, I was able to pull and push to GitHub, and open the RStudio instance without any lockup. 

This is what I see:
![image](https://github.com/user-attachments/assets/32f2c55c-1a40-4df9-a905-abe4b2bb5db0)

And this is the git command that is running:
![image](https://github.com/user-attachments/assets/be1f5f26-2118-450f-a403-8f78eb89b1fd)

```
/usr/bin/git status -z --porcelain -- /media/4TB_JPG_ext/stanja/gitprojects/coral-embryo-leachate
```

chatgpt suggests the following might be causing the lockup based on the above command:
> It sounds like there might be a Git-related plugin or configuration set up within RStudio on your remote server that automatically checks for version control status on startup. RStudio often integrates with Git to provide version control features, and this command could be part of that setup. However, if it’s locking up your instance, it could be due to:

A large repository: If the project directory is large, git status can be slow and resource-intensive.
Automatic Project or Git Setup in RStudio: RStudio may be trying to initialize Git for a project or workspace that’s set to open automatically.

And recommends these troubleshooting steps:
> Troubleshooting Steps
> Disable Git Integration in RStudio:
>
> Go to Tools > Global Options > Git/SVN in RStudio, and uncheck Enable version control interface for > > > > RStudio projects.
> Check Project-Specific Settings:
> 
> If you have a specific project that opens on startup, check if it has version control settings enabled by > navigating to the .Rproj file (if any) and disabling version control.
> Environment Configuration:
>
> RStudio might be set to automatically check the Git status in certain startup files. You can inspect > > > 
> .Rprofile or other startup files for commands that invoke Git on startup.
> Systemd or Cron Jobs:
>
> If you have admin access, check if there’s any scheduled job on the server that could be triggering Git > > commands on your RStudio instance.

The problem is as soon as I login to raven and open the project the lockup prevents me from any of the suggested troubleshooting steps (I can't close the project, restart the Rsession... anything in the UI). The only thing I can do is ssh to raven and use `kill <PID>`, but that doesn't relieve the RStudio project UI lockup.

**Comment by sr320** [comment]
Start over again - but this time when transferring fastq files do not put
inside of repo.

**Comment by sarahtanja** [comment]
Ok.. I think I'll also direct any large file output outside of the git repo too then

**Comment by kubu4** [comment]
If this were me, I'd "start over." It seems like there's an issue with the git history that's leading to the automatic git commands.

The presence/absence of large files in a git repo shouldn't have any impact on things, _unless_ large files have been actually added to the git index. As support for this thought process, I have multiple repos in which GBs upon GBs of files exist, but are _not_ tracked by git, and I don't have any issues with them in RStudio Server or otherwise.

So, with that said, this is what I'd do if it were me:

1. Clone existing repo to new location.
2. Delete repo from GitHub.
3. Create new repo (with same name as the old one) on GitHub.
4. Clone new repo to desired location on computer.
5. Copy files from old version of repo to freshly clone repo. !!! DO NOT COPY ANY `.git` directories/files !!!

These are generally "hidden" files, so you don't want to just do a blanket copy/mv/rsync command which might pick up those `.git` files!! To be safe, you'll want to "manually" copy your specific files to the new repo.

6. Add the files to the new git repo (with the `git add` command), but be sure there aren't any files >100MB!!! 

It's advisable to _NOT_ use the `git add .` or `git add *` commands to help avoid accidentally adding large files.

7. Push to GitHub.

All of the above will guarantee that you are working with a completely clean/new/fresh git history and should alleviate the `git` issues you're experiencing. Of course, you'll also lose your commit history (but, I guess you could go back to where you cloned your repo in step 1, if you need to get/view some old changes).

If you'd like to walk through this together, I'm more than happy to, but won't be available until late this afternoon (3 -4PM).

**Comment by sarahtanja** [comment]
Ok, I will start from the beginning with a fresh repo and come over to FTR from 3-4 today to check in

**Comment by kubu4** [comment]
Zoom

**Comment by sarahtanja** [comment]
We found the source of my miseries!

I had gotten into the habit of running `git commit -a -m "<commit message here>"`, The command `git commit -a` is a shortcut that automatically stages (adds) all modified and deleted files and then commits them in one step. 

`-a` option: This option stages all tracked files that have been modified or deleted, so you don't need to use git add for each one.

**From now on I'm omitting the `-a` option so that I can selectively choose which files to `git add`** 

Sam also helped me tailor my [.gitignore](https://github.com/sarahtanja/coral-embryo-ecotox/blob/main/.gitignore) file and showed me that even if I try to add a file that has been ignored I get an error code, and the file is not added. 

I restarted my repo in [coral-embryo-ecotox](https://github.com/sarahtanja/coral-embryo-ecotox/tree/main)
