### ISSUE TITLE
Getting high res. images for chapter figures

### ISSUE THREAD

**Issue by mgavery** [RobertsLab/resources#22]
I am looking for some help (ahem, Sam?) with getting high resolution images for chapter Figures.

The requirements: "please provide with min 300dpi for halftone/photograph at the physical dimensions that the image will be used (minimum width 166mm)"

Since I would like both figures to be 166mm, I think this is 1950 pix/in for the width.  Most of the photos I have are decent resolution, but I'm making modifications and labels etc. in powerpoint, so that's what I'm starting with.  

Here is a link to the powerpoint:
[https://drive.google.com/open?id=0B-vyLilchDgFSVR0VFB5SWUyZFk]

Thanks

**Comment by kubu4** [comment]
First, and I know you didn't ask for help/input with this, but could you straighten out Figures D & E? The horizon line is sloping to the right in both images and it's distracting.

Ideally, you should be making these figures in something like Adobe Illustrator and/or PhotoShop (InkScape and Gimp or freeware equivalents). These programs will allow you to save the files as 300dpi. PowerPoint only saves as 72dpi, no matter which export format you select.

However, if you want to stick with PowerPoint, set your canvas size to poster size first (e.g. 24" x 36"). After you get your figures labeled/tweaked, export the file as SVG, PNG, or TIFF (the first is the most preferable). After that, you'll have to open your exported file in some other software to adjust the DPI. I think the Preview program on Macs will allow you to set the DPI, but I'm not in lab today to verify. Otherwise, if Preview can't do it, you'll need Illustrator/PhotoShop (InkScape/Gimp) to save at the proper resolution.

**Comment by mgavery** [comment]
Thanks so much, Sam!

I have a question though. When I'm exporting out of power point and it asks me the width and height do I need to change those to ginormous as well?

![export](https://user-images.githubusercontent.com/4512578/29479241-e25eeaa0-8425-11e7-8564-7ca33a015518.png)

**Comment by kubu4** [comment]
Sorry for late response. Anyway, yeah, just keep it huge until you're at the point of having the final figure that you're going to submit.

**Comment by kubu4** [comment]
For Macintosh users, the easiest way to accomplish this is:

- Make large format PowerPoint (e.g. 24" x 36")
- Import various images into PowerPoint and create desired image.
- Export as PNG
- Open PNG file with Preview
    - Tools > Image Size...
    - Uncheck "Resample image"
    - Change resolution to 300
    - File > Export as...
