### ISSUE TITLE
More efficient ways to do basic stats in R?

### ISSUE THREAD

**Issue by kaitlynrm** [RobertsLab/resources#241]
I'm currently using [matrixStats](https://www.rdocumentation.org/packages/matrixStats/versions/0.53.1) to do basic stats in R to generate a table with several quantitative variables- median, mean, variance, skewness, kurtosis, etc. I did this in Excel previously but am trying to replicate it in R.

Often matrixStats has me generate a matrix instead of working directly off the df. Is there another package that has more stats options or a package that works directly off the data frame (so the process is faster)?

**Comment by sr320** [comment]
Can you provide a data table and a specific task to perform on the table?

**Comment by kubu4** [comment]
Can you give a brief explanation about your table? Specifically, what the rows and columns indicate?

**Comment by kaitlynrm** [comment]
The rows are the detected proteins. Columns are Silo_day. So each column has the NSAF value for each day measured based on each detected protein.

**Comment by kubu4** [comment]
Ok, thanks. 

Now, what is <em>one</em> thing you're trying to determine from this data and why? Also, what is the issue you're having in making this determination?

**Comment by kaitlynrm** [comment]
Well I'm just adding basic statistical measures in columns for each protein. I have been looking up packages with some stats and it's been working fine. However I often have to switch between matricies and dataframes and load several packages for these functions. Steven suggested I post here to see if anyone knew of a more encompassing package or faster way to perform them.

There is no one specific thing I'm looking for per say....

**Comment by kubu4** [comment]
> faster way

Can you expand on this a bit? What aspect of the process do you find to be too slow? E.g. 

- requires too much typing?
- loading packages takes a long time?
- computer takes a long time to perform analysis?

Maybe also post a link to your R script(s) and indicate what aspects of the script you wish were faster?

> Additionally, if there is another package that can generate standard deviation, variance, and quartiles without the extra step of making the df a matrix

No packages needed for these and these are functions that work directly on data frames:

- sd()
- var()
- quantile()

> There are a few stats I haven't been able to find: coefficient of variance, kurtosis, and skewness

- coefficient of variance is: sd()/mean()
- kurtosis and skewness both need an external library. ```library(e1071)``` will calculate both and will work on data frames.

> adding basic statistical measures in columns for each protein.

Why? If you're setting up an R script to perform the analysis, there's no real need to append the data to the table.

With all of that said, what are you going to do with these stats? Why calculate these?

> applied to all rows

R is set up to analyze data in <em>columns</em>. I think you'll need to transpose your data so that protein NSAF values are in columns and silo_day are in rows.

**Comment by sr320** [comment]
Note - this was just my request to see what I could do with dplyr
