### ISSUE TITLE
Annotate Oly Genome using Maker

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#261]
http://www.yandell-lab.org/software/maker.html

**Comment by kubu4** [comment]
Do we have an oly transcriptome assembly? If yes, could someone guide me to it?

Additionally, the same questions apply for a gigas transcriptome (I'd take a GFF3 alignment, too).

**Comment by sr320** [comment]
3 oly transcriptomes at 
http://oystergen.es/olympia/

**Comment by sr320** [comment]
however @ksil91 should have new Oly assemblies

**Comment by sr320** [comment]
@kubu4 not clear on gigas request.
But here is a lot of GFFs 
https://github.com/sr320/qdod/wiki/Genome-Feature-Tracks

**Comment by kubu4** [comment]
Thanks!

**Comment by kubu4** [comment]
Accidentally closed this!

**Comment by kubu4** [comment]
Good question. Haven't had a chance to check on progress since the most
recent Mox downtime.

I'll try to check on it in the next day or so.

**Comment by kubu4** [comment]
Preliminary results: 

- 303,426 GFFs!

Here're some other ramblings:

- Job initially started on 20180529

- Job got killed due to Mox maintenance on 20180612

- Job restarted (not resumed) later on 20180612

- Received second Mox email on 20180624 that the SLURM job began? Timestamps suggest that job was restarted! Not sure why. Email out to UW IT. Never received email that 20180612 job was killed/died...

**Comment by kubu4** [comment]
To add more info to my rambling from above, UW IT explained the multiple job start emails I received. Turns out, after the schedule Mox maintenance, the system attempted to restart my job, but it "hung" and wasn't discovered until 20180624. Then it was officially restarted.

Anyway, fingers crossed this will finish before the next Mox maintenance...
