### ISSUE TITLE
Status of Olympia oyster transcriptome

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#302]
Where do things stand with an improved Oly transcriptome? 
I know @ksil91 sequenced a lot - https://github.com/RobertsLab/project-olympia.oyster-genomic/issues/33
but not sure of assemblies. Is there a mega assembly and tissue specific assemblies?
I ask as I am analyzing WGBS data and trying to annotate DMLs.

**Comment by ksil91** [comment]
I have one that is annotated, but because of using multiple populations I think I have some transcripts from the same gene in different populations assembled as different genes based on raw reads mapping to multiple places. I want to try a more hierarchical assembly. I can upload the one I have now and it's annotations though if you think that'll be useful. I am TAing an undergrad  field trip in the desert Southwest until June 30, but I think I'll have WiFi time early next week to upload it from my cluster to /wetgenes folder.

**Comment by sr320** [comment]
If there was a way we could get the raw files, this would assist in genome annotation

**Comment by kubu4** [comment]
Sorry, @sr320 and I just talked about this and didn't realize that we have some (all?) of the RNAseq data. I didn't remember that the files (listed below) were RNAseq; thought they were more 2bRAD stuff for some reason.

Files labeled

CP-15
CP-16
CP-17
CP-18
CP-1
CP-2
CP-3
CP-4
CP-5
CP-6

are all RNAseq. 

These are in the nightingales/O_lurida folder.

**Comment by ksil91** [comment]
That's correct. Where should I put the sample information? Should I make a new Wiki page [here](https://github.com/RobertsLab/project-olympia.oyster-genomic) with sample info? I'll be uploading the assembled transcriptome today too.

**Comment by sr320** [comment]
Sure - a new wiki page would be fine
thanks
Steven

**Comment by ksil91** [comment]
Wiki page is up! Need to fill in some sample info about Laura's gonad samples.

**Comment by sr320** [comment]
What about the assembled transcriptome? is it available @ https://github.com/RobertsLab/project-olympia.oyster-genomic/wiki/RNA-Seq-February-2018
