### ISSUE TITLE
Consider Maker on Cyverse

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#312]
It would seem Maker is not really using all of Mox resource? It might be worth starting on Cyverse.

>MAKER is installed and available for iPlant users on the lonestar cluster at the Texas Advanced Computing Center (TACC). Here you can see the entire maize v2 genome (~2 Gb) can be annotated in just over 2 hours using as few as 500 cpus. MAKER-P was also used to annotate the largest genome ever sequenced (loblolly pine, >20 Gb) in less than 15 hours runtime on 8,640 cpus (37 hours total when including queue wait time).

**Comment by kubu4** [comment]
Haha! I love this:
>using as few as 500 cpus

Anyway, trying to get this set up on Cyverse. Default CPU allocation is only 16. Submitting a request for "as few as 500 cpus". :wink: 

We'll see if my request is granted...

**Comment by sr320** [comment]
I think I might have access to more cpus

**Comment by kubu4** [comment]
Well, the request is off to a rocky start:

>Hi, MAKER-P on Atmosphere is only for testing MAKER-P and not for actual genome annotation as Atmosphere doesn't have enough resources for completing genome annotationS. Alternatively you can take a look at Jetstream which has a lot more resources than Atmosphere. Here is the link that explains more - https://wiki.cyverse.org/wiki/display/TUT/MAKER+2.31.9+with+CCTOOLS+Jetstream+Tutorial. Let me know if you have further questions.
>
>Thanks,
>
>Upendra

We'll see where his recommendation gets me.

**Comment by kubu4** [comment]
OK, I _might_ be able to get something running via the CyVerse/Xsede/Jetstream platforms (whatever all those are). Upendra has set me up with access to his various system allocations or something like that.

I have to wait ~4hrs for the Jetstream account to activate and then I might be able to do something? 

Anyway, I'll be reading through the various documentation on how to use this stuff while I wait for account activation.

This could be awesome! :crossed_fingers:

**Comment by kubu4** [comment]
Still learning some stuff and have gotten access to using MAKER on Xsede/Jetstream(?). Not sure how much of the resources I've been given access to I'll be allowed to use, but Upendra has indicated we need to submit a Startup Application to Xsede to request our own resources.

Here are some successful applications, as examples (just look through the Startup Applications): https://drive.google.com/drive/folders/1uNROUEf7Yzj00jw0L1IM5K10YBXsDEX1

So, I think you'll probably need to create a user profile and submit a Startup Application - it doesn't look like any old regular research scientist can do that, otherwise I would.

I'll be viewing a new users webinar guide for Xsede, so will hopefully have a better grasp on some of the lingo they use to describe the available computing resources.

Regardless, having access to Upendra's computing allocation will allow me to "test" Maker on this platform (which has been specifically tailored to run on HPC clusters), so I'll try to get the Oly annotation going on Xsede this week.

**Comment by kubu4** [comment]
Fully up and running!

http://onsnetwork.org/kubu4/2018/08/07/genome-annotation-olympia-oyster-genome-complete-brief-note/
