### ISSUE TITLE
Set-up Titrator

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#33]
Titrator is here, in corner lab and is ready to be assembled so OA samples can be processed.

**Comment by laurahspencer** [comment]
Great!  I'll scope it out on Wednesday when I'm @ the lab and can start reviewing the manual, but will not likely be able to give it attention until after PCSGA (I'm gone next week).

**Comment by sr320** [comment]
@grace-ac you could start unpacking this week..

**Comment by sr320** [comment]
There appears to be an "issue" in getting this going?

**Comment by laurahspencer** [comment]
Yes, correct, I have yet to address this issue (and forgot to add it to my October Goals)- thanks for the reminder.

**Comment by grace-ac** [comment]
I have it mostly set up. The power connector cord for the Rondolino is pretty awful and has to be at weird angles in order to work. We got it to work and rotate the sample changer, but then it stopped when the cord got wiggled at an angle. @kubu4 is going to contact Mettler Toledo regarding this issue!

**Comment by kubu4** [comment]
Metler-Toledo is sending replacement cable to try; should arrive tomorrow. If that doesn't resolve the issue, they'll schedule a technician to come out.

**Comment by grace-ac** [comment]
New cord arrived! 
![img_4495](https://user-images.githubusercontent.com/14934314/31408388-2daa6bf4-adbd-11e7-85a5-d4b9843452b0.JPG)

I'll just have to move some cords around in order to get the titrator power cord to have a spot. I will NOT touch the cords hooking up the computer, in case anyone was worried about that.

**Comment by grace-ac** [comment]
Steven provided a power strip - all is well!

Everything is working! Generally speaking. 

I'm getting more into the finer details of the manual in terms of using the touchscreen to perform tasks. Things need to calibrated, test-runs, etc.
