### ISSUE TITLE
Clean up crab RNA samples w Cleanup kit

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#330]
Please take 10 RNA samples that represent individuals from each treatment and clean up. 

This would be similar to our prior MasterPool, but different samples.

Clean up the entire samples. 

with preference for samples with higher RNA levels

**Comment by kubu4** [comment]
@grace-ac - Please pull these samples for me when you have the chance.

**Comment by grace-ac** [comment]
picking samples from all three sample dates and all treatments, yes? 

(asking because we only have triplicate samples for Day 26)

**Comment by kubu4** [comment]
Concentrations are low, but there's RNA present in almost all of the samples. 

@grace-ac - Maybe you can compare the yields from the cleanup to your original yields for this set of samples?

Regardless, based on how clean the RNA turned out from the four samples I isolated RNA from earlier today, these should be nice and clean; which means I think we can trust the quants.

Here's my notebook: http://onsnetwork.org/kubu4/2018/07/31/rna-cleanup-tanner-crab-rna/

**Comment by grace-ac** [comment]
Haha, I just read your notebook posts, @kubu4 ! Thank you!! I'll compare right now.

**Comment by grace-ac** [comment]
They are all a lot lower (except tube 355 and 409 which aren't as far off as the others):      
## Original Qubit Results (RNA_ng/ul column):       
![20180731-cleanup-master-pool-original-qubit](https://user-images.githubusercontent.com/14934314/43491910-4b95e26e-94db-11e8-994c-2e2e6b3d63aa.png)

## Sam's Qubit results after clean up (note: 259 should be 359; comparable results in highlighted column):      
![20180731-sam-rna-cleanup-qubit](https://user-images.githubusercontent.com/14934314/43491919-57334c6a-94db-11e8-8b72-d0ee4e765c22.png)

**Comment by kubu4** [comment]
Fixed the typo in that sample - thanks for catching that! 

Although your comparison happens to work in this instance, you generally want to compare the _yields_ from both sets of isolations, due to differences in sample volumes.

For example, if my sample volumes were 200uL, I would have ended up with more amount of RNA than your samples.
