### ISSUE TITLE
Determine real -80 database

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#38]
per
https://github.com/RobertsLab/resources/issues/23#issuecomment-326435643

There appears to be two live sheets. The one mentioned above is not the the one linked 

at
https://github.com/RobertsLab/resources/wiki/Lab-Inventory

**Comment by kubu4** [comment]
My understanding is the sheet linked in the GitHub wiki is the correct one. I say this because I don't have the one linked by @grace-ac in my Google Docs (but I do have the one linked in the wiki). 

I believe the one @grace-ac linked in Issue #23 is the spreadsheet version she used to generate printouts to put on the door of the -80C.

**Comment by sr320** [comment]
I would attend to agree...

**Comment by grace-ac** [comment]
Yep - i have too many different versions of things. Will refer to the GitHub wiki, and GitHub in general for all the real versions!
