### ISSUE TITLE
Develop next phase plan for crab RNA extractions

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#393]

**Comment by grace-ac** [comment]
Lyophilizer is out of commission again... @kubu4 and I will be notified when it's ready

In the mean time,       
**would it be worth a try to extract RNA using Tri-reagent without lyophilizing?**

**Comment by sr320** [comment]
Yes, I believe it be worth doing that..

**Comment by grace-ac** [comment]
Plan for Monday/Tuesday next week:      
Use Tri-Reagent extraction protocol on following tubes:    
- **101** (there are 2 tubes labeled 101. Pam's notes from that day are: "There are 2 tubes recorded as 101 (3C, 8A), but there are no tube #s missing.")
- **460-2** (cold, day 26, uninfected)
- **482-2** (ambient, day 26, infected)
- **505-2** (ambient, day 26, infected)

Run on Qubit and Nanodrop/Bioanalyzer

See if protocol gives clean RNA and what yields are like without lyophilizing

**Comment by grace-ac** [comment]
@kubu4 I set aside hemolymph pellets and corresponding RNAlater supernatant for four samples in Rack 5, Column 4, Row 3. 

Since we don't have the lyophilizer working yet, we can try and see how it'll look without freeze drying. 

Let me know if you have any questions or need any assistance with anything, or if you want me to do it! I have class today 10:30-12:30 and then an eye appt at 4 (leave by 3:40pm).

![43059893_1848555415264035_5168073884590669824_n](https://user-images.githubusercontent.com/14934314/46426149-87f27800-c6f2-11e8-8029-f83a6a93ea7a.jpg)
![43125558_471627436685125_4204070493638098944_n](https://user-images.githubusercontent.com/14934314/46426150-888b0e80-c6f2-11e8-9ea5-25a0d8b4c95e.jpg)

**Comment by grace-ac** [comment]
101 --> a mistake sample 
471 --> Day 26, uninfected, ambient
462-2 --> Day 26, infected, ambient
482-2 --> Day 26, infected, ambient

**Comment by kubu4** [comment]
I'll let you handle this.

**Comment by grace-ac** [comment]
Bioanalyzer results:      
T3 --> sample that Sam processed, was lyophilized and used Tri-reagent
101A; 471; 462; 482 --> samples I extracted Friday (Tri-reagent without lyophilizing)

![20181008-electropherogram](https://user-images.githubusercontent.com/14934314/46640983-e9b44700-cb23-11e8-8921-1f7e16200a2b.PNG)
![20181008-gel](https://user-images.githubusercontent.com/14934314/46640984-e9b44700-cb23-11e8-8c42-15f7a2cc4bd4.PNG)

**Comment by kubu4** [comment]
Interesting.

Note: There's a technical issue with this Bioanalyzer run. The markers and ladder failed.

Also, what were the Qubit results from the TriReagent extracted samples? Based on the Bioanalyzer results, it looks like there's very little (if any) RNA in those samples.

**Comment by kubu4** [comment]
The marker didn't work either, so it's not just isolated to the ladder. Those are two different technical issues.

In regards to the ladder, you should know if there was sufficient volume. Were you able to pipette 1uL? If yes, then there was sufficient volume. Also, which ladder aliquots did you use? I think there are multiple sets of aliquots in the -80<sub>o</sub>C freezer.

> 
<sub>[View in Slack](https://genefish.slack.com/archives/DDBAZ28RM/p1539095963000100)</sub>

**Comment by grace-ac** [comment]
Yes, I know they're separate. I was just thinking back on the ladder, and I think it didn't look like quite 1 µL when compared to all the samples that I pipetted afterwards... but I could be mistaken. Or it might have been too frozen still to successfully pipet 1 µL. 

I was using the same ladder aliquots that I used the last few times I've run the bioanalyzer:    
[Rack 13, Column 4, Row 2](https://docs.google.com/spreadsheets/d/1Qsvz3QTURlPF_hX05BQxjom3484WuMfqQ1ILl9LEljU/edit#gid=2006985773) 
They were done by Hollie 8/26/16

**Comment by kubu4** [comment]
> They were done by Hollie 8/26/16

OK, good. Those are the aliquots we should be using, as they have been working (as you noted above).

Please pull three more samples that I can test out RNA isolations using TriReagent and then we can re-run the Bioanalyzer with all your samples and mine.

**Comment by grace-ac** [comment]
@kubu4 Samples are in box in Rack 5, Column 4, Row 3

They are the three screw-cap yellow tubes in positions 2-4. 

The samples are:     
429-1: cold, infected, Day 26
424-1: cold, infected, Day 26
438-1: cold, infected, Day 26

*Note: the "-1" part was added to the spreadsheet so that we can keep track of all the tubes. Day 26 samples were taken in triplicated (6 were taken for each of the three warm treatment crabs), so to account for all tubes, they were labeled with "-1", "-2", and "-3".

**Comment by kubu4** [comment]
No detectable RNA in any of the samples:

http://onsnetwork.org/kubu4/2018/10/09/rna-isolation-tanner-crab-hemolymph-pellet-in-rnalater-using-trireagent/

Overall, these results (@grace-ac and my isolations) are consistent with what @grace-ac has been experiencing all along: 

- RNA isolation methodologies produce inconsistent results.

**Comment by grace-ac** [comment]
So I think for now perhaps I should re-Bioanalyze the sample that you extracted that was lyophilized...? Because the BIoanalyzer results from yesterday apparently weren't done properly. 
That way we can see if lyophilizing helps at all? 

Or maybe those samples that you extracted today didn't even have hemolymph cells?
