### ISSUE TITLE
Assaying for Vitellogenin abundance in Geoduck

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#424]
@emmats we're trying to see if we might be able to use a [commercial vitellogenin ELISA kit](https://diapharma.com/product/ecotoxicology/teco-multi-species-vitellogenin-elisa/) with Geoduck hemolymph samples. I'm wondering where I can find the protein/peptide sequence(s) for the Vitellogenin (cds.comp144315_c0_seqI|m50928) you detected in your proteomics paper, so we can share it with Diapharma to see if it would be compatible with their antibody. And I'm also wondering what your thoughts are on other potential assays for this. I know you mentioned SRM in lab meeting, and did it in your paper, but how straightforward and economical would SRM be for this application? THX!

**Comment by emmats** [comment]
The protein sequence would be in the protein fasta file, that I believe @sr320 has, but I have copied the protein sequence below. Do you want the peptides that I actually used in the SRM assay? 

I did ask Charlotte Corporeau if she knew of any assays. She said she would ask around and I have not heard back. I'm not well informed on other types of protein assays. My answer would be ELISA or Western Blot.

Since we have already done SRM in geoduck hemolymph and know we can detect it, you wouldn't necessarily have to do intensive mass spec to develop the assay. I think it would be worth measuring as many Vg peptide transitions as possible in a few samples and seeing which ones look the best and change abundance as expected with advancement of reproductive stage.

The mass spec for doing SRM costs about $90-155 per day (we have two prices in the spreadsheet and I'm not sure why...). It takes about 1 hour to run 1 sample.

Let me know if you want to know more - via github or in person. I'm only 2 blocks away.

MTVACIMVRLLVLTISLGLAACQRPKSIETVYSNGKEYLYDYESQILSGLPQGSRIYSGF
KLKAQVRFQLISSSGNMKMELRNPKIYSINSEIGKEDSSREMLPMELFQELLDMDSDKMK
RELIKPLSFSFIRGHIEDLVTEGDDPEWSVNVKRGCISLMEVNFNERQSLDPKIDVLPSD
PTPSIYRVIEPSITGECETTYRLKSDRSPDGSPSMDIEKVRNFNRCLEKVIFRRNMMNWR
ECEYCDIDEDMETFTAQSSVRYSILGSPDQFLILRAVGESQYNFVPYLENRGRVSTFLNQ
TLTLLDSRPISDQIPEMRSRLQHERPLKANTLEEKSSSSLSPWKSDLTEKEKEEYYKKTW
KVLVGIEELTKDKMEDEVSDLLLELGRLLKKLDKTTLNKLTDKIIKDPSKYSRARKTLLD
LLPTIGTYDTIDVLLERIEKQELPRDSVIVSLMSLSLLPQPDVFIVKRFMNYITVLDKTK
SMTDDQLLRRSAWLCLGSLGGKMLKMNKTLVKELEDERKLVKELREEANERRVRRRLDKK
LEHVDNQRHQIEELYSTARTQIIDMVTKLHEKTDRDYKLLALKTMNSLGYDEFYPLLEKL
INDMDSPLLHRMEAITSLQKLTEYNPDKVKTLLLPLFFDRKQPEEMRMIAYLTSILARPS
RPELEMIAKSLEDEPSTNVGTLVWTSLVASSNKMPKCDCIKSLARNSTMAMRFAQKSEGG
VQHSNYMYRSSFDKKTRLGHSYEQVLLHSAKERFPRAFAMQYTATLMGKTVDLFELGYKA
KGVDTIVDRMYGVLGDTSMTNIVRKLFDTKFMKTVSPMEQELLKMKEKLEVKSRFPEIPE
GHVYMKLFGQELIYFDLPSMLGPSLTSSPDGSDGSQPNDLKLTKILPELMNVVISLNRLL
KTQKSAFFPLMSTMLPTETGLPLRFGIDKVAALKIDGDVKFEKEKDPNTSEKKFLLSSFD
SLLKFRFGCVFEIRGNMEVDFKYIRSTLSLQGRVSVEAPVTLAVNVDTTKSKLLLHLQDE
KEFYPVKMVSRPSSEIRRMPSDADRYPIPPDVKEIIIIDGADVRLFSYDIGKDTLGRKLT
VNGEMTVSRDDSCPLPPLNGRQVLYIKYEPLTFTGLDIQMQRVREVSTKDPSISTVSKQT
EPWWLPSWLSGTSTEEQSYSGPDRNKFEKNLDDPNKGFIVLDKTDLSLPYIKKKFERETE
LMKTGVKCGMVIRVSDHVPQPKHQIQLTTLYQSDSSGSQQWYSIELMKAPKSDERMPWKM
MTTVKLDLPETVVKPSFLLDNEYQKFIQDQIKVIVTENGKQTDSLLDLGSKFLTKAIKQL
YKLQRRDSTDKIIEDVVSHVLERSVDKDSAQLRDSVQEQRKLLKETDKLKKQLSEPRKLK
SQLELLKKILLKTKLVSETVSKNLDVIPWKQQKPEDSVMVLYVVSRQTQLKKKLRKIVEK
LHPLLTTNEKLDLESKLKEQKQSLDDIRMKQNTLSLAKQSTEEQKSRIEMEPKERSLQRQ
LLDIEQILISVSMERKNGKPFPSNKEKTYEIEKYLNKVIEKTKKVKDEMDERLLQKVKID
KMLRVKLLEVLLHQKLTVLDIEDKLLYQDKKQKPLFLRSPYSSYNDLEYPLKKENIKLKD
DLQREFGDLARRLAVSVDCEIETDSLVSFLSSEDQQQMDTLQKLKINQLRMLELLRTKSH
PSETETDLPTLDSVKETVHLIKESHEKIKDIVETIKSEKMRGIKQMMNPVLIKSLKIISK
QFDILNKVKQIIKHKMIVQALKEDEPKLESYKLLKREVFDLKENTIKELKKIEHLTMKDD
NKDMERSPTLTFPKEDNELPSRERTLRKPRSLPVSTLLKKALKVQTKQLQMKAEIEKLSM
VLDVPQYRDTGMLTLRQIKQKQIVYDVIGKAIDVQDELEELNKALQEKMEDTPEDKSVRD
LIKVVDDRQDELKKTIKLFEDTVEHNSRMDNSLVVPLEKLQQLKDRIEQQQLKVQKTKER
FDQLREAVDSDSKRTLPKYPKNLPSRSSMEMPNGRRIFMKDLRGVINIAYGPDGETPKKV
EIRLFGKKSLSQLFWELDQFEPSKQDPLMRKYLQERREPNDAVAKGYEMIADELNTYRHL
YLLCIYEDSLPVEVRALFWRMQEYMKYRLYDRTSLRMPDETNMKNEIQILTEIKRDNKWA
DVEIKTPYETMKMHNLRTPQLCKLATVPNTVSFEHHVIKSLTRTKLPATCELSKNRIKMF
RGKTYEIDMKPKPCTKVLAMDCSPSNKFAITSSPHSQQSDKTVVTLVTKTKKVEIVPDPD
EPKMTVKVNDEPVEFKDEIITKDSDSEILKIRKLDGGQLMVTIPQLSVIAITDGEHTSIT
VGSFYWSKVCGVCGHLGDQDSNSLQGPQKVLYPSPEAFVSTYLLPDDQCDVKSIQSQYNV
PDIRRESKHVHPKERTNIIKHRMNGIQRTCFSKTPVKSCPSSSRSEGTETRLVSYYCLRS
SSRMAQSLIRLAQTRVLDEVRTNFSDLNEYIREPKVCKLE*

**Comment by shellytrigg** [comment]
Thanks so much @emmats . It would be great to catch up more about the SRM stuff in person, especially since you're so close. Maybe sometime Friday or next week?

**Comment by emmats** [comment]
I should be around Friday, although I may have something in the morning. Do you want to meet around 11 or 12? I can come over to FTR.

**Comment by shellytrigg** [comment]
Sure, either time works. I'm in 234.

**Comment by emmats** [comment]
I'll aim for 11:00. See you then.

**Comment by shellytrigg** [comment]
great thanks @emmats

**Comment by kubu4** [comment]
@emmats - Can you please post link to FastA file? I didn't see any reference to a FastA file in the paper...

**Comment by emmats** [comment]
Again, @sr320 made the file so he probably has a link somewhere although I looked in cnidarian and couldn't find it. You'll note in the methods that a publicly available transcriptome was analyzed with Transdecoder to get the proteome for analyses.
Here is the file: https://drive.google.com/open?id=1FfyuLyJ3Hfp9PS4qzed8_Sol3n9EfoXW

**Comment by kubu4** [comment]
I saw your message, but how did you pull up the sequence so quickly if you
don't have a FastA? Can you please share a link to the file you used to get
that sequence?

**Comment by kubu4** [comment]
Thanks for link to file. That's all I wanted (FastA or not).

**Comment by kubu4** [comment]
That link you provided _is_ a/the FastA file!

**Comment by emmats** [comment]
Yes, I know. I just knew that Steven already had it somewhere on the Roberts Lab cluster and if he had been able to provide the link it would have been simpler. Of course I had it. I did the analyses.
