### ISSUE TITLE
Clarifying Abacus values to use in NMDS and downstream analyses

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#539]
Based on [the DDA analysis wiki](https://github.com/sr320/LabDocs/wiki/DDA-data-Analyses#convert-mass-spec-ms-raw-files-mzxml-files-for-use-in-comet) and [Emma's JOP geoduck paper](https://pubs.acs.org/doi/abs/10.1021/acs.jproteome.7b00288), ADJNSAF values should be used for NMDS analysis of technical replicates. Can anyone confirm this is correct?

Besides QSPEC, when should NUMSPECSTOT values be used? When is it appropriate to sum replicate values vs. use their average?

I think I don't understand why we want to use ADJNSAF values in some analyses and NUMSPECSTOT values in other analyses. @emmats can you comment on this?

**Comment by emmats** [comment]
Use the adjusted NSAF for all analyses, except qspec. Qspec only accept whole numbers, so you have to upload spectral counts. It also does its own internal normalization, kind of like NSAF (that's why you have to include protein length).

For qspec, since it only accepts whole numbers, I tend to sum technical replicates. Otherwise, I average them. But if you were to sum instead of average, you should get the same general results.

**Comment by shellytrigg** [comment]
@emmats THANK YOU! So helpful!
