### ISSUE TITLE
Bioinformatics task: differential expression between pH, Oly larvae

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#545]
I'm looking for differential expression analysis on QuantSeq data (aka TagSeq) in Olympia oyster larvae, which were spawned from pH-treated adults. There are 4 samples/files per treatment (data is already demultiplexed), and files are located here: http://owl.fish.washington.edu/wetgenes/20181109_QS_Laura/ - metadata and direct links to files listed below. 

I'm interested in getting this expression data aligned/annotated with the Oly genome to produce a table of counts - differential analysis would be a bonus. The developers of QuantSeq/TagSeq provide this [processing pipeline](https://raw.githubusercontent.com/z0on/tag-based_RNAseq/master/tagSeq_processing_README.txt), but it doesn't necessarily need to be followed. 

I used Kallisto and a denovo-assembled transcriptome previously - check out [my github repo](https://github.com/fish546-2018/laura-quantseq) for more details. 

Oly genome links [located on this page](https://github.com/RobertsLab/resources/wiki/Genomic-Resources)

File Name | RNA sample No. | Treatment | Tissue | File Link
-- | -- | -- | -- | --
L34-L_S25 | 34 | Ambient | new larvae | http://owl.fish.washington.edu/wetgenes/20181109_QS_Laura/CP-KS-LibL-L34-L_S25_L006_R1_001.fastq.gz
L35-L_S31 | 35 | Ambient | new larvae | http://owl.fish.washington.edu/wetgenes/20181109_QS_Laura/CP-KS-LibL-L35-L_S31_L006_R1_001.fastq.gz
L37-L_S32 | 37 | Ambient | new larvae | http://owl.fish.washington.edu/wetgenes/20181109_QS_Laura/CP-KS-LibL-L37-L_S32_L006_R1_001.fastq.gz
L39-L_S29 | 39 | Ambient | new larvae | http://owl.fish.washington.edu/wetgenes/20181109_QS_Laura/CP-KS-LibL-L39-L_S29_L006_R1_001.fastq.gz
L41-L_S27 | 41 | Stressed | new larvae | http://owl.fish.washington.edu/wetgenes/20181109_QS_Laura/CP-KS-LibL-L41-L_S27_L006_R1_001.fastq.gz
L44-L_S30 | 44 | Stressed | new larvae | http://owl.fish.washington.edu/wetgenes/20181109_QS_Laura/CP-KS-LibL-L44-L_S30_L006_R1_001.fastq.gz
L45-L_S28 | 45 | Stressed | new larvae | http://owl.fish.washington.edu/wetgenes/20181109_QS_Laura/CP-KS-LibL-L45-L_S28_L006_R1_001.fastq.gz
L47-L_S33 | 47 | Stressed | new larvae | http://owl.fish.washington.edu/wetgenes/20181109_QS_Laura/CP-KS-LibL-L47-L_S33_L006_R1_001.fastq.gz

**Comment by ksil91** [comment]
Working through this right now using de novo transcriptome mapping (which is slightly different then what you'll need to do for the genome), but here are some comments:

Many programs to estimate expression data include corrections and normalization based on transcript length. QuantSeq produces only one fragment per transcript, so these approaches are not valid. You want to use a mapper to get raw read counts per gene, then normalize your read counts using a method that does not take transcript length into account like htseq (which is in the QuantSeq analysis pipeline). Some options:

- STAR/bowtie mapper, htseq to count reads per gene (as in QuantSeq analysis pipeline), DESeq2 or edgeR for normalization (DESeq2 actually requires information on raw read counts). See [this](https://www.biostars.org/p/242906/) for advice on how to do in edgeR 
- the Matz script for counting reads instead of htseq after bowtie2 mapping (what I've been using, but now am not certain is the best way)
-Or use an expression level estimator that does not take transcript length into account. The only one I've found is salmon with `--noLengthCorrection`. See [this](https://groups.google.com/forum/#!topic/sailfish-users/VIfqBwgF6xQ) and [this](https://github.com/COMBINE-lab/salmon/issues/108). You should avoid RSEM. [Looks like kallisto also does automatic length correction](https://www.biostars.org/p/186368/), so probably not valid either. Note that salmon assumes mapping to a transcriptome, but their docs explain how to use it when mapping to a genome. If you go this approach and are extracting transcriptomes from genome, I read somewhere else to make sure and capture a little upstream(downstream?) of the 3' end to make sure you get the section where QuantSeq will map to.

[DeSeq2](http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html) has great documentation, which is why I like it. However I just realized I can not properly model random effects from tank replicates with it (only fixed effects), so I will eventually move to voom-limma. For your study though, I think DeSeq2 will work well.

I'm writing up the thesis using the de novo mapping since I don't have time to try with genome, but I think for the paper I will probably use the genome or some combination. So in a month will be figuring out the best way to use the genome, too!

**Comment by tamuanand** [comment]
Hi @ksil91 

Thanks for the detailed inputs with reference to the original question.

I have a very specific question on RSEM based on your response - could you elaborate on why you state not to use RSEM

Thanks in advance

>You want to use a mapper to get raw read counts per gene, then normalize your read counts using a method that does not take transcript length into account like htseq (which is in the QuantSeq analysis pipeline). Some options:
> 
> * STAR/bowtie mapper, htseq to count reads per gene (as in QuantSeq analysis pipeline), DESeq2 or edgeR for normalization (DESeq2 actually requires information on raw read counts). See [this](https://www.biostars.org/p/242906/) for advice on how to do in edgeR
> * the Matz script for counting reads instead of htseq after bowtie2 mapping (what I've been using, but now am not certain is the best way)
>   -Or use an expression level estimator that does not take transcript length into account. The only one I've found is salmon with `--noLengthCorrection`. See [this](https://groups.google.com/forum/#!topic/sailfish-users/VIfqBwgF6xQ) and [this](https://github.com/COMBINE-lab/salmon/issues/108). You should avoid RSEM. [Looks like kallisto also does automatic length correction](https://www.biostars.org/p/186368/), so probably not valid either. Note that salmon assumes mapping to a transcriptome, but their docs explain how to use it when mapping to a genome. If you go this approach and are extracting transcriptomes from genome, I read somewhere else to make sure and capture a little upstream(downstream?) of the 3' end to make sure you get the section where QuantSeq will map to.

**Comment by ksil91** [comment]
@tamuanand Sorry for the delay. RSEM should not be used for 3' TagSeq methods (such as Quanteq), but is ok to use for typical RNAseq. This is because RSEM and many other methods were designed to take the length of the full transcript into account when estimating transcript abundances, because multiple fragments are generated per transcript and the number of fragments vary by transcript length. With TagSeq, only 1 fragment is generated per transcript, which makes it more accurate however means that length correction methods will introduce bias. Happy to discuss more, will be more available going forward.

**Comment by tamuanand** [comment]
Hi @ksil91 Thanks for the reply. Have you tried salmon with the --noLegthCorrection method on QuantSeq data? If yes, what command line parameters did you use.

 I was thinking of using something like this 

```salmon quant -i {input.index} -l A -1 {input.R1} -2 {input.R2} -o {output} --noLengthCorrection --validateMappings --gcBias --seqBias --posBias```

Also, [the Salmon authors have recently mentioned about the Selective Alignment (SA) method using gentrome (genome + transcriptome) 
](https://www.biorxiv.org/content/10.1101/657874v1)

I am also thinking of using the gentrome method for indexing and the command line as mentioned above.

Would be curious to know your thoughts. 
> @tamuanand Sorry for the delay. RSEM should not be used for 3' TagSeq methods (such as Quanteq), but is ok to use for typical RNAseq. This is because RSEM and many other methods were designed to take the length of the full transcript into account when estimating transcript abundances, because multiple fragments are generated per transcript and the number of fragments vary by transcript length. With TagSeq, only 1 fragment is generated per transcript, which makes it more accurate however means that length correction methods will introduce bias. Happy to discuss more, will be more available going forward.
