### ISSUE TITLE
add tree to OSF repo

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#55]

**Comment by kubu4** [comment]
Do we want to alter that repo, since it's associated with the published paper?

In the mean time...

- [SVG version of tree](https://github.com/RobertsLab/paper_oly_gbs/blob/master/data/nj_tree.out.tre.svg)

- [Low res PNG version of tree](https://github.com/RobertsLab/paper_oly_gbs/blob/master/data/nj_tree.out.tre.png)

- [RobertsLab oly gbs paper repo](https://github.com/RobertsLab/paper_oly_gbs/tree/master/data)
