### ISSUE TITLE
RNA extractions next steps? no RNA from geoduck hemo extractions

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#557]
I was unable to extract RNA from the geoduck hemolymph samples using the Trizol LS reagent ([post](https://grace-ac.github.io/trizol-with-geo-and-oyster/)) or the RNeasy kit ([post](https://grace-ac.github.io/QiagenRNeasy-withgeoduck-andoyster/)). 

I was able to extract RNA (Qubit reads were "Out of range TOO HIGH") from oyster tissue samples using Trizol LS (not designed for tissue samples) and RNeasy kit.  

### What now? 

- Should I bioanalyze the oyster tissue samples? 
- Should I try bairdi hemolymph again using both methods but do something different? 
- Other...?

**Comment by kubu4** [comment]
I think you should try using the Direct-zol RNA kit. We have two of them at the RNA isolation bench in FTR209. Quick protocol summary:

- Lyse/homogenize tissue in Trizol (TriReagent)

- Add mixture to spin column

- Wash column

- Elute RNA

Should prevent any loss of RNA, since there's no phase separation step to deal with.

**Comment by grace-ac** [comment]
Thanks @kubu4 ! I'm looking at manufacturer protocol now and will try this out tomorrow.
