### ISSUE TITLE
Ronit's data - Which stats test(s) is most appropriate?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#569]
We're using some recycled code for running an ANOVA followed by Tukey's HSD for determining statistical significance between various interactions. Is this the correct approach?

His R Project (including data files and R script) can be cloned from here:

https://github.com/ronitjain31/gigas_ploidy?files=1

He needs to have some of this figured out before the scheduled discussion of his data on Feb 22nd for poster prep and whatnot.

Any suggestions are greatly appreciated!

**Comment by yaaminiv** [comment]
While you're doing your Tukey's HSD you want to correct for multiple comparisons (more information: http://www.biostat.umn.edu/~cavanr/asfChap4-2.pdf). This is as simple as adding `method = "BH"` as an argument for `TukeyHSD()`.

**Comment by shellytrigg** [comment]
To elaborate more on Yaamini's suggestion, I wanted to point out there are two types of multiple comparisons happening:
1. [The multiple test problem](https://en.wikipedia.org/wiki/Multiple_comparisons_problem#Correction) happening because we are applying ANOVAs to 10 different genes. The odds are higher that we find something significant simply because we are doing 10 ANOVAs (aka there's a higher chance for type 1 error). Applying an FDR correction (like bonferroni or BH - the p.adjust R function) to the ANOVA p-values would control for this. 
2. The multiple comparisons done by the [Tukey's test](https://www.rdocumentation.org/packages/stats/versions/3.5.2/topics/TukeyHSD). If an ANOVA identifies a factor or factor-interaction (e.g. ploidy, heat stress, the combo of ploidy and heat stress) as having a significant effect, we run TukeyHSD if we want to identify which comparison(s) underlie the significant effect. Was it:
1. diploid-triploid?
2. no heat stress-heat stress?
3. diploid-no heat stress?
4. diploid-heat stress?
5. triploid-heat stress?
6. triploid-no heat stress?
 
Tukey's essentially applies 6 different t-tests to determine which combinations of factors had a significant effect. See [R function details and values section for more](https://www.rdocumentation.org/packages/stats/versions/3.5.2/topics/TukeyHSD). Because there are 6 tests being applied, the TukeyHSD R function has a built-in p.value adjustment to correct for the increased chances of finding a significant effect simply from doing 6 t-tests. This is why the TukeyHSD output shows "p adj". [More info here](https://stats.stackexchange.com/questions/253588/interpreting-tukeyhsd-output-in-r).

If it were me doing this analysis, I would first apply an FDR correction (p.adjust() function; default is 'BH' also called 'FDR') to the overall ANOVA model p-values (obtained by the glance() in the broom package). I would see if any genes show an FDR-corrected overall ANOVA model p-value < 0.1. If a gene did, I would run the Tukey's test to identify which combination(s) of factor levels are significant at "p adj" < 0.05 or < 0.1 depending on how stringent we want to be. 

However, in [my crab metabolomics manuscript](https://drive.google.com/drive/folders/1uKf25Pj7jFr1PoJZX03s7VGsmeO77Vap?usp=sharing) where I did an ANOVA on each of the 3746 metabolites identified, I chose to assess raw ANOVA p-values rather than FDR-corrected p-values and cited [this paper](https://www.ncbi.nlm.nih.gov/pubmed/26596774) which describes applying an FDR correction to all detected compounds assumes that all compounds had equal chance for discovery, which can mask important biology in highly variable datasets. I'm not sure what reviewers think of this since I haven't received reviewer comments yet, but NOAA's review board was OK with it. @kubu4 @ronitjain31 in this manuscript, I also described assessing compound abundance normality (I used [shapiro.test() R function](https://www.rdocumentation.org/packages/stats/versions/3.5.2/topics/shapiro.test)) and homogeneity of compound abudance variances within treatment groups ([levene.test() R function](https://www.rdocumentation.org/packages/lawstat/versions/3.2/topics/levene.test)) prior to running ANOVA.

Does anyone have any other thoughts?
