### ISSUE TITLE
Determine WGBS cost if done at UW

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#580]

**Comment by kubu4** [comment]
This assumes we'll be doing library prep, correct? Or, is there a core facility doing bisulfite conversion/library prep now?

**Comment by sr320** [comment]
Both - see if core a would do prep; and what our in house cost would be for library prep.

**Comment by kubu4** [comment]
They do not offer methylseq library prep - sequencing only would be our only option, so we'd have to prep libraries ourselves.

Putting this table here for reference. Will calculate sample prep costs (and fill in the rest of the table once I receive the info) soon.

---

#### Table is based on 150bp PE sequencing.

| Sequencer             | Output (million reads) | Cost (USD) |
|-----------------------|------------------------|------------|
| NextSeq (high-output) | 400                    | 5382       |
| HiSeq X               | 2500                   | 11200      |
| NovaSeq SP            |                        | 4714       |
| NovaSeq S1            |                        | 7318       |
| NovaSeq S2            | 3300                   | 15881      |
| NovaSeq S4            | 10000                  | 21395      |

**Comment by kubu4** [comment]
DNA isolation & library prep in our lab:

- ~$65/sample

---

Based on isolating DNA with EZNA Mollusc DNA Kit (\~$2.25/sample) and library prep with Zymo Pico MethylSeq kit (\~$55/sample) and Bioanalyzer QC (\~$3.00/sample, but is actually higher due to reagent expiration times).

Pico MethylSeq kit only has six indexes included, so would need multiple flow cells on machines listed above if prepping more than six libraries.

**Comment by kubu4** [comment]
I'll also add that the HiSeq X has 8 lanes, so could accommodate more than 6 samples in a single flow cell.

**Comment by sr320** [comment]
remaining question is how many reads do we need per library...
