### ISSUE TITLE
Running C. virginica sperm samples on a gel

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#605]
@kubu4 you mentioned that I should run my [*C. virginica* sperm samples](https://yaaminiv.github.io/Sperm-Extractions-Part5/) on a gel before I shear the DNA. It's been many moons since I ran a gel and I don't remember how to do it, but I couldn't find a protocol anywhere. Do we have a lab protocol for running a gel?

**Comment by kubu4** [comment]
There is no protocol, due to the large number of variables in running a gel (e.g. number of lanes needed, width of each lane desired, gel mold/apparatus to use, agarose percentage, etc.).

In general, for looking at genomic DNA, here're some rough guidelines:

- 0.4% agaorse gel (using 1x Low TAE)
- Tips to determine volume of gel needed:
  - prep gel mold with desired comb(s)
  - fill 100mL graduated cylinder with 100mL water
  - pour water to appropriate level in gel mold and note how much volume you used
- Tips for melting agarose:
  - use flask with at least double volume of your gel volume
  - add 1x low TAE to flash, followed by agarose - do not swirl
  - weigh flask and tare scale
  - microwave flask for 1 minute at a time, swirling the flask after each minute (careful! it's HOT!). When agarose is powder/chunks are no longer visible, re-weigh flask and add 1x TAE to bring weight back to original weight, and set flask on bench to cool
  - once flask is cool (~55<sup>o</sup> - i.e. cool enough to hold flask on palm for ~15 seconds w/o feeling pain) then add ethidium bromide (10mg/mL stock) at a 1:1000 dilution (e.g. add 10uL of ethidium bromide to 100mL gel volume)
- Use [high range ladder](https://github.com/RobertsLab/resources/blob/master/protocols/Commercial_Protocols/ThermoFisher_GeneRuler_HighRange_DNALadder_50ug.pdf) (this is somewhere in the -20<sup>o</sup>C in FTR 209
- Prepare samples using 6x loading dye supplied with ladder
- Load 50 - 100ng (I used 100ng, if I can spare that much) of each sample
- Run gel @ ~100V for an hour or so to get good separation of the ladder.
- Use transilluminator to visualize bands (tip: use orange filter over phone lens; filter is on tray on top of power supplies)

**Comment by shellytrigg** [comment]
I can help you go through this @yaaminiv if you want

**Comment by yaaminiv** [comment]
@shellytrigg That would be great! I'm thinking of doing this Monday afternoon. I haven't made my own gel before so it would be nice to have some help.
