### ISSUE TITLE
Advice on MBD-BS library prep

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#607]
FIU folks would like specific advice on MBD-BS library prep and sequencing
I am thinking what was done for Yaamini's Cv samples.

I imagine there is not a url that captures it all..
What kits were used? 

Does it happen to match https://peerj.com/articles/215/#p-5 ?

**Comment by yaaminiv** [comment]
It doesn't match Claire's paper.

- DNA Extraction: EZNA Mollusc Kit (Omega)
- MBD: MethylMiner (Invitrogen)
- Library Preparation: Pico Methyl-Seq Library Prep Kit (ZymoResearch)
- Bisulfite Conversion: EZ DNA Methylation - LightningTM kit (ZymoResearch)
- Sequencing Information: Paired-end, non-directional, Illumina HiSeq1500

**Comment by sr320** [comment]
Why did we change from what was done for 

https://peerj.com/articles/215 

- MethylMiner Kit (Invitrogen) 
- **Illumina Tru-Seq system with methylated TruSeq adapters** 
- **EpiTect Bisulfite Kit (Qiagen)**

**Comment by kubu4** [comment]
Mac will probably have a definitive answer, but my guess is that Mac's stuff was done prior to the development of methylation-specific library construction kits. Once Illumina produced the TruSeq DNA Methylation Kit (which is no longer in production as of this year), then their library production methodology was followed. This meant using:

- EZ DNA Methylation kit instead of EpiTect Bisulfite Kit

For @yaaminiv's stuff above, the Illumina TruSeq DNA Methylation Kit was likely _not_ used due to input DNA quantities being too low for the minimum amount of DNA required to use the Illumina TruSeq DNA Methylation Kit; so we used the Pico Methyl-Seq Library Prep Kit (which also uses the EZ DNA Methylation kit for bisulfite conversion).

**Comment by sr320** [comment]
@hputnam - Is this the approach you are using?

- MBD: MethylMiner (Invitrogen)
- Library Preparation: Pico Methyl-Seq Library Prep Kit (ZymoResearch)
- Bisulfite Conversion: EZ DNA Methylation - LightningTM kit (ZymoResearch)

**Comment by hputnam** [comment]
Yes, I am working up a protocol for the following and will test this against WGBS with the same approach minus the MBD

Quick-DNA/RNA Miniprep Plus Kit - This works well with corals so far, but is not working well for Mytilus
https://www.zymoresearch.com/collections/quick-dna-rna-kits/products/quick-dna-rna-miniprep-plus-kit

dsSherase - for fragmentation prior to MBD
https://www.zymoresearch.com/products/dsdna-shearase-plus

DNA cleanup
https://www.zymoresearch.com/products/dna-clean-concentrator-5

MBD Enrichment
https://www.thermofisher.com/order/catalog/product/ME10025

Pico Methyl-Seq Library Prep Kit (ZymoResearch) - This has the lightning BS conversion included
https://www.zymoresearch.com/products/pico-methyl-seq-library-prep-kit

**Comment by sr320** [comment]
@kubu4 I presume we are using the sonicator in lieu of dsSherase?

**Comment by hputnam** [comment]
I have not yet tested the sherase. We don't have a sonicator in our lab, but our core does, so I was going to compare the two in the protocol test.

**Comment by yaaminiv** [comment]
@sr320 We're using the sonicator, then confirming shearing with the Bioanalyzer.
