### ISSUE TITLE
Determine status of samples on Manchester dock

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#61]
Ryan made a sheet listing some of our Olys

https://docs.google.com/a/uw.edu/spreadsheets/d/160_yNhscMAxTHoyTZXkUNZbwhjb4WM094RhYM0Y3_Ig/edit?usp=sharing_eil&ts=59c18ed1
(Noting it is restricted)

We need to determine if these are viable and/or valuable.

![5dd0bdce-bb55-49bf-99a0-022ede41b81c](https://user-images.githubusercontent.com/4442039/30655023-9cd0b666-9de4-11e7-95e1-6ae3fce6ec78.jpeg)

**Comment by sr320** [comment]
@ksil91 @grace-ac 
Do you have thoughts on these circled samples, what they might be and if they should be preserved?

**Comment by ksil91** [comment]
The SS F2 cold shock oysters are the South Sound oysters I exposed to 0degC for 24 hours in November 2015. They observed no noticeable mortality after that event. I believe Laura is using the non-cold shocked ones in her experiment. I have no need for them, but they are a nice F2 resource if we think we'd want that for epigentics/BS seq down the line. 

I think the 2015 oyster tiles are mine (but don't know what AP means). They would also be F2 oysters, but probably at most ~30 per population. I wouldn't use those to spawn or to compare epigenetics to the F1s (because they are on tiles), so they probably aren't useful. 

I don't know what Jake's seed oysters are.

**Comment by laurahspencer** [comment]
Could not find anything marked with tags 78 or 80 hanging off the Manchester dock; is it possible that these were the oysters I used in my Oly project?
