### ISSUE TITLE
Plot CpG o/e distribution density of eastern oyster samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#620]
Plot distribution of oyster CpG O/E similar to Jay's paper

![img](http://gannet.fish.washington.edu/seashell/snaps/Germline_DNA_methylation_in_reef_corals_patterns_and_potential_roles_in_response_to_environmental_change_-_Dimond_-_2016_-_Mol_2019-03-19_09-31-00.png)

https://onlinelibrary.wiley.com/doi/abs/10.1111/mec.13414

Here is the oyster data.
http://gannet.fish.washington.edu/Atumefaciens/20190225_cpg_oe/ID_CpG_labelled_all

You can just pick one column, any column.

**Comment by kaitlynrm** [comment]
`library(mixtools)`
`data <- cpg$CL_1`
`CL1_data <- data[data >= 0.001 & data <= 1.5] #Cutting off high and low values`
`set.seed(101)`
`CL1_mixmdl <- normalmixEM(Spist_data) #92 iterations`
`plot(CL1_mixmdl, which = 2, col2 = c("red", "blue"), xlab2 = " ", main2 = "CL_1", font.main = 3)`
`lines(density(CL1_data), lty=2, lwd=2)`

![CL1_CpG](https://user-images.githubusercontent.com/26392677/54635644-e82b6b00-4a41-11e9-8595-486e5b8a1862.jpeg)

**Comment by sr320** [comment]
Very nice!
Can you create a multi-plot with all 91?

**Comment by kaitlynrm** [comment]
I will try!

**Comment by sr320** [comment]
or if you can get means on the low and high components for all samples.
That would be useful

**Comment by kaitlynrm** [comment]
I faceted all 90 plots, but it's not legible:
![faceted_cpg](https://user-images.githubusercontent.com/26392677/54642600-43fdf000-4a52-11e9-8a36-d647cbe071aa.jpeg)

Here is an example of fewer plots:
![qplots](https://user-images.githubusercontent.com/26392677/54642631-5546fc80-4a52-11e9-836c-5d25270843c0.JPG)

I can make multiple plots so the graphs within them are larger. I will try to look into the components as well- the low component is red and the high component is blue correct?

**Comment by sr320** [comment]
Awesome! - yep if you could get mean on red and mean on blue for each one that might be interesting

**Comment by kubu4** [comment]
Looking good, but something seems off to me and I think @kaitlynrm and I may have touched upon it doing some early troubleshooting:

- There's probably a very small range of data in each set, but I'm concerned the individual plots are actually the same data.

- The first plot you made (as well as the ones Jay made) have some variation in the dashed line compared to the blue/red lines. The faceted plots, however, the dashed line matches up _exactly_ with the blue/red lines. Maybe this a "compression" effect from faceting the plots, making it difficult to see the actual separation between the the line overlays?


I feel like this is a potential problem in looping over the data that we may have missed. For confirmation, maybe add a print() statement to your loop and print the mean cpg each time through the loop. and just look at console output and make sure they're different for each loop cycle. Maybe test out on just a couple of columns first and see how things look?

**Comment by sr320** [comment]
ithere is a difference Jay’s different species where is Kaitlyn is doing a single species

**Comment by kubu4** [comment]
Yep. The "comparison" to Jay's also included @kaitlynrm's first example plot of just a single data set. The dashed line is separate from the blue/red lines. However, in the faceted plots, the dashed line matches _exactly_ the blue/red lines.

**Comment by kaitlynrm** [comment]
I included a `print(mean())` function in the loop. Here is the final code if you are curious @kubu4:

`colname.list <- colnames(cpg)`
`d <- par(mfrow = c(10, 9)) # r x c plot`

`for(i in 2:length(colname.list)){
data <- cpg[[i]]
filt.data <- data[data >= 0.001 & data <= 1.5] #Cutting off high and low values
set.seed(101)
mixmdl <- normalmixEM(filt.data, k=2)
plot(mixmdl, which = 2, col2 = c("red", "blue"), xlab2 = " ", main2 = colname.list[[1]][i], font.main = 3)
lines(density(filt.data), lty=2, lwd=2)
print(mean(cpg[[i]]))
}`

The means are very similar, but still different. 
![mean_cpg](https://user-images.githubusercontent.com/26392677/54649360-1d967f80-4a67-11e9-9f88-6921a7853c06.JPG)

Also, without the print command, I can see that the iterations for the mix model function change each time.

**Comment by kaitlynrm** [comment]
I checked the means individually by column (the first three) and they match.
![confirmation](https://user-images.githubusercontent.com/26392677/54649504-ba591d00-4a67-11e9-8cfd-9b2357917b2e.JPG)

The visual changes in lines must just be because they get pushed together when faceting multiple graphs onto a plot.

**Comment by sr320** [comment]
Can you produce a table with means and sample IDs?

**Comment by kaitlynrm** [comment]
Here are the Q-Q plots of all of the populations on separate graphs.
![popmeans-qq-faceted](https://user-images.githubusercontent.com/26392677/55014742-c0d81f00-4fa8-11e9-89e7-d556fa706162.jpeg)

I plotted each curve right over the top of the other curve and got the plot below. Even without changes in color based on the population, there is no major shifts occurring between  the populations since there are no  other lines visible. 
![popmeans-qq-same](https://user-images.githubusercontent.com/26392677/55014944-24624c80-4fa9-11e9-8aab-4579e9dcc800.jpeg)

**Comment by kaitlynrm** [comment]
I plotted Q-Q plots on top of each other (like above) and in faceted plots in order to identify if there are any differences in the distribution of CpG O/E values in the lists provided in #623. 

## Osmotic Stress (List 1)
![list1-qq-same](https://user-images.githubusercontent.com/26392677/55111102-d3308680-5096-11e9-9063-69b4e759d813.jpeg)
![list1-qq-faceted](https://user-images.githubusercontent.com/26392677/55111111-d592e080-5096-11e9-815f-09d644c4e06d.jpeg)

## Temperature Stress (List 2)
![list2-qq-same](https://user-images.githubusercontent.com/26392677/55111120-dc215800-5096-11e9-9266-e95b6a41d162.jpeg)
![list2-qq-faceted](https://user-images.githubusercontent.com/26392677/55111124-de83b200-5096-11e9-8982-f37c580be086.jpeg)

## Immune Response (List 3)
![list3-qq-same](https://user-images.githubusercontent.com/26392677/55111138-e7748380-5096-11e9-82da-74228a40375c.jpeg)
![list3-qq-faceted](https://user-images.githubusercontent.com/26392677/55111140-e93e4700-5096-11e9-8d42-852c3626816a.jpeg)
