### ISSUE TITLE
Develop canonical bismark script

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#665]
Here is at start 
https://github.com/RobertsLab/code/blob/master/20-bismark.sh

**Comment by kubu4** [comment]
What's the leading "20" mean in the script name?

**Comment by sr320** [comment]
No meaning - numbering system is easy way to organize repo and refer to in slang.

thanks
Steven

**Comment by kubu4** [comment]
Haven't tested yet to verify funcationality, but I've updated the script to do the following:

1. Require user to edit script and provide the following. The script will exit with error message explaining if one of the following has not been set.
  - path to sequencing reads
  - path to bisulfite genome
  - indicate if Bismark should run deduplication (yes for whole genome, no for reduced representation i.e. RRBS/MBD)

2. Create a text file that lists all input fastq files used. Used as a check for paired-end/single-end. Also, it's easier to look this log rather than scroll through Bismark output.

3. Check if run will be using paired-end or single-end reads.

4. Concatenate R1 and, if present, R2 reads (e.g. all_R1.fq.gz and all_R2.fq.gz

5. If/else to handle if paired-end or single-end when concatenating and running Bismark.

6. If/else to handle if deduplication is needed.

To do:

- Create check for paired-end files to make sure each R1 FastQ has an R2 FastQ. The fastest check is to just count total number of FastQs and make sure it's evenly divisible by 2. I'll probably just do this.

- Test the script on some files to make sure it actually executes and executes correctly when presented with the various options.

**Comment by kubu4** [comment]
- Removed concatenation of reads. Don't know why I did this initially...

- Added step to determine if there are equal amount of R1 and R2 FastQ files.

**Comment by kubu4** [comment]
OK, the script is essentially finished. I've tested it to make sure it can at least handle SE/PE reads and deduplication. 

Please test it out!

The script requires the user to enter some info near the header:

- path bisulfite genome directory
- path to fastq location
- whether or not deduplication is desired

The script will then determine if you're using single end or paired end reads and then off it goes! 

Things that might be worthwhile adding:

- a way to easily set bowtie2 alignment settings (i.e. stringency); currently uses default values
- a way to set subsets easily (and, if no subset is set, then do full set of reads)
- an option for selecting whether or not to concatenate fastqs before runnning
- an option to set whether or not reads are directional/non-directional (default is the latter)

**Comment by kubu4** [comment]
Added subsetting option.

**Comment by sr320** [comment]
While it of course can still be tweaked - I am going to call it as "developed"!
