### ISSUE TITLE
Extracting a set of Fasta sequences based on a .txt list

### ISSUE THREAD

**Issue by Jeremyfishb** [RobertsLab/resources#682]
I'm trying to extract a subset of significantly expressed protein sequences from a fasta file so that I can blast just that subset. I am using Gitbash on Windows. I formatted the fasta file so that the sequences are all on one line below the identifier (and other info) and now I can extract one file at a time using grep, like this:

`grep -A1 "sequence_ID" proteinsequences.fasta > newfile.fasta`

where A1 makes it return the lines with the identifier and sequence.

But I can't get it to work when I use a .txt file with a list of the IDs. From what I can find on the internet, the code should be something like this:

`grep -A1 -wf list_of_IDs.txt proteinsequences.fasta > newfile.fasta`

where w forces pattern to match only whole words and f gets the patterns from a file.

When I run that code nothing happens and I get an empty .txt file. 

Could there be a problem with my text file, my code, or the fact that I'm using Gitbash on Windows?

Here's a [link](https://github.com/Jeremyfishb/Jeremy-coral/blob/master/data/Bsigprots.txt) to the text file with the list of IDs of interest. The fasta file is too large for Github.

Thanks for any help!

**Comment by kubu4** [comment]
In the grand scheme of things, I think the easiest way to do this is to use a specialized tool: samtools.

In Git Bash, run the following commands.

1. Change to your desired directory and download samtools:
- `wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2`

2. Then untar/bzip samtools:
- `tar xjf samtools-1.9.tar.bz2`

3. Use samtools to create an index of your FastA file:

- `samtools faidx proteinsequences.fasta`

4. Use while loop, samtools, and your list of IDs to create new FastA:

- `while read contig;
    do samtools faidx proteinsequences.fasta ${contig} >> selection.fasta;
done < list_of_IDs.txt`

**Comment by kubu4** [comment]
Alternatively, if you want to stick with `grep`, you can use modify the while loop in my previous solution to look like this:

`while read contig; do grep -A1 ${contig} proteinsequences.fasta >> selection.fasta; done < list_of_IDs.txt`

**Comment by kubu4** [comment]
Also, it would be great if you could upload a subset of your FastA for us to use for testing with your list. Do something like this to get a subset:

`head -n 50 proteinsequences.fasta > first_25_proteinsequences.fasta`

**Comment by Jeremyfishb** [comment]
Thank you for the responses. I tried both of your methods Sam, to no avail. After downloading and unzipping Samtools I tried to run the next line of code but it's saying "samtools command not found". I tried this in both GItbash and Ubuntu, deleting the Samtools files in-between. I also checked that the Samtools files were there in Windows, they are.

The Ids match exactly, I can use grep to find individual sequences if I copy and paste an ID from the text file into gitbash.

I just put a subset version of the fasta file [here](https://github.com/Jeremyfishb/Jeremy-coral/blob/master/data/first_25_proteinsequences.fasta), and a test.txt file with 5 IDs that are in that subset fasta file [here](https://github.com/Jeremyfishb/Jeremy-coral/blob/master/data/test.txt)

Thanks so much for your help with this!

**Comment by kubu4** [comment]
To clarify on the samtools usage, you have to do one of the following in order to use it:

- add the samtools directory to your system $PATH

- change to the samtools directory and run the program from there, like this:

`./samtools faidx samtools faidx proteinsequences.fasta`

- use the path to samtools to run it, like this (this examples assumes samotols directory is in your home directory):

`~/samtools-1.9/samtools faidx proteinsequences.fasta`

Then, follow up with that while loop using whichever method you used to run samtools above in your loop.

**Comment by kubu4** [comment]
I've tested out all of the possible solutions and they all work, including your original `grep` command (see below)!

![20190423_002](https://user-images.githubusercontent.com/4514104/56616884-4dd7bd80-65d3-11e9-82eb-967818937398.png)

**Comment by Jeremyfishb** [comment]
Great, now if I only they would work on my computer... I just tried your options 2 and 3 but it still wouldn't work. I can't remember how to add samtools to my system path. Do you think the issues I'm having have to do with Windows?

**Comment by kubu4** [comment]
Shouldn't be a Windows issue (particularly if you ran this in Ubuntu). Can you please post screenshots and/or post error messages when you run the commands and they fail? That will be immensely helpful. It would also help if you could post your directory structure of where your various files/programs live on your computer.

**Comment by sr320** [comment]
>I'm trying to extract a subset of significantly expressed protein sequences from a fasta file so that I can blast just that subset.

My suggestion- blast it all. I will presume you will eventually need info on all- and this would be quicker ATC.

That being said - the skill sets mentioned here are valuable.

**Comment by Jeremyfishb** [comment]
Well, when I just use grep, it doesn't do anything, it either makes an empty file if I specify that it should go into a new file, or the command line is just blank.

I loaded samtools into the directory with the data of interest, and used option 2, and this is what I get (using Ubuntu):
![image](https://user-images.githubusercontent.com/43756452/56617826-b2941780-65d5-11e9-969d-2f182d342481.png)

My Ubuntu directory structure is really weird, it took me a really long time to figure out how to get anywhere on my computer. It's like the top of the directory is above the absolute path starting at drive C. To get to where my data is I have to type this:
`cd /mnt/c/Users/jeremy axworthy/Documents/GitHub/Jeremy-coral/data`

Before that, it says I am here: /home/jeremyfishb

**Comment by Jeremyfishb** [comment]
We just want to blast a couple subsets because they are about 130 and 30 sequences whereas the whole proteome is around 25000. Plus we want to let blast make us some figures based only on significant proteins..

**Comment by kubu4** [comment]
> I loaded samtools into the directory with the data of interest, and used option 2, and this is what I get

The error message is telling you what you need to know: samtools isn't located in that directory. 

Is it possible that samtools is in the following directory?

`/mnt/c/Users/jeremy axworthy/Documents/GitHub/Jeremy-coral/data/samtools-1.9/`

---

> To get to where my data is I have to type this:
`cd /mnt/c/Users/jeremy axworthy/Documents/GitHub/Jeremy-coral/data`

Yeah, this can be confusing. The reason for this is that the Ubuntu operating system has to "mount" (i.e. load) your Windows file system in order to access it. As such, your Windows file system gets loaded into the `/mnt/c/` directory in Ubuntu.

To add to the confusion, Ubuntu has it's own home directory, which, as you've discovered, is here: `/home/jeremyfishb`.

It's not _as confusing_ if you try to think of Ubuntu and Windows being two separate computers (which, they sort of are). Even though you are running them both on a single machine, they behave as if they were two different computers.

**Comment by kubu4** [comment]
I think the following will help figure things out.

1. Change to the `samtools-1.9/` directory.
2. Type: `pwd`
3. Post the results here.
4. Change to the directory with your FastA file.
5. Type: `pwd`
6. Post the results here.
7. Change to the directory with your list file.
8. Type: `pwd`
9. Post the results here.

**Comment by Jeremyfishb** [comment]
Thanks Sam, that makes things make a little more sense. As for samtools, there is a directory `samtools-1.9` but when I type samtools while in that directory it still says:
![image](https://user-images.githubusercontent.com/43756452/56622075-88495680-65e3-11e9-96c5-b06140b45516.png)

So then I looked in `samtools-1.9` and didn't see a `samtools`but saw a `samtools1`, so I typed that and it said:
![image](https://user-images.githubusercontent.com/43756452/56622121-c777a780-65e3-11e9-9a15-d8d2283e62a0.png)
What does "deb" mean?

And here are the answers to 3, 6 and 9 above:
samtools-1.9/ is here `/mnt/c/Users/jeremy axworthy/Documents/GitHub/Jeremy-coral/data/samtools-1.9`

The Fasta and list files are both here `/mnt/c/Users/jeremy axworthy/Documents/GitHub/Jeremy-coral/data`

Thanks again!

**Comment by kubu4** [comment]
Doh! Sorry! I didn't realize that samtools needed to be compiled; thought it was ready to go after downloading/untarring.

It's annoying to install and will take awhile. I'd stick with the grep code, but here's how to install samtools (I tested this on Ubuntu on Windows):

Before you proceed, I'd recommend moving the samtools-1.9 directory somewhere else. Currently, based on your naming structure, it looks like it's in a git repo. This is probably a bad idea. I'd create a programs folder (e.g. `mkdir /mnt/c/Users/jeremy axworthy/programs/`) and then move the folder there (e.g. `mv /mnt/c/Users/jeremy axworthy/Documents/GitHub/Jeremy-coral/data/samtools-1.9 /mnt/c/Users/jeremy axworthy/programs/`)

1. `sudo apt update`

2. `sudo apt upgrade`

3. `sudo apt install libncurses5-dev`

4. `sudo apt install zlib1g-dev`

5. `sudo apt install libbz2-dev`

6. `sudo apt install liblzma-dev`

7. cd to samtools-1.9/ directory

8. `./configure`

9. `make -j 8`

10. `make install`

11. `sudo make -j 8 install`

12. `which samtools` : This should return the path where samtools is installed (`/usr/local/bin/samtools`)

Then you're ready to roll! You can use the `samtools faidx` command from anywhere and don't need any funky dots or slashes to get it run.

---

Now, the grep code should work (tested on Ubuntu on Windows with your test files and had no problems). This should be the fastest way to get what you want. If it's not working can you please do the following:

1. `ls -l /mnt/c/Users/jeremy axworthy/Documents/GitHub/Jeremy-coral/data` and provide screenshot of output.

2. `cd /mnt/c/Users/jeremy axworthy/Documents/GitHub/Jeremy-coral/data`

3. `head list_of_IDs.txt` and provide a screenshot of output.

4. `head proteinsequences.fasta` and provide a screenshot of output.

5. `grep -A1 -wf list_of_IDs.txt proteinsequences.fasta | head` and provide screenshot of output.

**Comment by Jeremyfishb** [comment]
No worries and good morning! If we can't get grep to work, I will try to get samtools installed properly.. For now, the grep code still will not work, for the real data or the test data. Here's a bunch of screenshots as requested (for the test data):
1. 
![image](https://user-images.githubusercontent.com/43756452/56672878-08b39a00-666c-11e9-8741-995182aa7598.png)

3. 
![image](https://user-images.githubusercontent.com/43756452/56673101-85df0f00-666c-11e9-9c7a-1dc3a699fbf5.png)

4.
![image](https://user-images.githubusercontent.com/43756452/56673005-53351680-666c-11e9-9245-dff505aa51ca.png)

5. 
![image](https://user-images.githubusercontent.com/43756452/56673217-b757da80-666c-11e9-9924-f938ed6f2269.png)

**Comment by sr320** [comment]
If you would have started blast when you posted this issue yesterday …. You would be done by now :)

**Comment by kubu4** [comment]
This will sound strange, but download your `test.txt` from GitHub and try your grep command again. Download:

`wget https://github.com/Jeremyfishb/Jeremy-coral/blob/master/data/test.txt`

The reasoning is based on this [stackexchange.com problem](https://unix.stackexchange.com/questions/418120/grep-returning-blank-lines-when-using-rnw-instead-of-rlw).

I noticed that your grep output is an empty line. If grep _doesn't_ find any matches, there's no output and you should just get another command prompt. As such, that empty line below your grep command suggests that you are _actually_ getting a match. 

This suggested that something weird was going on. And, since you're using Windows, I suspect that it's a line ending problem. How did you create your `test.txt` file (i.e. did you use a text editor or the command line)? If a text editor, which one? If command line, which one (Git Bash or Ubuntu)?

If you used a "fancy" program to create the text file (e.g. Microsoft Word), then it's likely that the program inserted Windows-style line endings. Alternatively, if your Git Bash initial install was done "improperly", you could end up with Windows-style line endings. These endings will lead to the grep "result" you're experiencing (based on that stackexchange problem).

To add to the complexity, I believe that git can automatically convert different styles of line endings, depending on your settings.

Anyway, we know that the `test.txt` you uploaded to GitHub works, as I've used it on a native Ubuntu system, as well as an Ubuntu on Windows set up without issue. The main difference being that I downloaded the file from that GitHub link, but you're using a local copy of that file.

So, I say give it a shot and see what happens...

**Comment by Jeremyfishb** [comment]
Got it!!! It was a line ending problem. I tried downloading the .txt files from Github, ran the grep command and thought it was working, but somehow the .txt files came back really weird, like they were written in code, like this:
![image](https://user-images.githubusercontent.com/43756452/56690704-f6008b80-6692-11e9-9316-304e9f457d9f.png)
Oddly, this produces an identical fasta file to the one I was searching, all 25000 or so sequences.

So I followed your link to the stack exchange topic which led me to this [website](http://wiki.secondlife.com/wiki/How_to_avoid_DOS_line_endings_in_Windows_tools) where I found out how to convert my text file to Unix friendly line endings. 

This is what you need to do in notepad++ `Edit > EOL Conversion > UNIX Format`, that's all!

Then it worked! My god, what a pain... but I'm happy now.

Thanks so much for your help!!!

**Comment by kubu4** [comment]
Sorry for the bunk link on the downloads! That's my bad. Was working/thinking too quickly and forgot that I needed to use the "Raw" button to get the link directly to the file, instead of the GitHub HTML version of the file.

As an aside, it would probably be a good idea to install samtools anyway. It has a TON of useful stuff in there for manipulating sequence data files.

Anyway, nice work on figuring it out!
