### ISSUE TITLE
Annotate Acropora genome

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#715]
Supposedly the GFF at https://www.ncbi.nlm.nih.gov/genome/?term=txid70779%5bOrganism:noexp

is broken. 

When Mox (or GenSas?)  is available it would nice to get an annoation going

**Comment by kubu4** [comment]
GFF is definitely jacked.

Putting this here to find more easily - link to genome FastA file: 
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/222/465/GCA_000222465.2_Adig_1.1/GCA_000222465.2_Adig_1.1_genomic.fna.gz

**Comment by kubu4** [comment]
Turns out, a GFF can be downloaded from that page you linked above, and, more importantly, that GFF is good!

![image](https://user-images.githubusercontent.com/4514104/65062720-7f11ab00-d931-11e9-8cb0-07f5a8403ffe.png)

**Comment by sr320** [comment]
The coral people say it is not good / accurate. I can inquire why they say that.

**Comment by sr320** [comment]
feedback:

>I couldn’t find transposable elements for example. The original publication is from 2011, and although there is a more recent assembly on NCBI, there isn’t a publication linked to it. In addition, the GFF file on NCBI is broken and the authors do not respond to requests to provide an updated file.

**Comment by kubu4** [comment]
In regards to broken link, they're correct if they use that FTP link I posted above. However, if you use the link that's on the page (from the screenshot), it's a proper GFF.

Transposable elements are not present in the GFF. This seems to be standard procedure (based on our experience with MAKER and GenSAS), so it's not surprising. TE's can be found in the RepeatMaker output file:

ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/222/465/GCA_000222465.2_Adig_1.1/GCA_000222465.2_Adig_1.1_rm.out.gz

**Comment by kubu4** [comment]
Note, the RepeatMasker output file is _not_ a GFF, but has all the necessary coordinates needed.

**Comment by sr320** [comment]
I was reading "broken" as inaccurate, not literally broken link. I will inquire.

**Comment by kubu4** [comment]
To summarize my "findings":

1. GFF from this directory is broken (i.e. has a file, but file is screwed up): ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/222/465/GCA_000222465.2_Adig_1.1/

2. GFF from screenshot is good:

ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/222/465/GCF_000222465.1_Adig_1.1/GCF_000222465.1_Adig_1.1_genomic.gff.gz

3. Transposable elements are in this file: 

ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/222/465/GCF_000222465.1_Adig_1.1/GCF_000222465.1_Adig_1.1_rm.out.gz

I haven't taken the time to try to figure out the difference between "GCA" and "GCF" versions. However, the `assembly_status.txt` file in ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/222/465/GCF_000222465.1_Adig_1.1/ has an updated time stamp of 9/16/2019 and indicates this is the "latest" assembly. Additionally, the fact that the links on the genome info page link to the "GCF" versions of files, suggests that these are the canonical files for this. So, I'd use them instead of the "GCA" versions.
