### ISSUE TITLE
PhiX addition to bisulfite sequencing

### ISSUE THREAD

**Issue by jarcasariego** [RobertsLab/resources#753]
Hi All, 

I was wondering if you can help me make a decision here. The sequencing core is asking me if I would like to add a balanced sample (PhiX) spike to my Bisulfite sequencing. I commented this with Sam and he say it will be fine not including it but later I was reading around and found very contradictory opinions. My main concern with this is that it might reduce the sequencing depth of my already crowded lanes. What do you think? It is worth to include it in detriment of the depth? 

Thanks for giving me access to this great resource.

Cheers, 

Javi

**Comment by sr320** [comment]
I would go with what the core recommends and adding phage DNA so you can calculate conversion efficiency. @hputnam what do you think / do?

**Comment by hputnam** [comment]
Genewiz says: For most bisulfite library sequencing projects, GENEWIZ recommends spiking in 10-20% phiX. I did this for my recent MBD-BS, but don't have the data back yet to see what coverage I may have "lost" due to the spike.  It seems the benefits of knowing you have a good run overall because of including the spike in exceeds the risk of not including it. You could calculate the potential coverage loss to your samples given the % spike and see if you are concerned about the coverage of your samples.

https://support.illumina.com/content/dam/illumina-marketing/documents/products/technotes/hiseq-phix-control-v3-technical-note.pdf

**Comment by hputnam** [comment]
@sr320 I also add a unmethylated phage DNA (5ng of phage DNA for every 100ng of sample DNA)  to the library prep before bisulfite conversion. This can then be used to calculate bisulfite conversion efficiency for all the samples.

**Comment by sr320** [comment]
Sorry I mixed up phiX - with adding in phage DNA. I was not even aware of what phiX was used for.

**Comment by jarcasariego** [comment]
@sr320 and @hputnam. Thank you both for the input. I will go and include the PhiX spike. Do you think 10% will be enough? Since my libraries are MBD enriched, the imbalance should be more dramatic than with regular WGBS, right? Should I use more than 10% then? About the phage DNA, I already completed the library prep so I will have to go without it in almost all my samples (I think I might have enough to prepare one more with the phage if you think could make things better). How will that impact my results?

**Comment by sr320** [comment]
@kubu4 what are your thoughts on the PhiX spike? My presumption is this would be something the core just does.. or do they ask you when jobs are submitted?

**Comment by kubu4** [comment]
For us, since we're usually just submit DNA to them and the facility performs all the necessary library prep, sequencing, and quality control (presumably the proper PhiX spike to ensure sequencing worked properly). Additionally, we have stuff sequenced based on the desired number of reads, so the core facility does the calculations to determine how many flow cells, sequencer runs, PhiX proportion, etc. to generate the desired output.

**Comment by hputnam** [comment]
@jarcasariego If you only have one library left, no need to do lambda phage for conversion efficiency. What you potentially miss if you don't use it is the ability to determine if you have differential conversion in your library prep.  The Liew et al paper argued their way around this as follows: "Lambda DNA, which can be spiked-in to estimate the combined nonconversion and mis-sequencing rate during the bisulfite treatments, was not used in our sequencing runs. However, as we observed that the rates of non-CpG methylation (CHG and CHH, where H = non-G base) were at 0.1% in all samples (data S1), the combination of noncon- version and mis-sequencing would be—at worst—0.1%, if we assumed that CHG and CHH methylation does not occur in S. pistillata."

**Comment by jarcasariego** [comment]
Hi all. Thanks for the advice. I will talk with the core people and include the PhiX. I'll keep you in the loop when the results are back. I really appreciate the support. Cheers
