### ISSUE TITLE
Figure out Scaffold 1 missing TE

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#788]

**Comment by kubu4** [comment]
So, this is what's happening. The final "merged" GFF that gets generated by GenSAS produces a singular GFF that _should_ contain all the genome features/annotations. However, despite individual GFFs from RepeatMasker and RepeatModeler (via GenSAS) that include Scaffold 1 repeats data, Scaffold 1 repeats data does _not_ get included in the final merged GFF. All other scaffold's repeats data is represented.

I'm testing some quick things out on GenSAS to see if I can fix the issue. Otherwise, we can just use the separate RepeatModeler GFF for repeats info for all scaffolds. I'll also contact GenSAS if I can't figure out why the merged GFF is lacking this info.

**Comment by kubu4** [comment]
Ended up contacting GenSAS and they identified a bug that caused this!

Will re-run parsing/stats/renaming and update manuscript.
