### ISSUE TITLE
Explanation for poor sea lice BS mapping

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#821]
Recently I ran Bismark on the sea lice raw data

```
# Directories and programs
bismark_dir="/gscratch/srlab/programs/Bismark-0.21.0"
bowtie2_dir="/gscratch/srlab/programs/bowtie2-2.3.4.1-linux-x86_64/"
samtools="/gscratch/srlab/programs/samtools-1.9/samtools"
reads_dir="/gscratch/srlab/sr320/data/caligus/reads/raw/"
genome_folder="/gscratch/srlab/sr320/data/caligus/genome/"

source /gscratch/srlab/programs/scripts/paths.sh


find ${reads_dir}*_R1_* \
| xargs basename -s _R1_001.fastq.gz | xargs -I{} ${bismark_dir}/bismark \
--path_to_bowtie ${bowtie2_dir} \
-genome ${genome_folder} \
-p 4 \
-score_min L,0,-0.6 \
-1 ${reads_dir}{}_R1_001.fastq.gz \
-2 ${reads_dir}{}_R2_001.fastq.gz
```
and seem to be getting poor mapping efficiency

```
Sealice_F2_S22_L001_R1_001_bismark_bt2_PE_report.txt:Mapping efficiency:	5.9% 
Sealice_F1_S20_L001_R1_001_bismark_bt2_PE_report.txt:Mapping efficiency:	9.0% 
Sealice_F1_S20_L002_R1_001_bismark_bt2_PE_report.txt:Mapping efficiency:	8.8% 
Sealice_F2_S22_L002_R1_001_bismark_bt2_PE_report.txt:Mapping efficiency:	5.7% 
```

Any ideas on what might be contributing to this?

**Comment by kubu4** [comment]
Your reads folder is labelled as `raw`. Are these actually raw reads or are they trimmed. If untrimmed, could lead to poor mapping?

**Comment by shellytrigg** [comment]
That's what I was thinking.

Here's an example of trimmed vs. untrimmed fastqc:

UNTRIMMED:
- [Sealice_F2_S22_L001_R1_001_fastqc.html](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190722/Sealice_F2_S22_L001_R1_001_fastqc.html)

TRIMMED:
- [Sealice_F2_S22_L001_R1_001_val_1_fastqc.html](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore/FASTQC/Sealice_F2_S22_L001_R1_001_val_1_fastqc.html)

For more FASTQC comparisons the untrimmed files are [here](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190722/) and trimmed files are [here](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore/FASTQC/) 

In the end I got 28.1% alignment for F1 and 21.7% alignment for F2. Bismark summary [here](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190814_Calig/bismark_summary_report.txt) and report [here](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190814_Calig/bismark_summary_report.html). Mox script [here](https://gannet.fish.washington.edu/metacarcinus/mox_jobs/20190814_BmrkCalig.sh). Slurm file [here](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190814_Calig/slurm-1231400.out)

I'm pretty sure we are using the same [genome](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/GENOMES/Caligus/) but our parameters are slightly different. I used the --dovetail option, which didn't really make a big difference based on analysis [here](https://shellytrigg.github.io/146th-post/) and I used --non-directional because these libraries were not directional (confirmed by 1:1:1:1 alignment ratios for all sequcne pair combinations in [slurm file](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190814_Calig/slurm-1231400.out))

**Comment by sr320** [comment]
@shellytrigg Where can I find the trimmed files?

**Comment by shellytrigg** [comment]
@sr320 they are [here](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore). 

Here are direct links to the trimmed files:

- Sealice F1 S20:

[https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore/Sealice_F1_S20_L001_R1_001_val_1.fq.gz](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore/Sealice_F1_S20_L001_R1_001_val_1.fq.gz)

[https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore/Sealice_F1_S20_L001_R2_001_val_2.fq.gz](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore/Sealice_F1_S20_L001_R2_001_val_2.fq.gz)

[https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore/Sealice_F1_S20_L002_R1_001_val_1.fq.gz](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore/Sealice_F1_S20_L002_R1_001_val_1.fq.gz)

[https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore/Sealice_F1_S20_L002_R2_001_val_2.fq.gz](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore/Sealice_F1_S20_L002_R2_001_val_2.fq.gz)

- Sealice F2 S22

[https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore/Sealice_F2_S22_L001_R1_001_val_1.fq.gz](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore/Sealice_F2_S22_L001_R1_001_val_1.fq.gz)

[https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore/Sealice_F2_S22_L001_R2_001_val_2.fq.gz](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore/Sealice_F2_S22_L001_R2_001_val_2.fq.gz)

[https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore/Sealice_F2_S22_L002_R1_001_val_1.fq.gz](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore/Sealice_F2_S22_L002_R1_001_val_1.fq.gz)

[https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore/Sealice_F2_S22_L002_R2_001_val_2.fq.gz](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190806_TrimGalore/Sealice_F2_S22_L002_R2_001_val_2.fq.gz)

**Comment by sr320** [comment]
https://sr320.github.io/Refreshing-the-Caligus/
