### ISSUE TITLE
Extra geoduck larvae available for eDNA project 

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#828]
Request from Micah Horwith (now with WA Ecology):  

"I am working with Ryan Kelly in SMEA and post-doc Emily Jacobs-Palmer on an eDNA project that involves the quantification of geoduck DNA in field samples. We are hoping to generate standard curves for qPCR using lab samples spiked with actual geoduck larvae. Do you or anyone in the Roberts lab have preserved geoduck larvae on hand? If so, would there be enough larvae for us to borrow some?"

I see a couple entries in our -80 database for geoduck larvae - any that are extra samples?
![image](https://user-images.githubusercontent.com/17264765/72925824-30718480-3d08-11ea-9cd3-a6da226ab317.png)

![image](https://user-images.githubusercontent.com/17264765/72925955-6a428b00-3d08-11ea-8f2d-42d38be050ed.png)

Alternatively, we could put him in touch with the Point Whitney folks.

**Comment by sr320** [comment]
I prefer not to involve PW. If we do something beyond providing old samples, a larger convo should be had.

**Comment by shellytrigg** [comment]
@laurahspencer We have animals from a volitional spawn of low pH (6.8) conditioned broodstock from 1 dpf, 2 dpf, 3 dpf, 4 dpf, 5 dpf, and 7 dpf. We have quadruplicate samples of each time point preserved in glyoxyl and quadruplicate samples of each time point preserved in DNA/RNA shield. Because we have no ambient conditioned broodstock control for these samples, i don't think anyone has plans for them.

**Comment by laurahspencer** [comment]
Thanks @shellytrigg, passing it on to Micah
