### ISSUE TITLE
Validate Yaamini's and Laura's SRM protocols

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#83]

**Comment by grace-ac** [comment]
Yaamini's: stuck at the same spot as last attempt (Step 2d). Link to issue: [here](https://github.com/RobertsLab/project-oyster-oa/issues/8). 

Laura's: issue from last attempt [link here](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/issues/5) is gone. Perhaps because this time I'm actually using Skyline Daily, or maybe Laura addressed the issue. 

    A slight confusion occurred, simply because one step was missing, but I figured it out! Made a new issue - link: [here](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/issues/7) - that addresses it. 

    The .raw files are currently downloading, and it looks like it'll take a while, but looks good so far!

**Comment by kubu4** [comment]
Before we get too far down this path, I think we need to make a decision on how to handle using Skyline vs Skyline Daily. If Skyline Daily is updated automatically, it's going to kill our reproducibility; which is exactly what we're currently attempting to validate.

And, why does Skyline Daily seem to work for some stuff, but not Skyline??

**Comment by sr320** [comment]
I agree but there are bigger issues currently needing resolving with protocols that are irrespective of software...

2nd Q - I believe "fixes" were made to the software, that imagine will be pulled back into stable version.

**Comment by sr320** [comment]
@grace-ac - Yamini has addressed the Step 2d fail by providing a fasta file, so this is can be tried again
