### ISSUE TITLE
Create canonical gene fasta file for Olurida

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#835]

**Comment by kubu4** [comment]
Just an FYI (since we just talked about this), this file _does_ actually have the corresponding FastA sequences after the GFF portion of the file; but with the original contig names...

https://gannet.fish.washington.edu/Atumefaciens/20190709_maker_olur_v081_annotation/Olurida_v081_genome_snap02.all.renamed.putative_function.domain_added.gff

**Comment by kubu4** [comment]
FastA file is here:

- https://owl.fish.washington.edu/halfshell/genomic-databank/Olurida_v081.genes.fasta

FastA index is here:

- https://owl.fish.washington.edu/halfshell/genomic-databank/Olurida_v081.genes.fasta.fai

Jupyter notebook:

- https://github.com/RobertsLab/code/blob/master/notebooks/sam/20200228_swoose_olur_v081_fasta_renaming.ipynb
