### ISSUE TITLE
Determine discrepancy between fastp and trimgalore on RRBS

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#853]
there are some end differences possibly linked to concept of directionality that considerably alters data.

**Comment by kubu4** [comment]
Alternatively, should we even bother? Could just use TrimGalore with the suggested settings, according to Bismark.

I only started using `fastp` because it was:

- faster

- had automatic QC built in (thus, eliminating need to run FastQC before and after trimming)

**Comment by kubu4** [comment]
[Posted an issue to Bismark GitHub in regards to the TrimGalore `--non_directional` option](https://github.com/FelixKrueger/Bismark/issues/319) and go this response:

>Hi @kubu4 ,
>
>The --non_directional setting is meant to be used for non-directional RRBS sequencing only. Non-directional RRBS libraries are indeed very rare, we had to deal with them in 2010/11, but I think someone else dug up a protocol a bit more recently. If your application is RRBS and you would like to know more about this you could probably read the RRBS Guide on the Trim Galore page, and direct further questions to me.
>
>For anything else, including non-directional standard BS-seq libraries, e.g. scBS-seq, Zymo Pico-methyl or scNMT-seq, it is not required to use this options. I hope this helps. Cheers, Felix

**Comment by shellytrigg** [comment]
FYI TrimGalore! can be run with multi-core settings if you use version 0.6.1 or newer. Using 8 cores reduced the run time for 100M reads from ~2hr10min to ~30min. My script implementing TrimGalore with multiple cores is here [20200316_TG_speedTest.sh](https://gannet.fish.washington.edu/metacarcinus/mox_jobs/20200316_TG_speedTest.sh). You can check the time difference between these slurm.out files [multiple cores](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200316/slurm-2268224.out) and [single core](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200306/slurm-2025665.out). The single core slurm.out file was generated by this script: [20200306_TrimGfroger.sh](https://gannet.fish.washington.edu/metacarcinus/mox_jobs/20200306_TrimGfroger.sh).

**Comment by kubu4** [comment]
I know this issue is closed, but I'd also like to point out that the kit used for the RRBS library prep in the [Meth_compare](https://github.com/hputnam/Meth_Compare) project (which is what started this discussion in the first place), indicates exactly how to trim these particular RRBS libraries (non-directional), on [pgs. 6 & 7 of the manual](https://github.com/hputnam/Meth_Compare/blob/master/lab-methods/commercial-protocols/EZ-DNA-Methylation-RRBS%20Library-Prep-Kit.pdf).

**Comment by shellytrigg** [comment]
@kubu4 the trim galore settings outlined that manual are exactly what I used to trim the daa (which is mentioned here https://github.com/hputnam/Meth_Compare/issues/12)

**Comment by kubu4** [comment]
@shellytrigg Yep, I know. I just wanted to point out that we could/should have followed trimming instructions initially and avoided all the fastp/TrimGalore comparisons, had someone pointed out that the proper (i.e. non-directional) trimming info was provided in the manual.

**Comment by shellytrigg** [comment]
@kubu4 100% agreed! A separate issue, I just got some info yesterday from Illumina re: trimming libraries prepared with Illumina Truseq Methylation Kit (all Hollie's RRBS geoduck samples). It turns out those adapters are 25bp (including the 13bp universal illumina adapter sequence + 12 additional bases). I'm about to post a journal entry about it.
