### ISSUE TITLE
Retest reprod. dev. stage geoduck primers w/ water

### ISSUE THREAD

**Issue by kaitlynrm** [RobertsLab/resources#864]
Run NTCs on primer pairs to determine contamination sources and primer viability

**Comment by shellytrigg** [comment]
@kubu4 can you test the following primer pairs on NTC and positive control (cDNA pool)

- RPL5 _FWD + REV
- TIF3s6B_FWD + REV
- APLP_FWD + REV
- NFIP_FWD + REV
- GSK3B_FWD + REV
- SPTN1_FWD + REV

**Comment by kubu4** [comment]
qPCRs complete.

Results summary:

- No template controls (NTCs) did not generate any amplification in any of the primer sets.

- All primer sets generated amplification with both cDNA and gDNA.

- Only two primer sets which produced acceptable cDNA melt curves:

  - APLP

  - NFIP1

---

Notebook entry (with amp/melt plots):

- https://robertslab.github.io/sams-notebook/2020/07/23/qPCR-Testing-P.generosa-Reproduction-related-Primers.html

**Comment by shellytrigg** [comment]
Awesome, that's great both APLP and NFIP1 worked since these are two different reproductive development genes. 

We still need a positive expression control since neither of the two housekeeping genes (RPL5  and TIF3s6B) produced acceptable melting curves. @kubu4 do you think redesigning these primers could improve the melt curves? The full coding sequences are listed here: https://docs.google.com/spreadsheets/d/1vkUQvqNUN-9ntv0NoVDAtD8zA-p9e3xosGwsWSFV0qk/edit#gid=0
