### ISSUE TITLE
dplyr `filter` returns extra rows 

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#868]
I'm trying to subset/filter a dataframe in R using 2 conditions. I usually have good success using `dplyr::filter`, but I'm encountering a weird issue - when I'm filtering my object using 2 conditions I get a few extra rows. If anyone has time to trouble shoot, attached is a folder with an R project, R objects, and my code that needs help: [trouble-shooting.zip](https://github.com/RobertsLab/resources/files/4391205/trouble-shooting.zip). 

Note: I also tried using `subset` (instead of `filter`), and got the same weird result.

**Comment by kubu4** [comment]
One thing I noticed in your subset example is that if you provide a vector of explicit start values from `Pst.100` (e.g. c(115, 1712)), things work as expected and get the two desired rows. Alternatively, if you provide the subsetted chr (e.g. `chr %in% c("Contig16850") and leave the `start %in% c(Pst.100$start)`, you get the the four rows.

So, here's what I think is happening.

Your filter first filters `meth_filter` for any of the 100 contigs in `Pst.100`. This pulls out 1660 rows from `meth_filter`. Then, those 1660 rows are filtered for any values in the `meth_filter$start` that are present in `Pst.100$start`. So, you end up with "extra" rows. But, the code is working the right way.

Reading the code verbally, it's working like this:

Pull out all rows that match provided contig names and all rows that match provided start values. 

Reading it that way, it's a bit more evident that the two conditions are not dependent on each other. You need to rewrite the code so that the rows will only be extracted if both conditions are met.

**Comment by laurahspencer** [comment]
Thanks for the help! Yes, that's exactly what is happening. the `filter(A & B)` _should_ filter a dataframe conditional upon both A _and_ B, but that doesn't seem to be working. I found a work-around: create a new column with A pasted with B ("A_B") in both dataframes, then subset using that new column. 

```
Pst.100 <- perc.meth.Pst.done %>% 
  mutate(Quant_Varia=as.character(Quant_Varia)) %>%
  separate(Quant_Varia, c("contig", "start", "end"), sep = "\\.") %>%
  mutate_at(vars(start, end), funs(as.integer)) %>%
  mutate(contig_start=paste(contig, start, sep="_")) %>%
  top_n(100, Pst_Values)

meth_filter %>% 
  mutate(chr_start=paste(chr, start, sep="_")) %>%
  filter(chr_start %in% c(Pst.100$contig_start))
```

**Comment by laurahspencer** [comment]
An even better solution: 

Because I'm working with MethylKit objects, I want to keep my "meth_filter" as a methylKit object (not an R dataframe or tibble). Therefore, I can use methyKit functions and GRanges to create a list of desired loci: 

```
library(GenomicRanges)
my.win=GRanges(seqnames=Pst.100$contig,
               ranges=IRanges(start=Pst.100$start,width=1))
 
# selects the records that lie inside the regions
selectByOverlap(meth_filter,my.win) %>% getData() %>% View()
```

**Comment by kubu4** [comment]
Very nice! I glanced at the methylkit documentation, but didn't have the brain capacity last night to try to figure it out. Glad that works!

In regards to this:

> the filter(A & B) should filter a dataframe conditional upon both A and B, but that doesn't seem to be working

This _is_ working as it's designed. 

You're filtering `meth_filter` based on a list of contig names provided by `Pst.100`. So, it finds those rows in `meth_filter`. 

Then, you're filtering _that_ subset of `meth_filter` by any rows that also contain any of the `Pst.100$start` values.

I think your subsetting example code is very helpful in thinking about why this works the way it does (and, shows that it is working properly):


```R
subset(meth_filter %>%
filter(chr %in% c(Pst.100$contig) & start %in% c(Pst.100$start)), chr=="Contig16850") #4 loci
```

In your example code above (even though you've subsetted it, I'm just going to talk in terms of "filtering"), you've filtered for all rows with `Contig16850`. This pulls out 42 rows. 

Next, it looks for any of those rows that also have `meth_filter$start` values that match `Pst.100$start` values. As it turns out, there just happen to be `Pst.100$start` values that correspond to 4 of the 42 `Contig16850` `meth_filter$start` values.

So, that's why you get four loci in your example. You can test this out by replacing the `start %in% c(Pst.100$start)` with the start values of the four loci you get in the results:

```R
subset(meth_filter %>%
filter(chr %in% c(Pst.100$contig) & start %in% c(115, 1407, 1712, 1799)), chr=="Contig16850") #4 loci
```

If you look through `Pst.100$start`, you'll see those start values.

Anyway, not sure if that helps explain a bit better of why it's operating the way it's supposed to or not. Figured I'd try!

Finally, at the end of the day, _major_ props for verifying your results were what you expected/did not expect!! Without that step, you could've proceeded and not realized you're analysis was flawed!

**Comment by laurahspencer** [comment]
Precisely - this agonizing trouble shooting revealed that a couple of my other filtering steps were incorrectly pulling extraneous loci, so I'm now rewriting that code to accurately filter.

Moving forward, I'll need to identify a go-to code to subset rows in a dataframe conditional on multiple columns simultaneously, not in sequence.
