### ISSUE TITLE
Cannot push to GitHub from R Server (emu)

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#888]
Mac is having issues with R server.

> I still can't push the R anayses (corr plots) to GitHub.  The plots on the Emu R server, but it just hangs there after I hit 'push' and put in my GitHub credentials

**Comment by kubu4** [comment]
Has she tried from the command line?

**Comment by kubu4** [comment]
Can she pull from the GitHub repo (in the RStudio interface)?

**Comment by sr320** [comment]
@mgavery ?

**Comment by kubu4** [comment]
Also, which Emu user account is she logging into?

**Comment by mgavery** [comment]
srlab is user account

**Comment by kubu4** [comment]
@mgavery - What about my other questions?

**Comment by mgavery** [comment]
I have not tried from the command line

I can pull using the interface

**Comment by kubu4** [comment]
Can you push to the repo from your own computer? Also, which repo are we talking about here?

**Comment by kubu4** [comment]
@mgavery 

I just logged into Emu (both via the command line and via the RStudio Server interface). It looks like you haven't added/committed anything. All of the files listed in the `/home/srlab/GitHub/Meth_Compare` directory are listed as "Untracked" or "Modified".

In order for the files to be pushed, you need to "Add" then "Commit". After that, you should be able to push. I did _not_ try this with any of your files, as I don't know which files you want committed. However, I'd try this first and then try pushing.

**Comment by mgavery** [comment]
can we chat?  I've committed and pushed plenty of stuff ..all the early March stuff was done in that way.  I pull, commit and try to push now and it just hangs.  I gotta talk through this all at once.  Can I call ya?

**Comment by kubu4** [comment]
Yeah, of course.

**Comment by kubu4** [comment]
> all the early March stuff was done in that way.

Which repo? The `Meth_Compare` GitHub repo only shows you committing one file (a `.DS_store` file) from a while ago, and then a merge from today.

**Comment by kubu4** [comment]
This was due to a couple of things:

1. Needed to wait longer. RStudio was actually still pushing (took > 30 mins to finish when troubleshooting with @mgavery ).

2. If we had waited longer, we would've encountered an error anyway, with "the remote hung up unexpectedly". This was probably due to the default buffer size being insufficient. This has been upped to 500MB with the following command: `git config http.postBuffer 524288000`

3. There were a number of commits with files >100MB. This is the file size limit for GitHub. However, the push was terminated before this error was generated.

---

I have resolved the issue by doing the following:

1. Copy the repo in its current state to a different directory on Emu, _excluding_ any "dot" files. These would be the special Git repo files that are used to track all the changes/history/commits/etc. This is important because trying to weed through all of the commits that included large files was too tedious. By excluding the Git files, we don't get stuck with those large files being included in any commits.

`rsync -av --progress --exclude ".*" --relative ./Meth_Compare /home/srlab/Downloads`

2. Delete the actual repo where @mgavery was doing her work:

`sudo rm - ~/Github/Meth_Compare`

3. Clone the Meth_Compare repo from GitHub:

`git clone https://github.com/hputnam/Meth_Compare.git`

4. Copy all of the "old" files to the freshly clone repo:

```shell
cd ~/Downloads
rsync -av --progress --relative ./Meth_Compare /home/srlab/GitHub
```

5. Add all files >99MB to the `.gitignore` file (`sed` command strips leading `./` from file paths):

`find . -size +99M | sed 's|^./||g' >> .gitignore`

6. Add/commit the changes to `.gitignore`

7. Add all untracked/modified files in repo.

8. Commit those changes.

9. Push to GitHub.

Boom! Done!

That was easy! ;)
