### ISSUE TITLE
Katherine's oyster shells and tissues from Manchester

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#89]
I unpacked a small storage container that has some things labeled as @ksil91 's. Keep some? Toss some? Thoughts? 
These are all from Manchester.

![img_4486](https://user-images.githubusercontent.com/14934314/31402892-3c99d304-adac-11e7-89de-cb4ca7837c1a.JPG)

Some tubes that I am guessing just have ethanol in them:
![img_4488](https://user-images.githubusercontent.com/14934314/31402981-963136be-adac-11e7-8fa8-001cb6b43e8b.JPG)

Tubes with oyster mortality tissue samples: 
![img_4490](https://user-images.githubusercontent.com/14934314/31403028-bdbfea18-adac-11e7-8c8a-8e98fb6b3923.JPG)

Some shells in a tri-pour:
![img_4494](https://user-images.githubusercontent.com/14934314/31403066-dcb9f5a8-adac-11e7-8097-c67bfbf54310.JPG)
![img_4493](https://user-images.githubusercontent.com/14934314/31403067-dccb9308-adac-11e7-9411-6f6321636825.JPG)

**Comment by ksil91** [comment]
Ah, I was supposed to take those shells with me and forgot them. I do not have immediate plans, but I thought it might be nice to have in case I wanted to do a population level survey of shell characteristics. Do you have room to stick them in a freezer for now (doesn't have to be -80)? If not, I can pay to have them shipped to me.

The empty tubes were extras from the dissections and either have RNALater or Ethanol. Unless you think you can reuse them, you can toss them.

I suspect the tripour has shells of oysters that died during the OA experiment and are probably not sorted by population. I know that the oyster labelled "72" is from BC, so you could put it in the BC bag of shells, but otherwise you can toss these.

Do the oyster morts in EtOH have any other labeling on them, like date or population? If not, just throw them away. If they do, please send me what the labels are and I'll cross-reference my notes to see if they should be kept in the freezer.

Thanks!

**Comment by grace-ac** [comment]
I can put the bags of shells in the MERLAB along with the bags of shells from Jake's experiment. 
It's a -20. 

I tossed the tubes.

I put the "72" into the BC shell bag. Rest were tossed.

Oyster morts: 
There are six - with the following labels:
- OR 2B, 31, 9/26,mort
- OR 4B, 9/26 mort
- 10-3-16, BC - 1B
- 10-3-16, BC3B, (looks like it says "140" or "Mo" for mort?) 
- 10/6/16, Orange 025, BC-A3
- 11/17/16, White 107, BC B1

**Comment by grace-ac** [comment]
Added the bags to the left -80 and added the information at the bottom of the [-80 Inventory Map](https://docs.google.com/spreadsheets/d/1Qsvz3QTURlPF_hX05BQxjom3484WuMfqQ1ILl9LEljU/edit#gid=2006985773). 

@ksil91 Any thoughts on the oyster morts tubes?

**Comment by ksil91** [comment]
Can you put those in a minus 20 with some labelling like,
 K. Silliman
Olympia oyster OA Experiment Fall 2016
Mortalities

**Comment by grace-ac** [comment]
Of course! 

And for all those clear tubes labeled "M"s and "A"s and "C"s... are those from you as well? They don't have any labeling and have a clear liquid in the bottom. @ksil91

**Comment by ksil91** [comment]
The labelled tubes were extras from the dissections and either have RNALater or Ethanol. Unless you think you can reuse them, you can toss them

**Comment by grace-ac** [comment]
Great, thank you! Everything is taken care of now.
