### ISSUE TITLE
blast output for 2019 crab data exist already? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#905]
Does a BLAST output for the 2019 crab seq data exist already? 

Working to annotate and enrich a list of DEGs

**Comment by sr320** [comment]
Actually you would want an annotation for the transcriptome used....

**Comment by sr320** [comment]
Which is 20200408.C_bairdi.megan.Trinity.fasta

**Comment by sr320** [comment]
This looks to be blast output https://gannet.fish.washington.edu/Atumefaciens/20200408_cbai_diamond_blastx_megan/20200408.C_bairdi.megan.Trinity.blastx.outfmt6

**Comment by kubu4** [comment]
Yes. See my notebook: https://robertslab.github.io/sams-notebook/2020/04/08/Transcriptome-Annotation-C.bairdi-MEGAN-Trinity-Assembly-Using-DIAMOND-BLASTx-on-Mox.html

Also, I've also done the differential gene expression (using an early genome), if you just want all of that, too:

https://robertslab.github.io/sams-notebook/2020/02/07/Gene-Expression-C.bairdi-MEGAN6-with-Trinity-and-EdgeR.html

**Comment by grace-ac** [comment]
thanks :)

**Comment by kubu4** [comment]
Also, to clarify, since I'm not fully sure what's going on here, there are a few things (not sure if/how they impact this analysis):

1. Trimmed reads used for salmon gene abundance included _all_ reads (i.e. hematodinium and crab).

2. Transcriptome used is _only_ crab reads.

Something to keep in mind (maybe)?
