### ISSUE TITLE
Problems pulling MethCompare on Emu R sever

### ISSUE THREAD

**Issue by mgavery** [RobertsLab/resources#917]
![RStudio_-_Meth_Compare](https://user-images.githubusercontent.com/4512578/80264248-5f213300-8648-11ea-8fa9-4dfc892ee85e.png)

**Comment by mgavery** [comment]
I can't update the corr plots I've made on emu.  I'm not familiar with these other files, but should I just stage and commit them to get everything up to date?  .

**Comment by kubu4** [comment]
Address the errors one at a time. Did you commit your changes to the files listed that require commits?

**Comment by mgavery** [comment]
I was allowed to commit the 3 .jpg files that I made, but I can't push them

**Comment by mgavery** [comment]
![RStudio_-_Meth_Compare](https://user-images.githubusercontent.com/4512578/80264367-d060e600-8648-11ea-9747-2fdac457f246.png)

**Comment by kubu4** [comment]
Error indicates you need to pull, so do that.

**Comment by mgavery** [comment]
I can't pull.  That was the first pic I put on this issue

**Comment by kubu4** [comment]
I'm confused now. So, the error message about pulling is what you get after you've made the specified commits??

**Comment by mgavery** [comment]
I pulled, got the error.
I went ahead and committed anyway.
I tried to push and it didn't let me.

**Comment by kubu4** [comment]
OK, looking into this. there's a lot going on here. For example, when I check things with `git status`, this only a _part_ of what is printed:

![image](https://user-images.githubusercontent.com/4514104/80272823-98c26000-8681-11ea-863d-ea22badbf7e8.png)

--- 

![image](https://user-images.githubusercontent.com/4514104/80272861-19815c00-8682-11ea-9277-3e75c124b310.png)

I'm guessing this is all part of why you encountered this problem in the first place: changes to files that haven't been committed/pushed, but there have likely been changes to the remote repository involving some of these files.

I should be able to fix this (I think `git pull --rebase`), but wont be able to tackle it until tomorrow morning.

**Comment by mgavery** [comment]
Thanks for looking into this!

**Comment by kubu4** [comment]
Just updating this. Processing repo now (it's a bit of a rat's nest...) and I think it's going to take awhile. 

The gist of it is that there are large files that have been committed, then additional commits have been made after the large files were committed. Remote commits have also been made since those large files were committed. All of this means that the large files files need to be stripped from the commit history before the `.gitignore` list of those large files will have any affect. 

So, I'm running a command that is going through each file listed in the `.gitignore` and is then going through _each commit_ and looking for those large files in each commit. If those files are discovered in a commit, then they are removed from the commit history.

I'll report back when this is complete and the repo on Emu is functional again.

**Comment by kubu4** [comment]
Well, that was actually pretty quick! The overall process was not. Anyway, here's how it was resolved:

1. Add large files to `.gitignore`

- `find . -size +99M | sed 's|^./||g' >> .gitignore`

2. Remove large files from commit history (via [this GitHub help page](https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository)). I used the list of files in the `.gitignore` file as the source of files for the command:

- `while read -r line; do file="./${line}"; git filter-branch --force --index-filter "git rm --cached --ignore-unmatch ${file}" --prune-empty --tag-name-filter cat -- --all; done < .gitignore`

3. Force push commits:

- `git push origin --force --all`

All good!

With all that being said, here's the _basic_ workflow that should be followed going forward when you (or anyone) starts using a repo on a computer:

1. `git pull`

2. `git add <file>`: Replace file with name of actual file that has been changed. Do _not_ use `git add .` or `git add *`! This will lead to major problems.

3. `git push`

Do this regularly while using the computer. _DEFINITELY_ do this before you take a break and/stop using the computer for even a few minutes.

That should help.

Bigger picture. Since this is a collaborative repo, it would help immensely if everyone involved learned about (and used) branches. This would help minimiz/avoid merge conflicts (which are also a source of headaches and are complicated to resolve).

With all that said, just post an issue if you encounter any other difficulties and I'll be happy to help!

**Comment by sr320** [comment]
The aftermath? :) 
https://d.pr/i/Z1QeTg

**Comment by kubu4** [comment]
Uhhhh....

**Comment by kubu4** [comment]
@sr320 Should we make this into a new issue? You're not going to be the only one with these conflicts. We might want to decide on an approach to address this.
