### ISSUE TITLE
Keep/Toss: Chems and others from Manchester

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#95]
Tubes of Tris:
![tris_tubes](https://user-images.githubusercontent.com/14934314/31511930-2900cf44-af3e-11e7-853d-c37c330dc90f.JPG)

2 tubes of Oly strings:
![stringtube_2](https://user-images.githubusercontent.com/14934314/31511941-32428480-af3e-11e7-8f7e-35e0c5af5bed.JPG)
![string_tube](https://user-images.githubusercontent.com/14934314/31511943-32701c4c-af3e-11e7-81f5-9abfde609b1d.JPG)

Bottles of buffers:
![trisbuffer_21917](https://user-images.githubusercontent.com/14934314/31511967-49fb8a4a-af3e-11e7-80d1-a66f9f433d12.JPG)
![oa_cal_buffer](https://user-images.githubusercontent.com/14934314/31511968-4a0dd16e-af3e-11e7-8098-463db702bea0.JPG)
![trisbuffer_6616](https://user-images.githubusercontent.com/14934314/31511969-4a1ed72a-af3e-11e7-9574-6f29f4705111.JPG)
![phbuffers](https://user-images.githubusercontent.com/14934314/31511976-4e1032de-af3e-11e7-9a90-f51b4346c2ce.JPG)

A small bit of RNAlater:
![rnalater_side](https://user-images.githubusercontent.com/14934314/31511981-53f03d52-af3e-11e7-880d-900549ca7cb3.JPG)
![rnalater](https://user-images.githubusercontent.com/14934314/31511982-541e670e-af3e-11e7-8a29-2f5744fbb61d.JPG)

KCL (I'm pretty positive this is for keeping: where should this be stored?): 
![kcl](https://user-images.githubusercontent.com/14934314/31512000-59632e5c-af3e-11e7-8f46-a45bf381bcee.JPG)

**Comment by laurahspencer** [comment]
Until we iron out the protocol for analyzing water samples via titrator I suggest we keep the individual/dated TRIS samples, since we used them to standardize our pH measurements of water quality.  

I can't speak to the RNALater nor the Potassium chloride solution (likely used by Katherine, Hollie or Dan)

I'll set aside the "Oly string" tubes in case we want to sample them for some reason - those were from stringy stuff found in broodstock conditioning tanks which we determined were caused by the algae paste (Reeds Shellfish Diet).
