### ISSUE TITLE
Help updating sort (GNU coreutils) on Ostrich

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#964]
I'm running some Bismark programs on Ostrich which use `sort`. The version of `sort` (GNU coreutils 5.93) installed on Ostrich is out of date (current version is 8.32), and thus it lacks a key sort option that I need (-V / --version-sort). 

I can't figure out how to update either just the `sort` function, or the whole coreutils package on Ostrich- anyone have ideas, or can help with the install?

**Comment by kubu4** [comment]
Two options.

1. Install "homebrew" and then install the GNU coreutils via that method. This will also require you to create an an alias for `sort` that points to the GNU sort.

2. Use one of the Linux computers (including Mox, which is probably the best choice).

**Comment by kubu4** [comment]
BTW, my recommendation is Option 2 listed above (with particular emphasis on using Mox).

My rational for this is that it keeps things "simple", in that Bismark was written to work on Linux computers, but not for OSX (macOS) computers. Also, it "simplifies" troubleshooting because it's easier to determine which programs are being used. When you start going down the path of creating alias, symlinks, etc. that redirect a "basic" command to somewhere/something else than what's normally expected; fixing problems becomes inherently more difficult.

However, with all of that said, I'm certainly happy to help with Option 1 listed above. Presumably, you have your own user account on Ostrich, so you'll have to do most (all?) of the work to setup homebrew (btw, this is _very_ simple; I think it's a one-line command). If you encounter any issues, just post here and I'll see what advice I can provide!
