### ISSUE TITLE
Low MBD-seq mapping efficiency 

### ISSUE THREAD

**Issue by jarcasariego** [RobertsLab/resources#967]
Hi all, 
Following Yaami's advice I tried several alignment conditions to improve mapping of my MBD reads to the M. cavernosa genome. The mapping efficiency continues to increase and never plateau with reductions of the stringency of the alignment (e.g. L,0,-0.6 = 15.4%; L,0,-0.9 = 19.1%; L,0,-1.2 = 24.26%; L,0,-1.5 = 35.5% & L,0,-1.7 = 50.5%). What do you think about that because the mapping at such loose conditions should produce errors right?
On the other side, I was checking Zymo's advice for processing data resulting from Pico-Methyl lib and they propose to sequentially trim (5-10 based at a time) to 50bp if the libraries were sequenced either by 2x100 or 2x150 (my case). Could this improve mapping? Have you ever tried this? 
Thanks!
Javi

**Comment by shellytrigg** [comment]
Hi Javi,

I definitely recommend trimming as I have seen this can really improve mapping. I follow Bismark's trimming recommendations for libraries prepared with Zymo Pico Methyl kit outlined in the Bismark user manual here: https://rawgit.com/FelixKrueger/Bismark/master/Docs/Bismark_User_Guide.html#ix-notes-about-different-library-types-and-commercial-kits


Below is an example of the trimming I perform on paired end libraries:

#TrimGalore on WGBS and MBD-BS
/gscratch/srlab/programs/TrimGalore-0.4.5/trim_galore \
--output_dir /gscratch/scrubbed/strigg/analyses/20200311/WGBS_MBD \
--paired \
--fastqc_args \
"--outdir /gscratch/scrubbed/strigg/analyses/20200311/WGBS_MBD/FASTQC \
--threads 28" \
--illumina \
--clip_R1 10 \
--clip_R2 10 \
--three_prime_clip_R1 10 \
--three_prime_clip_R2 10 \

As a proxy for judging alignment quality, I consider the %mCHH and %mCHG because we don't expect non-CG methylation in shellfish, and the %mCHH should be similar to the BS conversion error rate from the lambda DNA spike in control. I notice that when I make the mapping score looser, that my %mCHH increases. If I know for instance that my BS conversion efficiency is 99% and my BS conversion error is 1%, then I expect my %mCHH to be 1%. If a looser alignment score threshold gives %mCHH much greater than 1%, I know the alignment score threshold is too loose.

**Comment by sr320** [comment]
Also - is it possible you have symbiont DNA in your  libraries?

**Comment by kubu4** [comment]
> I was checking Zymo's advice for processing data resulting from Pico-Methyl lib and they propose to sequentially trim (5-10 based at a time) to 50bp

That's not how I interpret the their instructions. The [protocol says](https://files.zymoresearch.com/protocols/_d5455_d5456_picomethylseq.pdf):

> Recommended: Treat Pico Methyl-Seq™ libraries as 50 bp single-end reads when mapping back to the
reference genome. Sequentially trimming of the first four bases may increase mapping efficiency.

Admittedly, the phrasing isn't worded clearly/well.

I interpret them in this fashion:

1. When mapping, treat libraries as single-end.

2. Trim the first four bases from each read.

**Comment by sr320** [comment]
@hputnam - you have any insights?

**Comment by jarcasariego** [comment]
Shelly, I used those trimming conditions since they were in Yaami's code that I followed. 

Steven, yes I expect to have symbiont DNA and I actually mapped about 10-20% to S. minutum genome

Sam, I was refering to the Q&A section:
**Should single end or paired end read be performed? Which read length should be set?**
We typically sequence Pico Methyl-Seq libraries with 50 bp reads because trying to align reads that are longer than 50 bp result in lower alignment rates. If you still want to sequence the libraries at 100 bp or 150 bp reads, we suggest to trim the reads down to 50 bp to align, or sequentially 5-10 bp each time to see at what point the alignment goes up. Pico Methyl-Seq generated libraries are TruSeq libraries. The index barcodes are in the protocol and can be used in the sample sheet to upload onto the NextSeq for demultiplexing.

**Comment by jarcasariego** [comment]
@shellytrigg even with the most strict parameters I used (L,0,-0.6), still got around 4% CHH methylation for some samples. Should I try something stricter?

**Comment by sr320** [comment]
Do you know BS error rate?

Also given symbionts-  a mapping rate of 15% would be on par.

**Comment by jarcasariego** [comment]
> Do you know BS error rate? 

No, I don't.

**Comment by jarcasariego** [comment]
>Also given symbionts-  a mapping rate of 15% would be on par

should I go with a stricter alignment parameters then?

**Comment by sr320** [comment]
I would.

**Comment by shellytrigg** [comment]
Javi if you're interested I've looked into PE alignment vs. SE global alignment vs. SE local alignment for PE RRBS salmon libraries I made. Here's my journal post about that: [https://shellytrigg.github.io/310th-post/](https://shellytrigg.github.io/310th-post/). In the end, I ended up going with PE alignment because a lot of the reads I gained from SE were low coverage or were mapping to repetitive regions. I also evaluated alignment score thresholds here: [https://shellytrigg.github.io/315th-post/](https://shellytrigg.github.io/315th-post/) by comparing %mCHH, %mCpG, and % mapping.

**Comment by jarcasariego** [comment]
Thanks @shellytrigg. I'll review it.

**Comment by jarcasariego** [comment]
Hi All, 
I did several analyses to see if I could improve mapping of my reads.  I tested several alignment scores (-0.2.-0.4, -0.9, -1.2, -1.5 and -1.7), trimmings (clipping 10, 15, 20 and 25 bp from both ends) and aligners (bowtie2 and hisat2). I don't see any improvement by changing the aligner or trimming to smaller fragments. The increases in mapping with more relaxed scores, rapidly increase the %CHH and %CHG after -0.9. I was thinking using -0.9, maintaining everything else as in Yaami's code, could be a good compromise. what do you think? Should I try something else?
Thanks!
Javi
Results are attached.    
[20200728_alignment_compare.pdf](https://github.com/RobertsLab/resources/files/4989391/20200728_alignment_compare.pdf)

**Comment by hputnam** [comment]
I would map to the C1 genome (http://symbs.reefgenomics.org/download/) instead of the B genome.
Interested to see what you find!

**Comment by jarcasariego** [comment]
Hey!! Update
Alignment with the C1 genome did not result in higher mapping and there is lost of CHG and CHH methylation. I also tried to do SE alignment and the improvement is minimum (about 1%). I emailed Zymo and they proposed this: 
"Run the alignment of the samples to the reference genome using the full length reads but also let the program generate a new fastq file containing the unaligned reads (the option is --un). Then the unaligned reads are trimmed from the 3’ end to a shorter fragment (less than 100 bp, even to 50 bp) and the alignment is run again. This way you will have two sets of bamfiles, first for read 1 and read 2 of the full length reads and then a second set for read 1 and read 2 for the trimmed files. You can combine these files together, you should see more reads that are aligned. 50 bp should be the limit to where the reads should be trimmed to. When the fastq files are trimmed, you should trim both the sequence (line 2) and quality (line 4) to the same length."
What do you think? 
I'm giving it a try using L,0,-0.9 and trimming the unmapped fragments with clip 30, 40 and 50 (result in frags of 90, 70 and 50 bp respectively).
Javi

**Comment by jarcasariego** [comment]
I completed the realignment of the unmapped reads after clipping 30, 50, 70 and 90 based from 3', and hard trimming to 50 bp. All cases had very low efficiency (~2%) and with high percentages of CHH and CHG methylation. In Conclusion, none of the options I have tried increase the mapping efficiency. If any of you have another idea I should try, please let me know. If not, I'll move on with the analysis using the results of the L,0,-09 alignment that yields 20%-50% mapping.
