### ISSUE TITLE
Identifying samples to reshear

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#983]
@kubu4 I ran [*C. virginica* samples I resheared]() on the BioAnalyzer. Based on the electropherogram and gel below, I am going to reshear samples 6 and 63. I am unsure about 12. Do you recommend shearing it more?

![Capture](https://user-images.githubusercontent.com/22335838/89451482-2564cb80-d711-11ea-939c-16e7e7d1c592.PNG)
![Capture2](https://user-images.githubusercontent.com/22335838/89451485-25fd6200-d711-11ea-9691-19b6ee2a02a3.PNG)

**Comment by kubu4** [comment]
Agree with your assessment. I'd also re-shear 48.

As far as 12... I'm not entirely sure what to think about that sample.

I guess I'd just use it, as is.

In theory, the larger fragments will get filtered out during library prep. However, the input amount that someone will be using as a guide for library creation will not be able to account for the contribution of the higher molecular weight stuff (which will get filtered out). Thus, the person making the library will, in essence, actually be using _less_ input DNA than they expect. You could advise them of this fact, and you can perform a cursory analysis with the Bioanalyzer software to evaluate what proportion of the sample is that higher molecular weight DNA. Then, you'd tell them to factor that in to their calculations when deciding on the amount of input DNA to use for library prep.

 Does that make sense?

**Comment by yaaminiv** [comment]
> Agree with your assessment. I'd also re-shear 48.

Will do.

> Does that make sense?

Yes! How do I do that? Is that an analysis I need to do before I use the MethylMiner kit?

**Comment by kubu4** [comment]
> How do I do that? 

Like, specific steps? Offhand, I can't remember and I don't have ready access to a Windows computer with the software (but, I will a bit later this morning).

But, basically, there's a way to go into each sample and select/mark regions of the electropherogram. Once you've done that, the software will display some stats about each of the regions you've marked. I suspect that you you can determine a proportion from the stats.

I can get you more specific instructions later this morning.

**Comment by kubu4** [comment]
Alrighty, here're deets on how to determine `% of Total`.

1. Click on desired sample so that you're just viewing a single sample. This can be done by double-clicking on an electropherogram when viewing "All samples", or by clicking the desired sample from the list on the left side.

2. Click on the tab at the bottom of the screen labelled "Region Table".

3. Right-click anywhere on the electropherogram and select "Add Region".

4. Click-and-drag on the blue vertical lines to have them encompass your desired region.

5. Look at info in table below electropherogram that indicates `% of Total`.

That should do it!

**Comment by yaaminiv** [comment]
> Alrighty, here're deets on how to determine % of Total

Thanks! And to clarify: I can look at the % of total to figure out just how much properly sheared/acceptable for enrichment DNA I have?

**Comment by kubu4** [comment]
Yes. This would potentially be info to provide to the sequencing facility. Here's an example:

They need 100ng of DNA to make a library.

You tell them that you gave them 100ng, but, as it turns out, 75% of that is not-sheared.

That means, they'd actually only be getting 25ng of properly sheared DNA to make the library. This might be result in the inability to create a library with sufficient yield for sequencing.

---

So, you would want to advise the sequencing facility of this fact so they can make the adjustment to the amount of input DNA used.

**Comment by yaaminiv** [comment]
> So, you would want to advise the sequencing facility of this fact so they can make the adjustment to the amount of input DNA used.

This would imply that we wouldn't prep the libraries ourselves?

**Comment by kubu4** [comment]
Correct. As mentioned before, we're not preparing the libraries.

**Comment by yaaminiv** [comment]
Looks like I have ~50% of my DNA within 200-600 bp. I'll keep this in mind for the sequencing facility.

![Capture](https://user-images.githubusercontent.com/22335838/89662986-b494ef00-d889-11ea-88bb-cdfca15c863c.PNG)
